### ISSUE TITLE
How to read the value of some variables such as get_enthalpy_flow_terms?

### ISSUE THREAD

**Issue by TheHuangs** [IDAES/idaes-pse#10]
I find that the unit model such as Mixer can call get_enthalpy_flow_terms, which is defined as shown below.
def get_enthalpy_flow_terms(self, p):
        """Create enthalpy flow terms."""
        return self.flow_mol_phase[p] * self.enth_mol_phase[p]
what I need to do is to read this value for some port, when I use the following method to read this value, m.fs.R101.outlet.get_enthalpy_flow_terms['Vap'], Python gave AttributeError: 'SimplePort' object has no attribute 'get_enthalpy_flow_terms'. 
I have found that only the variables defined as the state variable via define_state_vars(self) as shown in the next fig., can be read via m.fs.R101.outlet.temperature[0].value. I guess these variables defined via  define_state_vars(self) are global variables, while other variables are local variables, would you like to tell me how to read such local variables, for example, the get_enthalpy_flow_terms value.
![image](https://user-images.githubusercontent.com/50746074/58685889-c3dbfb00-83af-11e9-801c-4fc9f655306d.png)

**Comment by andrewlee94** [comment]
Hi @TheHuangs. The answer to this is actually fairly involved, and relates to how we define state variables in IDAES and how the models are structured. Firstly, it is not a matter of global or local variables - all components are objects within a tree structure. So, you can always access any component in the tree, but you need to know where to look.

The short answer is that enthalpy is not necessarily part of the `Port` definition (as is the case in the example you are looking at). So, in this case, you cannot ask the `Port` for enthalpy. Instead, you would need to check the `StateBlocks` in the `UnitModel` where you could potentially use the `get_enthalpy_flow_terms` method (as an aside, this method returns an indexed Pyomo `Expression`).

The longer answer:

The first thing to realise here is that `Ports` are not models - they are a collection of other components (mostly `Vars` but sometimes `Expressions`) which are used as a convenient way of linking sub-models together. Simply put, a `Port` is like a `dict` which summarises a list of things we want to connect between sub-models. As such, it does not contain any components of its own, but rather points to components on its parent model. Another important thing to note, as mentioned above, is that the property package developer can chose which variables to use as the state variables - in this case it is flow, temperature and pressure. So, `Ports` do not necessarily contain enthaply.

Secondly, `get_enthalpy_flow_terms` is a method (not a variable) on a `UnitModel` which returns an indexed Pyomo `Expression` representing the enthalpy flow terms. The main purpose of this method is for automating the internal workings of the framework, but can also be used to get expressions for the enthalpy flow at a given state.

So, what is the "correct" way to find a value for a given quantity? Generally, the best way is to find the actual variable object in question within the model structure and then use the Pyomo `value` method to return the current value. IDAES models have a well-defined structure, so the first step is to know where to look. A general summary of the model structure is:

- Flowsheet
    - Unit Model
        - Control Volume
            - State Blocks

State variables and function, such as enthalpy, all exist in the `StateBlocks` so you should look there to find them, i.e. `flowhseet.unit_model.control_volume.state[time].quantity`.

Hope that helps.

**Comment by TheHuangs** [comment]
Thanks for your patient reply.

**Comment by TheHuangs** [comment]
@amdrewlee94, does that mean only the values of variables defined by pyomo `Var` can be read?  how about the expressions.  

In my case flow_mole_phase is defined as Var but not the state variables. Would you give me an exact example for the following abstract example. 
flowhseet.unit_model.control_volume.state[time].quantity
I  have tested the m.fs.R101.control_volume.vap[0]. flow_mole_phase.value, but not success. and how to distinguish between the inlet and outlet of the control volume.

**Comment by andrewlee94** [comment]
`Expressions` can also be read (note that there is a distinction between a Pyomo `Expression` object, and the expressions that are contained within `Constraints` and `Objectives`). You can use `value(Expression)` to return the value of the `Expression` in the same way as a `Var` (but `Expressions` do not have the `value` attribute of a `Var` - i.e `Expression.value` returns a warning).

With the code example you showed above, there are two things to be aware of. Firstly, the `component_objects` method iterates over all the object **containers**, not the data within them. For singleton objects, this is fine, but it does not work as you might expect for indexed components. Instead, you probably want the `component_data_objects` method. Secondly, if you want the values of the `Vars`, you need to use the `value` method. Try the following code:
```
for v in m.component_data_objects(ctype=Var, active=True):
    print(v.name, value(v))
```

Note the `active` argument determines whether "inactivated" components will be considered or not (in this case `Vars` on deactivated `Blocks`, if you have any). Behaviour is:

- `None` (default_ - all components,
- `True` - only activated components,
- 'False' - only inactivated components.

**Comment by TheHuangs** [comment]
Thank you, it seems that print(value(m.fs.R101.control_volume.properties_out[0.0].get_enthalpy_flow_terms)) doesn't work, I want to use get_enthalpy_flow_terms at R101 outlet, but get_enthalpy_flow_terms is a method.

**Comment by andrewlee94** [comment]
Yes, `get_enthalpy_flow_Terms` is a method, so you need to call it first. However, you should note that this is an **extensive** enthalpy flow, i.e. [energy]/[time], not a specific enthalpy terms (i.e. [energy]/[quantity]). If you are looking for the specific enthalpy values, then you should be look for the actual specific enthalpy components (e.g. `enth_mol` - see the documentation for a list of standard names for quantities).

Also note that `get_enthalpy_flow_terms` returns enthalpy on the basis of phase, so you need to provide a valid phase name as well, e.g.

```
print(m.fs.R101.control_volume.properties_out[0.0].get_enthalpy_flow_terms("Vap"))
```

**Comment by andrewlee94** [comment]
@TheHuangs Did this answer all your questions, and have you found the enthalpy terms you need?

**Comment by TheHuangs** [comment]
@Andrewlee94，Your answers are perfect, I have got the value I need. I want to optimize a waste water treatment unit of a gasifier, which need the column model, I know from your papers in 2018, and your groups have developed the column model even the EleNrtl physical properties. Would you like to add the column model and the EleNrtl property package in the contribution  folder if it is not mature? you said that it will be added in the next major release, but I can not wait that long. I can give you feedback if I find bugs.Thank you.

**Comment by andrewlee94** [comment]
I believe the eNRTL model will be available shortly, however the column model needs a lot more work at this stage. WE do hope to have it finished before mid-July however and there should be a release around that date.

**Comment by vinayvm** [comment]
Hi,

I will post here instead of creating a new thread since I have a similar question: regarding accessing value of some variables. Pardon me if the question is stupid. 

Lets say I want to plot holdup of Tank 1 with time as it fills up for "Tutorial_3_Dynamic_Flowsheets.ipynb"
I access tank holdup with `list(m.fs.Tank1.control_volume.volume[:].value)`. Is this the correct way to access the values at all timesteps?
With the way Tutorial 3 is made, we will see a constant value for `height` and `volume` (holdup). Everytime we change the `flow_vol` the holdup of the tank changes. I find this a bit unintutive. This happened even when I initiate the `height` to a very small value (I made sure the magnitude of flowrate corresponds to the time domain). What is exactly happening here?
 
Instead, I would like it if we can : 
1. Inititate the `height` to `0.0` (which is for some reason not possible)
2. define an overflow volume for each tank - the volume beyond which the flow goes to the next tank

How can I make this possible? 

Thanks and kind regards,

**Comment by vinayvm** [comment]
I missed the part that the outflow is connected to the bottom of the tank. 
Indeed `max` function is the way forward for flow based on overflow. Then all that needs to be done is initiate the height to a small value and change the outlet_flowrate rule to 
```
m.fs.Tank1.height_of = Var(initialize=2.0,
                            doc="Tank outlet flow volume")
def outlet_flowrate(m, t):
    return m.control_volume.properties_out[t].flow_vol == (max(0, m.height[t]-m.height_of))*m.control_volume.properties_in[t].flow_vol/(m.height[t]-m.height_of)

m.fs.Tank1.outlet_flowrate = Constraint(m.fs.time, rule=outlet_flowrate)
```
Well at least I was expecting that, but I get  
```
ERROR: Rule failed when generating expression for constraint
    fs.Tank1.outlet_flowrate with index 0.0: TypeError: Relational expression
    used in an unexpected Boolean context.
 The inequality expression:
                0.0  <  fs.Tank1.height[0.0] - fs.Tank1.height_of
            contains non-constant terms (variables) that were evaluated in an
            unexpected Boolean context
```
This is coming from Pyomo?

**Comment by ksbeattie** [comment]
@vinayvm, in the future I think it would be better for you to create a new issue rather than post in a closed one like this.  The reason is that this being a closed issue, we might not see that you've asked a follow on question.

**Comment by andrewlee94** [comment]
@vinayvm You cannot use the Python `max` operator in a Pyomo constraint, as it is not a continuous function. You can use the IDAES `smooth_max` operator instead (see `idaes.core.util.math.smooth_max`).
