### ISSUE TITLE
OMLT/Keras Documentation For New API

### ISSUE THREAD

**Issue by bpaul4** [IDAES/idaes-pse#1003]
The new surrogates API documentation needs further OMLT/Keras content. The [API landing page](https://github.com/IDAES/idaes-pse/tree/main/docs/explanations/modeling_extensions/surrogate/api/index.rst) and [OMLT/Keras](https://github.com/IDAES/idaes-pse/tree/main/docs/explanations/modeling_extensions/surrogate/api/omlt-keras/index.rst) pages should be expanded.

**Comment by ksbeattie** [comment]
@carldlaird, is this (and https://github.com/IDAES/idaes-pse/issues/982) something you'll be able to get to?

**Comment by ksbeattie** [comment]
@carldlaird, is there someone you can assign to this?

**Comment by ksbeattie** [comment]
@rundxdi @Xinhe-Chen is this someone one of you might be able to help with?
