### ISSUE TITLE
Helmholtz Available Components Check

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-pse#1016]
I need to modify the why the Helmholtz property package checks if a component is available.  Currently I assume if it has transport properties on the IDAES side it should be available.  That makes is hard to add new components without modifying IDAES code, especially if you don't care about transport properties. 

I'm not sure how to handle this, but I need to figure it out soon.

**Comment by andrewlee94** [comment]
My first thought is that this sounds like there should be a register of available components, which we populate with the standard ones by default and users can add new one if they have them. Maybe a case for the DMF.

**Comment by eslickj** [comment]
@andrewlee94, yeah the DMF could be a good place to handle this.  That would give a place to put the data files too.  I guess I can add a registry system, and we can take more time to consider the DMF and maybe improving the way we deal with the data files.
