### ISSUE TITLE
IDAES v2 user-support material

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/idaes-pse#1038]
## List of material

- [x] IDAES v1 compatibility mode ([wiki](https://github.com/IDAES/idaes-pse/wiki/idaes-v1-compat)
  - [x] Content
  - [x] Review
- [x] How-to: migrate code from IDAES v1 to v2 ([wiki](https://github.com/IDAES/idaes-pse/wiki/idaes-v2-migrate))
  - [x] Content
    - [x] Import paths
    - [x] `ProcessBlock` kwargs
    - [x] Heat exchanger
  - [x] Review

## Open questions

- [x] Q: To make the nomenclature more consistent, I'm thinking of using "migrating [code][from IDAES v1] to IDAES v2" to describe the action of modifying code developed using IDAES v1 to make it work under IDAES v2. Is "migrating" an acceptable choice for this? A: Changed the material above to use "migrate"

**Comment by dangunter** [comment]
I think migrating/migration is a good term for this
