### ISSUE TITLE
Improve costing implementation

### ISSUE THREAD

**Issue by TimBartholomew** [IDAES/idaes-pse#104]
After adding costing to some of my NAWI work, I think there are a few places where we can change our costing implementation.

Here are two things that I think are easy changes:

1. We should use `**kwargs` in the Unit_Model_costing function call in the get_costing method for each unit model. This way the financial modules don't need to include all the key word arguments.
2.  We should make it standard for financial modules to create a block with all the costing parameters on the flowsheet. This would act similarly as the properties parameter block. This would help with sensitivity analyses and I think is just a better way than an example costing module I saw on IDAES that created a new parameter on the unit model costing block.

Other bigger picture things we should think about:
- Should a "costing package" be more implemented like a "properties package"?
    - where we define it on the flowsheet with `m.fs.costing = financials.CostingParameterBlock"
    - we feed it into unit models with `"costing_package" = m.fs.costing`
    - if a costing package is provided to the unit model, then the unit costing block is created along with the costing variables and constraints. Currently, we must call the get_costing method on each unit model in the flowsheet script to do this.
 - We may need to set up naming conventions for costing. We already do that for what the functions in financial modules must be called, but we don't have standard variable names. Generally the naming conventions won't be as big of a deal as property packages, but it would be important if we envision someone using 2 financial modules (costing packages) in the same flowsheet.

**Comment by andrewlee94** [comment]
Closing this in light of the ongoing development of a new costing framework.
