### ISSUE TITLE
Separator unit model doesn't support MomentumBalanceType

### ISSUE THREAD

**Issue by NCJazzMan65** [IDAES/idaes-pse#1046]
I would like to use a separator unit model to split a solids stream into multiple solids streams.  Looking through the separator unit model code, this looks like it should be possible but when I try it in my model it doesn't work.  I get a message that says my properties package must support pressure, which my solids property package does not.  It looks like the separator unit model doesn't support the MomentumBalanceType property like other unit models do (HeatExchanger for instance).

**Comment by andrewlee94** [comment]
@NCJazzMan65 Support for this should be merged into the main branch in the new few hours - it won't be in a release branch until February however.
