### ISSUE TITLE
PySMO: Fix broken np.array calls due to numpy changes

### ISSUE THREAD

**Issue by OOAmusat** [IDAES/idaes-pse#1065]
Changes to numpy have broken some numpy calls in PySMO. Calls of the type:

``t1 = np.array([list of variables])`` 

which worked fine as at numpy 1.22.3 no longer work in some numpy 1.24.1 cases. 

The failures appears to occur trying converting a list of a mixture of variable types into an array e.g.,  lists containing mixtures of scalar and indexed pyomo variables.

**Comment by OOAmusat** [comment]
Solution appears to be to add the dtype argument, 

``t1 = np.array([list of variables],dtype=object)``

Need to test that it works across versions.

**Comment by lbianchi-lbl** [comment]
@OOAmusat, does this causes any of the IDAES tests to break? just asking since I haven't noticed it yet but I might just have missed it.

**Comment by OOAmusat** [comment]
@lbianchi-lbl No, not that I know of. We don't have any tests that use a mixture of variable types, afaik.

**Comment by ksbeattie** [comment]
@OOAmusat do you have an example/test case of this failing?  Otherwise, it isn't clear if this something we, within idaes, can fix.

**Comment by lbianchi-lbl** [comment]
![image](https://user-images.githubusercontent.com/48035537/216437347-97a92183-3726-40bd-986a-48ecad510f26.png)

For reference: we're already using Numpy 1.24.1, so if there's anything in IDAES that would trigger the error we would realize since the tests would fail.

**Comment by OOAmusat** [comment]
We don't have an example testing for this specifically in IDAES now because it wasn't a problem previously. I didn't even know it was a problem until a collaborator on WaterTAP tried passing in a list of Pyomo variables in a specific way and got the error.

I could probably write a text that checks for the specific error though (once I fix it).
