### ISSUE TITLE
Funky process flow diagrams in documentation

### ISSUE THREAD

**Issue by adam-a-a** [IDAES/idaes-pse#1071]
I was revisiting IDAES' documentation and stumbled upon some jumbled PFDs for the NGCC flowsheet (https://idaes.github.io/examples-pse/latest/Examples/Flowsheets/power_generation/ngcc/ngcc_doc.html). These should probably be fixed at some point, and I suspect this issue is in more places within the documentation, though I didn't conduct a thorough search. I'm guessing this is an issue for @dangunter to check out. See snapshots below to see what I mean:
![image](https://user-images.githubusercontent.com/22691844/214878604-e8f8334b-ae05-4473-8bda-6d8c28de6e76.png)
![image](https://user-images.githubusercontent.com/22691844/214879033-825948cc-6593-40fa-9281-82a6d1234136.png)
![image](https://user-images.githubusercontent.com/22691844/214879243-829d2a32-51e3-47fc-94ab-4da51c535912.png)

**Comment by bpaul4** [comment]
Hi @adam-a-a, thanks for opening this issue. I did a cursory check of the power generation docs that are built from the example notebooks, and it appears that loading from PNG works as expected; only loading from SVG presents the jumbled images as seen above. It's likely a parsing issue with loading the SVG tags.

**Comment by andrewlee94** [comment]
We are currently in the process of moving examples over to a new repo, and these examples are not likely being moved over (although we might find another location to put these). As such, fixing these is not a high priority right now.

**Comment by eslickj** [comment]
That's a problem with SVG.  The font is inconsistent since the fonts don't come along with the SVG.  These look fine in a browser, but I guess whatever is doing the conversion from SVG to PNG or whatever is having an issue with fonts.

**Comment by eslickj** [comment]
NGFC has issues too.  https://idaes.github.io/examples-pse/latest/Examples/Flowsheets/power_generation/ngfc/NGFC_flowsheet_doc.html.  But I checked and it looks fine in my browser if I run the actual notebook.

I guess we need to find what renders the SVGs for the docs and figure out what it doesn't like.

**Comment by eslickj** [comment]
Think this is fixed due to the move to JupyterBook in the new examples repo.  As far as I know the SVGs always look pretty good in a web browser.  At least we can open a new issue if there are issues in the new repo.
