### ISSUE TITLE
Power Plant Costing NGCC+SOEC Bug with New NL-Writer

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-pse#1084]
There seems to be some kind of bug where the power plant costing as used in the NGCC+SOEC example doesn't work with the new Pyomo NL-writer. See https://github.com/IDAES/examples/pull/10#issuecomment-1421058954.  The problematic constraints seem to (at least) be the bare_erected_cost.  The constraints are generated here https://github.com/IDAES/idaes-pse/blob/a2140155169eb3ffd058afd7f41e40e82a7473eb/idaes/models_extra/power_generation/costing/power_plant_capcost.py#L1020.

The constraints did work with the old nl-writer and I can evaluate the constraints without issue. 

I broke into Pyomo nl_writer.py and printed some stuff to try to diagnose the problem. I'm not sure what's going on but something isn't right.  At the very least the AMLP repn has a variable, and the variable list is empty.  I suspect the AMPL repn is just wrong, but I'm not sure.

```
in _write_nl_expression
nl = 
o2
n0.001
o2
n-13.209932196966305
o5
o2
n9.328531204477933e-07
v%s
n0

repn = AMPLRepn(mult=1, const=0.0, linear={6085815296: 0.001}, nonlinear=('o2\nn0.001\no2\nn-13.209932196966305\no5\no2\nn9.328531204477933e-07\nv%s\nn0\n', []), nl=None, named_exprs={6264423296})

args = []

repn.nolinear = ('o2\nn0.001\no2\nn-13.209932196966305\no5\no2\nn9.328531204477933e-07\nv%s\nn0\n', [])

at line 1203:
info[0] = fs.b1.costing.bare_erected_cost_eq['8.4']
info[0].body = (fs.b1.costing.bare_erected_cost['8.4'] - 0.001*(MUSD_2018/kUSD_2018)*(fs.b1.costing.ref_cost['8.4']*kUSD_2018)*((7936.641438655591*(lb*s/h/kg)*(fs.ngcc.hrsg.prop_gas.mw_comp[N2]*fs.ngcc.hrsg.econ_hp1.hot_side.properties_in[0.0].flow_mol_comp[N2] + fs.ngcc.hrsg.prop_gas.mw_comp[O2]*fs.ngcc.hrsg.econ_hp1.hot_side.properties_in[0.0].flow_mol_comp[O2] + fs.ngcc.hrsg.prop_gas.mw_comp[CO2]*fs.ngcc.hrsg.econ_hp1.hot_side.properties_in[0.0].flow_mol_comp[CO2] + fs.ngcc.hrsg.prop_gas.mw_comp[H2O]*fs.ngcc.hrsg.econ_hp1.hot_side.properties_in[0.0].flow_mol_comp[H2O]))/(fs.b1.costing.ref_param['8.4']*(lb/h)))**fs.b1.costing.exp['8.4'])*0.001
```

**Comment by andrewlee94** [comment]
@jsiirola Is aware of this and is going to look into it when he has the time. He is fairly certain it is a bug in the NL writer, as the it producing an invalid `repn` for AMPL.

**Comment by eslickj** [comment]
Link to specific notebook that shows failure

https://github.com/IDAES/examples-pse/blob/main/src/Examples/Flowsheets/power_generation/ngcc/ngcc_soec.ipynb.

**Comment by jsiirola** [comment]
Fix is up as Pyomo/pyomo#2726

**Comment by dangunter** [comment]
fwiw, the current version of that same notebook in the new examples repo (currently in a PR): 
https://github.com/IDAES/examples/pull/10/files#diff-9e2f725b11351296a9dbf1d6eaa45f4891e190f159faf6d989505ebc16c257c2

**Comment by jsiirola** [comment]
Fix is merged onto Pyomo/main
