### ISSUE TITLE
Add max_iter to default ipopt config?

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-pse#1099]
I was running the ideas-pse tests without HSL stuff and some solves failed after like 3000 iterations.  I think most initialization routines and other things that use a solver in the idaes-pse repo use ``get_sover()``, so we could probably just globally restrict the number of iterations by adding "max_iter" to the defaults IDAES config.  For things in the core idaes repo we may also want to use ``get_solver()`` everywhere.

**Comment by andrewlee94** [comment]
Please do - the default should probably only be 100 or so (quite possible even less). That said, a lot of people seem to want to manually set this at some ridiculous value too.
