### ISSUE TITLE
Add to defined properties

### ISSUE THREAD

**Issue by adam-a-a** [IDAES/idaes-pse#1113]
As commented by @andrewlee94 in WaterTAP (https://github.com/watertap-org/watertap/pull/937/files#r1123757875), the osmotic coefficient should probably be added to defined properties. We currently have it named `osm_coeff` in WaterTAP.

**Comment by andrewlee94** [comment]
I was actually primarily referring to the fact that `enth_flow` was not defined as a standard property, but the osmotic coefficient could also be added (maybe to the electrolyte property set).

**Comment by adam-a-a** [comment]
So maybe it's best to add several (assuming several exist) standard properties (assuming several exist). This ties to @bkneuven's issue on WaterTAP: https://github.com/watertap-org/watertap/issues/940

Based on what we aggregate in WaterTAP, we could decide which properties should go up to IDAES and which are likely to be more relevant as standards in WaterTAP (if any discrepancies exist).

**Comment by ksbeattie** [comment]
@adam-a-a is this something you can do for the May release?  If so, we can put it on that release board.
