### ISSUE TITLE
Failures on Python 3.11 for logging configuration tests

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/idaes-pse#1140]
![image](https://user-images.githubusercontent.com/48035537/225987927-13299b6b-d1d6-49cc-924c-b475c2389eb5.png)

The offending test (which will be skipped on 3.11 starting with #1137) is:

![image](https://user-images.githubusercontent.com/48035537/225988622-9ac495e5-82ca-4e21-92ba-ed4f8ea29c8c.png)

(Using a screenshot since permalinks with the commit hash might not work if the PR head branch is deleted or rebased)

**Comment by eslickj** [comment]
I don't think this failure really has anything to do with logging.  It's testing the command line tool to edit the IDAES config file.  I guess the problematic file access is reading/writing json files.  I don't really see how this can happen, unless there is some weird asynchronous business going on.  The file is only opened in a with block.

We may just want to remove the whole command-line configuration thing.  Nobody uses it and I'm not sure it was a good idea.  It's probably easier just to edit the json file.
