### ISSUE TITLE
"gaussian" rbf type always displayed when loading surrogate using `PysmoSurrogate.load_from_file()`

### ISSUE THREAD

**Issue by hunterbarber** [IDAES/idaes-pse#1164]
I performed independent surrogate training for all radial basis functions using the config argument in  `PysmoRBFTrainer()` When training, the terminal display is for example,
```
Default parameter estimation method is used.

Parameter estimation method:  algebraic
Basis function:  imq
Regularization done:  True
```
The main thing is that it correctly reports the basis function.

However, when reloading ANY of the surrogates with various rbf's using `PysmoSurrogate.load_from_file()`, the terminal output ALWAYS shows
```
Default parameter estimation method is used.

Parameter estimation method:  algebraic
Gaussian basis function is used.
Basis function:  gaussian
Regularization done:  True
```
 This may be a problem in line 318 of idaes\core\surrogate\pysmo\radial_basis_function.py, but not certain

**EDIT** @lbianchi-lbl : this is the line mentioned: https://github.com/IDAES/idaes-pse/blob/f9c4fd319a590a839007db2605543b523904fa86/idaes/core/surrogate/pysmo/radial_basis_function.py#L318

**Comment by OOAmusat** [comment]
fISED IN #1166
