### ISSUE TITLE
Update IDAES docs with new instrcutions for getting examples

### ISSUE THREAD

**Issue by andrewlee94** [IDAES/idaes-pse#1172]
The IDAES docs still point to the old `get-examples` command for installing the example notebooks: https://idaes-pse.readthedocs.io/en/latest/reference_guides/commands/get_examples.html#idaes-get-examples-fetch-example-scripts-and-jupyter-notebooks

This should be updated, and we should also check for any other outdated pointers to the examples.

**Comment by lbianchi-lbl** [comment]
Isn't this what #1132 is about?

**Comment by andrewlee94** [comment]
@lbianchi-lbl Quite probably - however I am starting to field complaints about the examples "not working" so we had better get it merged quickly.

**Comment by lbianchi-lbl** [comment]
Closing this as #1132 got merged.
