### ISSUE TITLE
Documentation of idaes.core.util.math is missing

### ISSUE THREAD

**Issue by andrewlee94** [IDAES/idaes-pse#1176]
It appears that documentation of the maths utility methods slipped through a crack - we should add a page for these in the docs.

https://github.com/IDAES/idaes-pse/blob/main/idaes/core/util/math.py

**Comment by lbianchi-lbl** [comment]
Some documentation exists in https://github.com/IDAES/idaes-pse/blob/main/idaes/core/util/math.py; the action item would be to 1) review the existing documentation and improve it if needed; 2) make sure that it gets included into the Sphinx build (via `autodoc` or whatever method we're using).

**Comment by lbianchi-lbl** [comment]
Resolved by #1213.
