### ISSUE TITLE
Document Manual IDAES-EXT Install

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-pse#119]
There is a pretty easy manual install process for the idaes binary extensions.  Goto https://github.com/IDAES/idaes-ext/releases/ and download the tar files for the release and platform you want and extract them in the directory that is given by the ```idaes bin-directory``` command.  This is probably going to be useful to some people where their security setup prevents the download using ```idaes get-extensions```

Also should probably ask @jsiirola to checkout the pyutilib file download utility.  @carldlaird reported trouble with self signed cert error when using a proxy.  Not sure if it's fixable, but that initiated this issue.

**Comment by jsiirola** [comment]
@eslickj: the Pyomo FileDownloader has two options for managing SSL certificates:
```python
class FileDownloader(object):
    def __init__(self, insecure=False, cacert=None):
        # ...
```
You can specify a specific CACert file with `cacert=`, or you can turn off all SSL verification with `insecure=True` when creating the `FileDownloader`, or by setting the corresponding public attributes after the object is created.

**Comment by eslickj** [comment]
@jsiirola, thanks I can add options for these to the get-extensions command.  Any thoughts on what the default behavior should be?

**Comment by jsiirola** [comment]
Default behavior should definitely be `insecure=False`.  I am not sure that a default CACert other than `None`would make any sense.

**Comment by eslickj** [comment]
@jsiirola yeah, I guess now that I think about it, that was a stupid question.

There is a PR for the insecure and cacert options (#121).  I'll add the manual install to the docs seperatly.

**Comment by adowling2** [comment]
@eslickj @jsiirola @ksbeattie We now have fairly well tested (N=8 computers/users) macOS manual installation instructions here: https://github.com/IDAES/idaes-ext/blob/adowling2-macos/macOS_notes.md
