### ISSUE TITLE
Demo Flowsheet Test Failures

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-pse#1198]
There are some demo flowsheet test failures on RHEL7 see https://github.com/IDAES/idaes-ext/actions/runs/5212024395/jobs/9405076893.

**Comment by ksbeattie** [comment]
@bpaul4 & @MarcusHolly could you take a look to see if this is still an issue?

**Comment by andrewlee94** [comment]
I am seeing some failures locally when I run these tests (these started failing in the past few days, and I am not sure why).

**Comment by MarcusHolly** [comment]
@andrewlee94 To run these tests locally, do we run `sh build.sh {platform}` for the two failing jobs (centos7 and debian9)? If so, I'm seeing vulnerabilities but nothing specifically pointing to the demo flowsheet.

**Comment by andrewlee94** [comment]
@MarcusHolly This shouldn't need you to build anything unless you are attempting to run the tests locally on different platforms (in which case I have no idea how to do it properly).

The better place to start would be to apply the DiagnosticsToolbox to the model and see what it comes up with first. If the problem is numeric, then it shouldn't matter what system you run it on - the issues will be the same across all systems but different systems might react differently to those issues.

**Comment by MarcusHolly** [comment]
@andrewlee94 My tests are passing locally when I run them (Python 3.10.12; pytest-7.4.0; pluggy-1.2.0). However, when I copy these files over to a different environment (Python 3.8.13; pytest-7.1.3; pluggy-1.0.0), I'm getting an InitializationError. Is this what you're seeing locally as well? If so, I can work on resolving this.

According to the DiagnosticsToolbox, the only issue is two of the mole fracs being set at its upper bound (1). After resolving this, I still get no failures in my first environment and the same failures in my second environment...

**Comment by andrewlee94** [comment]
I get two tests fail - the initialization test and the subsequent solve_flowsheet test. The error I see is:

```
E           idaes.core.util.exceptions.InitializationError: fs.M01.inlet_2_state failed to initialize successfully. Please check the output logs for more information.

idaes/models/properties/activity_coeff_models/activity_coeff_prop_pack.py:666: InitializationError
```

For the diagnostics, how many numerical cautions do you get (there might not be any warnings, but a lot of cautions is also a bad sign)? Also, make sure you run the tools on the failed initialization to see what it tells you then.

**Comment by MarcusHolly** [comment]
Okay, I'm seeing those same errors. And there are a lot of cautions, so I'll try to work through resolving this today.
![image](https://github.com/IDAES/idaes-pse/assets/96305519/5cd3b6b6-3c9c-4f8c-a1bd-e9d7dca58e31)

**Comment by bpaul4** [comment]
Completed via #1266.
