### ISSUE TITLE
Integration tests for 'idaes get-examples' fail non-deterministically because of GitHub API limits

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/idaes-pse#120]
## Description

- `idaes.commands.examples.get_examples()` uses the GitHub API (through `requests.get()`) to fetch metadata and assets for the IDAES examples
- This functionality is tested as part of the integration tests in `idaes/commands/tests/test_commands.py`
- GitHub API limits are checked on a per-IP address basis, so running the tests as part of the CI checks can trigger the limit if e.g. the CI runners are on the same network node and all API calls happen to occur in a short enough time window
- This condition is difficult to reproduce or predict (since it depends on low-level implementation details of the CI infrastructure running the tests) and thus ends up causing non-deterministic test failures that do not depend on the tests themselves
- See e.g. https://github.com/IDAES/idaes-pse/runs/1528160933?check_suite_focus=true for an example

## Solutions

- The GitHub API limits are not enforced (or less stringent) if they come from an authenticated client
  - Somewhat confusingly, the fact that the CI checks are running on GitHub Actions (i.e. the CI infrastructure), and the cause of the GitHub API limits (i.e. the `get_examples()` code) are not direcly related: this error could occur if we were using a different CI provider as well
  - Arguably, one could expect that the GitHub API would be aware that the API calls come from GitHub itself and take this into account when enforcing the limits, but apparently this is a deliberate choice (TODO: link) (which in the end makes sense, since GitHub Actions can run arbitrary workflows and thus shouldn't be considered "trusted" by the GitHub API)
- Taking this into account, one way to address this would be to make sure that the API calls in `idaes.commands.examples.get_examples()` are authenticated
- This could be done conditionally by detecting whether the tests are being run in a GitHub Actions runner, and adding a header with an authentication token if so
  - Both of these (detection and token) could be done at once by checking for `os.environ.get('GITHUB_TOKEN') is not None`
  - `GITHUB_TOKEN` is a special API auth token available by default in the runner environment
  - It should be sufficient for our purposes since the API calls issued in `get_examples()` don't require particular repo permissions (just accessing a public repo)

If this sounds reasonable, I could take a stab at making a PR to address this. The real challenge would be being able to test it, since the error belongs to both the "Testing the tests" and "Unpredictable external conditions" categories of extra complications...

**Comment by ksbeattie** [comment]
@lbianchi-lbl will add a "flaky" test mark, so people will know to try re-running it when it fails.

**Comment by ksbeattie** [comment]
no longer a problem (procrastination wins again!)
