### ISSUE TITLE
Unable to run pytest on a single test file

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/idaes-pse#1200]
As originally reported by @dallan-keylogic:

## Description

- It used to be possible to run pytest on a single test file by specifying the path to the test file as a command-line argument, e.g.: `pytest idaes/models/properties/modular_properties/eos/tests/test_enrtl.py`
- However, since recently, it seems this is not possible anymore: the same command runs all tests regardless of what file is specified

## Probable cause

- Changes to `pytest.ini` in #1133 added a default command-line flag (`--pyargs idaes`) that specifies the location of the `idaes` package as the testpath
  - This was done to ensure more consistent behavior regardless of e.g. the working directory where `pytest` is invoked, as well as forcing the tests to be collected from the installed package (as opposed from the local directory, in case the two are not the same)
- However, this cause the unwanted side effect of always adding all tests inside the `idaes` package directory (and subdirectories) to the current test run, effectively rendering the option of specifying individual test files or directories non-functional

## Workarounds

- Edit `pytest.ini` locally to remove the offending `--pyargs idaes` CLI flag
- To select a subset of the tests to be run, use keywords through the `-k` CLI option https://docs.pytest.org/en/7.2.x/reference/reference.html#command-line-flags instead of passing file paths as arguments
  - Note that this has an overhead since all tests still need to be collected first, which might take several seconds because of the size of the IDAES codebase and the amount of import-time metaprogramming

## Remedies

- To reduce the possibility of these issues occurring in the future, we should consider carefully how the pytest configuration should be distributed between file(s), CLI flags, env vars, etc

## Other useful info

- To show what tests would be run with the current configuration without actually running them, add `--collect-only` to the pytest CLI options

**Comment by Robbybp** [comment]
Any update on a more permanent solution for this? This makes developing IDAES very cumbersome (at least by my workflow).

**Comment by andrewlee94** [comment]
@lbianchi-lbl I believe most of us were used to just running doing `pytest [filename]` or running `pytest` from in a subfolder of IDAES to run specific tests.

The first can be replicated using the `-k` flag (although it does give less control overall, e.g. files/test with duplicate names in different folders/modules), but I don't know how you would do the second.

**Comment by Robbybp** [comment]
Yes, I am used to running `pytest filename` or just `pytest` to run tests for a specific file, or those in and below my current working directory. My workaround is `pytest -k filename`, which is not bad (as long as I remember the `-k`), but does incur a cost of a few seconds collecting all the tests, which greatly increases the amount of time it takes to test a single file.
