### ISSUE TITLE
Spellcheck CI jobs failing with no change in content being checked

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/idaes-pse#1203]
This seems to be due to a different version of the underlying `typos` tool, compare e.g.:

- [Last passing run](https://github.com/IDAES/idaes-pse/actions/runs/5207558856/jobs/9395232371), v1.14.12
- [First failing run](https://github.com/IDAES/idaes-pse/actions/runs/5213770931/jobs/9409202002), v1.15

**Comment by mrmundt** [comment]
I noticed this, too, @lbianchi-lbl, on the Pyomo side. It looks like the new minor version bump added in more “commonly misspelled” words. I’ll open a PR for IDAES to resolve this.

**Comment by lbianchi-lbl** [comment]
> I noticed this, too, @lbianchi-lbl, on the Pyomo side. It looks like the new minor version bump added in more “commonly misspelled” words. I’ll open a PR for IDAES to resolve this.

Thanks @mrmundt. I think it'd be OK (or even preferable) to pin the version to 1.14.12 as a short-term fix so that the CI suite is usable again, but I'll leave it up to you.

**Comment by mrmundt** [comment]
@lbianchi-lbl - PR open.
