### ISSUE TITLE
PySMO Basics Example Failure

### ISSUE THREAD

**Issue by bpaul4** [IDAES/idaes-pse#1215]
A failiure appearing in the `pysmo_basics` example notebook presents as:

```
File /usr/share/miniconda/envs/idaes-pse-dev/lib/python3.10/site-packages/scipy/optimize/_minimize.py:533, in minimize(fun, x0, args, method, jac, hess, hessp, bounds, constraints, tol, callback, options)
    530 x0 = np.atleast_1d(np.asarray(x0))
    532 if x0.ndim != 1:
--> 533     raise ValueError("'x0' must only have one dimension.")
    535 if x0.dtype.kind in np.typecodes["AllInteger"]:
    536     x0 = np.asarray(x0, dtype=float)

ValueError: 'x0' must only have one dimension.
```

From a quick error tracing, it appears the source is the Kriging parameter optimization method, either something has changed in a recent `numpy` or `scipy` update or there is an issue in reshaping `initial_value_list`:

```
def parameter_optimization(self, p):
        """
        Parameter (theta) optimization using BFGS or Basinhopping algorithm. This is the core of the Kriging Class.
        Algorithm used will depend on whether the numerical_gradients was set to True or False.
        """
        initial_value_list = np.random.randn(
            self.num_vars - 1,
        )
        initial_value_list = initial_value_list.tolist()
        initial_value_list.append(1e-4)
        initial_value = np.array(initial_value_list)
        initial_value = initial_value.reshape(initial_value.shape[0], 1)
        # Create bounds for variables. All logthetas btw (-4, 4), reg param between (1e-9, 0.1)
        bounds = []
        for i in range(0, len(initial_value_list)):
            if i == len(initial_value_list) - 1:
                if self.regularization is True:
                    bounds.append((1e-6, 0.1))
                else:
                    bounds.append((1e-10, 1e-10))
            else:
                bounds.append((-3, 3))
        bounds = tuple(bounds)

        if self.num_grads:
            print("Optimizing kriging parameters using L-BFGS-B algorithm...")
            other_args = (self.x_data_scaled, self.y_data, p)
            # opt_results = opt.minimize(self.objective_function, initial_value, args=other_args, method='L-BFGS-B', jac=self.numerical_gradient, bounds=bounds, options={'gtol': 1e-7}) #, 'disp': True})
            opt_results1 = opt.minimize(
                self.objective_function,
                initial_value,
                args=other_args,
                method="tnc",
                jac=self.numerical_gradient,
                bounds=bounds,
                options={"gtol": 1e-7},
            )
```

`initial_value` is the object `x0` with the wrong shape in the notebook error.

**Comment by lbianchi-lbl** [comment]
This is likely related to NumPy 1.25.0 (only available for Python 3.9+, which explains why the 3.8 checks are passing as theyr'e using an older version).

**Comment by OOAmusat** [comment]
@bpaul4 @lbianchi-lbl It could also be a scipy problem - a new version was released this week (https://scipy.org/news/), and I saw something about ``scipy.minimize`` making some changes to the shapes of their arrays. Apparently there was a deprecation warning in 1.10 (https://github.com/scipy/scipy/issues/16898). 

I'll take a look at this.

**Comment by lbianchi-lbl** [comment]
> @bpaul4 @lbianchi-lbl It could also be a scipy problem - a new version was released this week (https://scipy.org/news/), and I saw something about `scipy.minimize` making some changes to the shapes of their arrays. Apparently there was a deprecation warning in 1.10 ([scipy/scipy#16898](https://github.com/scipy/scipy/issues/16898)).
> 
> I'll take a look at this soon.

Good point, thanks. To my non-expert eye, this looks more likely judging from the PySMO code.
