### ISSUE TITLE
Example Breaks with Latest PETSc Version

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-pse#1217]
There is a test failure in the PR #1199.  The details are there, but it is due to an update in the PETSc version.  The breaking example is ```/examples/idaes_examples/mod/co2_adsorption_desorption/simulation_utilities.py```.  There is more detail in the PR.  The failure is not in the dynamic solve, but the nonlinear initial condition solve for desorption.  I used PR #1211, to try IPOPT and the solve still fails.  I think the failure is due to a very fragile problem, that we just got really lucky on before with the previous version of PETSc.

**Comment by lbianchi-lbl** [comment]
This is preventing us from updating the `idaes-ext` version (#1199).

**Comment by ksbeattie** [comment]
This is part of https://github.com/IDAES/examples/issues/70
