### ISSUE TITLE
Add uncertainty propagation toolbox

### ISSUE THREAD

**Issue by adowling2** [IDAES/idaes-pse#122]
High-level steps:
- [x] Discuss with @dangunter @ksbeattie @jghouse88 @andrewlee94 where to place the code (we can do that in this issue)
- [x] Open PR on idaes-pse, include info if it requires a specific Pyomo version/PR
- [ ] Add general library
- [ ] Add example/unit tests from the workshop tutorial
- [ ] Create documentation page
- [ ] Iterate with reviewers

**Comment by adowling2** [comment]
This toolbox will allow propagating uncertainty in model parameters (encoded in a covariance matrix) through an IDAES simulation/optimization process model. Right now, we are using k_aug. In the future, this can be extended to support sampling-based approaches.

**Comment by adowling2** [comment]
I propose `idaes-pse/idaes/apps/uncertainty`. Comments? @dangunter @ksbeattie @jghouse88 @andrewlee94

**Comment by jghouse88** [comment]
@adowling2 That sounds like the right location. Cannot think of anything else.

**Comment by adowling2** [comment]
Regarding conventions: `uncertainty` versus `uncertainty_propagation` versus `uncertainty_toolbox`? Also `_` versus `-`?

**Comment by adowling2** [comment]
Right now, my preference is `uncertainty_propagation`.

**Comment by andrewlee94** [comment]
I believe we tend to use underscores (and it is more Pythonic?). I would also go with `uncertainty_toolbox` as something more extensible for the future.

**Comment by dangunter** [comment]
To me, 'toolbox' doesn't add enough information to be worth making the sub-package name longer.

**Comment by JanghoPark-LBL** [comment]
Thanks for all your opinions. I will go with `idaes-pse/idaes/apps/uncertainty_propagation`.
