### ISSUE TITLE
Remove references to Pyomo `expr.current`

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/idaes-pse#1227]
Needed once Pyomo/pyomo#2910 is merged. See @blnicho's message https://github.com/Pyomo/pyomo/pull/2910#pullrequestreview-1544232295:
 
> This looks fine. I just did a quick check of IDAES and it looks like there are a handful of files that are importing from `expr.current` that will need to get updated after this is merged and the IDAES tag of Pyomo is bumped (FYI, @andrewlee94 and @lbianchi-lbl)

**Comment by blnicho** [comment]
This was fixed in #1234
