### ISSUE TITLE
Pysmo tests np.testing.assert_array_equal() fail because of ordering

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/idaes-pse#1253]
- Current best guess is that something is affecting the ordering and therefore causes the assertions to fail
- Possibly related to pandas 2.1 being released

**Comment by ksbeattie** [comment]
@OOAmusat Is there any chance you could take a look at this and see if there is an easy fix without pinning to a specific/old version of pandas?

**Comment by OOAmusat** [comment]
There seems to be no re-ordering with df.filter  in pandas 2.1 which is breaking some of the sampling code.  For example, with the dataframe below:

```
import pandas as pd

input_array_pd = pd.DataFrame(
    {
        "x1": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        "x2": [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
        "y1": [11, 14, 19, 26, 35, 46, 59, 74, 91, 110],
        "y2": [21, 24, 29, 36, 45, 56, 69, 84, 101, 120],
    }
)

x_lab = ["y1", "x1"]
input_array_pd.filter(x_lab)
```

Pandas pre-2.1 would return:
```
    y1  x1
0   11   0
1   14   1
2   19   2
3   26   3
4   35   4
5   46   5
6   59   6
7   74   7
8   91   8
9  110   9
```

while the new pandas 2.1 returns 

```
   x1   y1
0   0   11
1   1   14
2   2   19
3   3   26
4   4   35
5   5   46
6   6   59
7   7   74
8   8   91
9   9  110
```

This is breaking column selections in our sampling tests, as we check that the specified column order is maintained in the tests.

I have created an issue on pandas github - hopefully this is a bug and not a permanent change.

**Comment by OOAmusat** [comment]
Yeah, it is a bug, and they expect it to be fixed in the next release:

https://github.com/pandas-dev/pandas/issues/55075

**Comment by andrewlee94** [comment]
So, we should be able to add something like `pandas!=2.1` to our `setup.py` then so than we switch to the new version once it is released and so that users don;t run into this problem.
