### ISSUE TITLE
Possible spurious failure in Pysmo kriging tests

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/idaes-pse#1258]
This occurred in https://github.com/IDAES/idaes-pse/actions/runs/6041051733 for a single job run and seems unrelated to #1253.

![image](https://github.com/IDAES/idaes-pse/assets/48035537/35806dfa-80a5-4633-baa3-6d90d64a0c29)

**Comment by andrewlee94** [comment]
The Pysomo tests are known to have an issue with non-deterministic behavior. Specifically, I think it is because the sampling steps are not seeded and thus we get a new set of sample points each time we run the tests and occasionally this results in an infeasible solution.

**Comment by ksbeattie** [comment]
@OOAmusat would this be easy/possible to fix as well?

**Comment by OOAmusat** [comment]
@lbianchi-lbl @ksbeattie This is due to random number generation in the initialization and solution steps.

I have attempted to fix the issue by fixing the numpy random seed generator for this test (PR #1264), but since it is a random failure there is no way to know if the fix works.
