### ISSUE TITLE
HeatExchanger0D initialization bug

### ISSUE THREAD

**Issue by jghouse88** [IDAES/idaes-pse#127]
Noticed the following bug while working on the unit model tutorial with @anujad95. 

- If Q is fixed as part of the initial specifications, and `initialize()` is called --> initialization unfixes the side2.heat and results in 1 DOF
- If delta_T_in or delta_T_out is fixed as part of the initial specifications, too few degrees of freedom is raised during the initialization

Documentation needs to be updated: The docs mention that the var `delta_temperature` is available as a potential DOF but these should be `delta_temperature_in` or `delta_temperature_out`. Please correct if we are wrong.

**Comment by eslickj** [comment]
Sounds like you are right.  Lotta options there.  Sometime soon we should discuss initialization in general, but I can fix these right away.  I guess the docs should probably just explicitly say what different options are for initializing the model.

So what options do we want?

1) Specify inlets, U, and A.
2) Specify inlets, free U or A, and fix Q
3) Specify inlets and free U or A and fix delta_temperature_in or out.  Obviously if cocurrent inlet_delta_T is not good enough.
4) Specify inlets, free U or A and an outlet temperature
5) Specify inlets minus one flow and something else...
