### ISSUE TITLE
Preparations for possible breaking changes in upcoming releases of Numpy and/or pandas

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/idaes-pse#1322]
Creating an issue to track this after @mrmundt brought this up.

## Numpy
- Upcoming v2.0 has a number of backward-incompatible changes
  - https://numpy.org/devdocs/numpy_2_0_migration_guide.html

## pandas
- `pyarrow` will become a requirement; causes a warning to be emitted on import (?)
  - See also https://github.com/Pyomo/pyomo/pull/3102

**Comment by mrmundt** [comment]
Tagging for ease of finding later: https://github.com/numpy/numpy/issues/24300
