### ISSUE TITLE
PETSc solver interpolate bug

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-pse#1326]
I'm not sure if this is a bug in IDAES or Pyomo, but with PETSc solver interpolation there is an issue setting variables with units.  I put an issue in Pyomo https://github.com/Pyomo/pyomo/issues/3123.   Here https://github.com/IDAES/idaes-pse/blob/190451a457fcc69aa73c7253f09bec17cd870112/idaes/core/solvers/petsc.py#L713, we are setting variables from a numpy float.  This causes a Pyomo exception detailed by the Pyomo issue, if the variable has units.

**Comment by dallan-keylogic** [comment]
As far as I can tell, this is a Pyomo issue, detailed here:

https://github.com/Pyomo/pyomo/issues/3100.
