### ISSUE TITLE
Update spatial domain as another continuous set in dynamic model simulation.

### ISSUE THREAD

**Issue by minhwvu** [IDAES/idaes-pse#14]
Hi all, I am trying to apply the IDAES platform to my heat conduction model, which is a partial differential equation. Can we apply both the time domain and the spatial domain as two continuous sets in the IDAES platform? If it is possible, do you have any example? Thank you.

**Comment by andrewlee94** [comment]
@minhwvu Yes, we can apply a ContinuousSet to both space and time - see the PFR and ControlVolume1D models for examples.

**Comment by minhwvu** [comment]
@andrewlee94 Thank you. I found your answer.
