### ISSUE TITLE
Interest in updated USD_YYYY additions to the units library

### ISSUE THREAD

**Issue by hunterbarber** [IDAES/idaes-pse#1408]
Is there any potential to update the available units to have more recent USD values than USD_2021? I have desire to use a more recent value of the USD for WaterTAP and figured I could just convert based on an estimate, but I'm asking here to see if any updated USD values may be added to the basic unit container in IDAES to ensure consistency of where those CEPCIs came from.

**Comment by andrewlee94** [comment]
Feel free to open a PR.

**Comment by hunterbarber** [comment]
@andrewlee94 I know the organizations that publish cost indices sometimes limit access. So I opened an issue opposed to a PR more wondering if someone on the team both knew which previous cost index was used to supply up to USD_2021, and also still had the ability to access and release those cost index values.

**Comment by andrewlee94** [comment]
I am not sure exactly where the values came from or who got them. The costing team might know more @bpaul4 @AlexNoring

**Comment by bpaul4** [comment]
Hello @hunterbarber, thank you for opening this issue. The cost index values listed in [costing_base ](https://github.com/IDAES/idaes-pse/blob/main/idaes/core/base/costing_base.py) were originally sourced from https://www.toweringskills.com/financial-analysis/cost-indices/. Feel free to open of pull request to update or add entries. For example, I see the source now contains 2022 which we don't have yet in our list of supported cost years.

Alternatively, you may add custom units to just your flowsheet by registering new currency units. See our [power plant costing module](https://github.com/IDAES/idaes-pse/blob/97d2f053a7895cd1cfacca328d264ca1c2be324c/idaes/models_extra/power_generation/costing/power_plant_capcost.py#L85) lines 85-107 as an example of adding custom currency units. As shown on line 114, calling the method at the start of your code is sufficient to register the units when building your flowsheet.

**Comment by bpaul4** [comment]
Hello @hunterbarber. Please let me know if you have any further questions regarding using your own custom currency units, or if this issue may be closed as completed. Note that we have recently added 2022 to the costing base currency list and very soon will include 2023 as well.

**Comment by hunterbarber** [comment]
Yea @bpaul4, this could've been closed as of #1413. Thanks!
