### ISSUE TITLE
Potential reshuffling for “WaterTAP UI” code

### ISSUE THREAD

**Issue by dangunter** [IDAES/idaes-pse#1416]
Potential reshuffling for “WaterTAP UI” code
Context: this UI lets you configure and run any flowsheet, including sweeps, if it is “wrapped” with the appropriate export of desired input/output values.

API for UI wrappers → IDAES

The UI itself → ?? own repo ??

**Comment by dangunter** [comment]
@lbianchi-lbl is this issue being referenced / used anywhere besides the equally dormant-looking PR? If not I'll close it

**Comment by lbianchi-lbl** [comment]
Not that I know of; I'm OK with closing this.
