### ISSUE TITLE
Crash in state initialization when init_VLE flag is false

### ISSUE THREAD

**Issue by vova292** [IDAES/idaes-pse#1424]
https://github.com/IDAES/idaes-pse/blob/1c337b9902efa356014cb41d0f25c1b8b820f3d5/idaes/models/properties/modular_properties/state_definitions/FTPx.py#L497

In the line linked above, the variable vap_frac does not exist if init_VLE flag is False. The else section is missing.

So when init_VLE is False the code will crash

**Comment by andrewlee94** [comment]
@vova292 Thank you for filing this issue (and #1423) - I've confirmed both of them and have a fix ready for testing and review. Do you happen to have a simple test case that triggers this issue at all?

**Comment by vova292** [comment]
I had created this by using a Feed unit model in a flowsheet. Using the Coolprop property package with multiple components but a single Liquid phase for all the components. The valid phase was also just liquid. 

Unfortunately i dont have that running example at the moment.

**Comment by andrewlee94** [comment]
@vova292 I think I put together an example that will test for this case. PR #1425 will hopefully fix this and your other issue.
