### ISSUE TITLE
Revisit "upadate" in typos list and code

### ISSUE THREAD

**Issue by bpaul4** [IDAES/idaes-pse#1444]
Currently, "upadate" is an exception to the spell checker due to what looks like a temporary fix for DMF examples: https://github.com/search?q=org%3AIDAES%20upadate&type=code

At a convenient time, we should consider correcting "upadate_metadata_model_references" back to "update_metadata_model_references" in the code and examples, and clean up as needed.

**Comment by bpaul4** [comment]
@dangunter what is the status regarding DMF support? If the plan is to continue supporting the tool, I am happy to open a pull request to correct the typo and remove the exception.

For what it's worth, it appears the typo was "corrected" in the two DMF examples https://github.com/IDAES/examples/blob/main/idaes_examples/archive/data_reconciliation/boiler_flowsheet_recon_src.ipynb and https://github.com/IDAES/examples/blob/main/idaes_examples/archive/data_reconciliation/econ_recon_src.ipynb. The notebooks are not currently tested, but most likely would fail since they reference `update_metadata_model_references` not `upadate_metadata_model_references` as currently exists in the code.

**Comment by dangunter** [comment]
The DMF is being removed, so I don't think it is worth correcting this typo

**Comment by lbianchi-lbl** [comment]
Resolved by #1484
