### ISSUE TITLE
Drop support for Python 3.8

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/idaes-pse#1462]
Python 3.8 is related to a growing number of issues, mostly due to support being dropped by dependencies such as NumPy and matplotlib, including:

- #1401
- #1453

**Comment by andrewlee94** [comment]
I don't think this will be a big issue, but I believe Pyomo does not plan on deprecating support for Python 3.8 yet. however, seeing as we are being more restrictive, this really shouldn't cause any issues,
