### ISSUE TITLE
Linking external property databank to IDAES

### ISSUE THREAD

**Issue by TheHuangs** [IDAES/idaes-pse#15]
Is it possible to link external property databank to IDAES, such as the ChemSep open source database? Rahul Jain et al. have implemented this method in OpenModelica. OpenModelica is also equation oriented. please refer to the paper titled 'Implementation of a Property Database and Thermodynamic Calculations in OpenModelica for Chemical Process Simulation' as well as the 'https://github.com/FOSSEE/OMChemSim/'.

Ps. what's the development status of the column model? If you are familiar with the work of https://github.com/FOSSEE/OMChemSim/, could you please tell me what's the advantage of the IDAES platform? Maybe the solver or other perspectives.

**Comment by jghouse88** [comment]
@TheHuangs Currently, we do not support links to external property databanks. It is definitely on the cards but it is hard for us to give an exact timeline on when this will be made available. 

The tray column model should be available in the October release. Please register on our website if you haven't already to be added to our mailing list. One significant advantage in IDAES is the capability to use these in deterministic optimization studies, both operational (NLPs) and conceptual design (MINLPs). As for the solvers, having these in Pyomo allows you to utilize any state of the art solver depending on the problem you are solving.
