### ISSUE TITLE
Handle poorly configured streams when building stream table

### ISSUE THREAD

**Issue by dangunter** [IDAES/idaes-pse#1509]
When the stream table is being built, it is possible (though probably not desirable) that some streams will not have the attribute `define_display_vars` and/or `define_state_vars`. Also it is possible that stream states may not be able to be treated as indexed components. Models can build and even solve with these conditions, so it would be better if the stream table gracefully handled them by simply not displaying information that isn't there.

This is related to the idaes-ui issue https://github.com/IDAES/idaes-ui/issues/54

**Comment by lbianchi-lbl** [comment]
Closing this as we decided that it probably makes more sense for this functionality to fail "noisily" than to try to handle all possible error conditions.
