### ISSUE TITLE
Incorrect method docs for FlowsheetBlock.visualize

### ISSUE THREAD

**Issue by dangunter** [IDAES/idaes-pse#151]
The `visualize` method in idaes.core.flowsheet_model.FlowsheetBlock is wrapping the method in the `idaes.ui.fsvis.fsvis`, but it has diverged in documentation. The ideal fix would ensure that this couldn't happen again by removing the redundancy. Also, the redundancy of ".fsvis.fsvis" could be removed, so e.g. the following would work:
```
from idaes.ui.fsvis import visualize
# ... create a flowsheet, in variable "m.fs"
# the following are equivalent, and call the same exact method:
# (1)
visualize(m.fs, "my flowsheet", save_as="my_flowsheet.json")
# (2)
m.fs.visualize("my flowsheet", save_as="my_flowsheet.json")
```

**Comment by ksbeattie** [comment]
@dangunter another chance to check on this again (before closing it)?
