### ISSUE TITLE
CI failures due to TypeError: cannot inherit frozen dataclass from a non-frozen one

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/idaes-pse#1524]
- Something within the past few hours must have happened causing the CI to fail:
  ![image](https://github.com/user-attachments/assets/6e7d25f8-b0b9-4364-bb51-89dd1ed48e24)
- This points towards the cause being a dependency being updated (as opposed to a change in the code, since there were no commits merged between the passing and failing CI workflow runs below):
  ![image](https://github.com/user-attachments/assets/7a60c1d6-c33b-40ea-9010-0a7e64b590bf)
- However, at first sight, none of the packages involved in the stack trace have been updated in that timeframe:
  - Pyomo 6.8.1a0 (released a few weeks ago)
  - Pint 0.24.3 (released July 2024)
  - `dataclasses` is part of the Python standard library, so unlikely to have been changed in a backward-incompatible way within the same Python version

## Related

We're aware of this error affecting the following PRs

- IDAES/idaes-pse#1523
- watertap-org/watertap#1520

**Comment by lbianchi-lbl** [comment]
From comparing `pip list` between the passing (LHS) and failing (RHS) runs, there are two differences:
![image](https://github.com/user-attachments/assets/cd25aba8-a12d-4aaa-9ee9-757356b7f37e)
![image](https://github.com/user-attachments/assets/3da7f3d4-8015-4fb5-909b-1f418ecc174b)

**Comment by lbianchi-lbl** [comment]
It looks like flexparser is the likely culprit, see https://github.com/hgrecco/pint/issues/2074

**Comment by blnicho** [comment]
@lbianchi-lbl the issue is the latest `flexparser` not being compatible with `pint`. See the discussion here: https://github.com/hgrecco/pint/issues/1969

I've temporarily pinned `flexparser` in #1523

**Comment by blnicho** [comment]
New `pint` release is out: https://github.com/hgrecco/pint/releases/tag/0.24.4

**Comment by lbianchi-lbl** [comment]
> New `pint` release is out: https://github.com/hgrecco/pint/releases/tag/0.24.4

This has been fixed upstream, so I'm closing this issue.
