### ISSUE TITLE
Issues with developer installation with "Failed to build jupyter_contrib_nbextensions" error

### ISSUE THREAD

**Issue by andrewlee94** [IDAES/idaes-pse#1529]
_(Note from @lbianchi-lbl: I've amended the title following confirmation that the error described in https://github.com/IDAES/idaes-pse/issues/1529#issuecomment-2468996187 also applies to @andrewlee94's original reporting of the issue)_

I did a new developer installation of IDAES today on Windows and found a few things that were missing from the installation instructions:

1. Instructions appear to skip the step of actually installing IDAES. They go from setting up and activating the conda environment to `pip install -r requirements-dev.txt` which only installs the developer dependencies. When you then try to run `idaes get-extension` you get an error as IDAES has not been installed yet.
2. `pip install -r requirements-dev.txt` installed a new version of Pyomo even though I had a fresh clone of Pyomo already installed. There is a note about this, but it comes after the instruction to run this command.
3. Pytest was not installed on my machine by default for some reason, so I had to install it separately through conda (after receiving an error when trying to run it the first time).

**Comment by lbianchi-lbl** [comment]
@andrewlee94 did this happen using a Conda environment? While it's possible to install IDAES without Conda, it's definitely an uphill battle, especially on Windows.

**Comment by andrewlee94** [comment]
It was not in a conda environment, although I did install Miniconda first.

**Comment by dallan-keylogic** [comment]
Recall that you should be using Miniforge now. Also, the Pyomo thing is a known issue, and the last time we discussed it the easiest way was just to install from requirements-dev then uninstall that version of Pyomo and reinstall from sources.

As for `idaes get-extensions`, I haven't had any issues with the developer installation instructions. I can just install from `requirements-dev.txt` then run it.

**Comment by lbianchi-lbl** [comment]
> Actually, I just tried running through things in Windows Sandbox and had issues, so @andrewlee94 is probably on to something (as was likely from the beginning).
> 
> `pip install requirements-dev.txt` failed with the error
> 
> ```
> Failed to build jupyter_contrib_nbextensions
> ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (jupyter_contrib_nbextensions)
> ```
> 
> and I was unable to run `idaes get-extensions`.

@andrewlee94: @dallan-keylogic and I are trying to debug this issue, but I haven't been able to reproduce it yet on the Windows machine I'm using for testing. Can you check if the same error message was shown when you ran the `pip install -r requirements-dev.txt`?

**Comment by andrewlee94** [comment]
@lbianchi-lbl I did get the same error as Doug but mostly ignored and forgot it as I figured I didn't care too much about notebooks. I did not stop to think it might have been a terminal error that stopped the installation before it finished/

**Comment by lbianchi-lbl** [comment]
OK, thanks for confirming, it looks like is a genuine issue and I was wrong for summarily chucking it into the "Windows is weird, just use Conda" bin, sorry about that.

If you don't mind, I'll edit the title so that it's more descriptive now that we have a better sense of what's happening.

**Comment by dallan-keylogic** [comment]
@andrewlee94  If you comment out `jupyter_contrib_nbextensions` in `requirements-dev.txt`, the installation works fine. It's unclear why that suddenly broke at the moment.
