### ISSUE TITLE
Docs: point out the preferred method of designating inlets/outlets...

### ISSUE THREAD

**Issue by perrenyang** [IDAES/idaes-pse#153]
... and the impact of said designation (namely, at the moment, affecting their display in the visualizer).

This is a follow-up to IDAES/idaes-dev#1107 (which attempts to display Feed and Product blocks when inlet/outlet ports are given appropriate variable names). Discussions revealed that the preferred way to designate inlets and outlets is by using Feed and Product (UnitModelBlockData?) blocks; this should be noted in the documentation. The PR _attempts_ to still display them when blocks are not used, but is more of a stopgap measure.

Current plans include making a note of this situation+preference within the Visualization docs, and crosslinking to one or more of:

- User Guide/Conventions
- User Guide/Unit Model
- Adv. User Guide/Developer Standards
- Any of their associated subpages

**Comment by dangunter** [comment]
I think this is resolved since we can see connections on flowsheets now
