### ISSUE TITLE
Windows installation fails with error: could not create 'build\bdist.win-amd64\wheel\.\idaes\core\surrogate\tests\data\onnx_models\net_st_net_5000_STM_100_s_2000000_60_5_tanh_1e-06 _4096_tr_15481_Calcite_ST_idaes_info.json': No such file or directory

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/idaes-pse#1540]
- Originally reported by @MarcusHolly, @hunterbarber, and @OOAmusat
- As suggested by @adam-a-a, the file mentioned in the error was added in #1308
- I was able to reproduce this locally on a Windows VM using:
  ```sh
  conda create --yes -n test-idaes-install-error python=3.11
  conda activate test-idaes-install-error
  pip install "idaes-pse @ git+https://github.com/IDAES/idaes-pse@main"
  ```
- My current best guess is that this is due to file path length limitations on Windows
  - See also e.g. https://scikit-learn.org/stable/install.html#error-caused-by-file-path-length-limit-on-windows
- The reason why this issue doesn't show up in CI (and indeed might be impossible to reproduce on GitHub Actions runners) is that the file path length limit is disabled on the Windows version used in GHA: https://github.com/actions/runner-images/issues/1052

**Comment by lbianchi-lbl** [comment]
I was able to confirm that this is indeed caused by file path length limitations:

1. In a Powershell prompt, run the following "cmdlet"  to check whether long paths are supported or not (`0`: long paths not supported; `1`:  long paths supported):
  ```pwsh
  Get-ItemProperty -Path "HKLM:System\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled"
  ```
2. Run the `pip install` command above (it should fail if `LongPathsEnabled` is 0)
3. Open a Powershell prompt with "Run as Administrator" to enable support for long paths:
  ```pwsh
  Set-ItemProperty -Path "HKLM:System\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1
  ```
4. Run the `pip install` command above, which should now pass

For more information: https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later

**Comment by lbianchi-lbl** [comment]
From more testing, I think I figured out the exact path that causes the error, at 262 characters when the default length without `LongPathsEnabled` is 260:

```
C:\Users\lbian\AppData\Local\Temp\pip-install-is8sb24x\idaes-pse_f27d74dd25594348bdef5015371f125f\build\bdist.win-amd64\wheel\.\idaes\core\surrogate\tests\data\onnx_models\net_st_net_5000_STM_100_s_2000000_60_5_tanh_1e-06_4096_tr_15481_Calcite_ST_idaes_info.json
```

Assuming this is true, and that the pattern for name mangling that `pip` uses is fixed in length, then the filename just happens to be long enough to go over the threshold by 2 characters :upside_down_face:

**Comment by fahim831** [comment]
When I tried the above solution, i.e.,
`Set-ItemProperty -Path "HKLM:System\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1`
on a Windows virtual machine via Citrix, I get this error:

```
Set-ItemProperty : Requested registry access is not allowed.
At line:1 char:1
+ Set-ItemProperty -Path "HKLM:System\CurrentControlSet\Control\FileSys ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (HKEY_LOCAL_MACH...trol\FileSystem:String) [Set-ItemProperty], Securit
   yException
    + FullyQualifiedErrorId : System.Security.SecurityException,Microsoft.PowerShell.Commands.SetItemPropertyCommand
```

**Comment by lbianchi-lbl** [comment]
> When I tried the above solution, i.e., `Set-ItemProperty -Path "HKLM:System\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1` on a Windows virtual machine via Citrix, I get this error:
> 
> ```
> Set-ItemProperty : Requested registry access is not allowed.
> At line:1 char:1
> + Set-ItemProperty -Path "HKLM:System\CurrentControlSet\Control\FileSys ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : PermissionDenied: (HKEY_LOCAL_MACH...trol\FileSystem:String) [Set-ItemProperty], Securit
>    yException
>     + FullyQualifiedErrorId : System.Security.SecurityException,Microsoft.PowerShell.Commands.SetItemPropertyCommand
> ```

Thanks for the feedback @fahim831. As I mentioned in my comment above, this commands needs to be run as administrator (which, depending on how your machine is configured, might not be possible to ordinary users).

Also, #1545 should have resolved this error, so commands such as `pip install "idaes-pse @ git+https://github.com/IDAES/idaes-pse@main` should work as expected now.

**Comment by fahim831** [comment]
@lbianchi-lbl Thank you! I did run it with Admin privileges, which is why I was confused it didn't work. But the #1545 solution worked, using pip install git+ for both idaes and then watertap.
