### ISSUE TITLE
message from solver=Too few degrees of freedom (rethrown)!

### ISSUE THREAD

**Issue by vinayvm** [IDAES/idaes-pse#16]
Hi,

I get this when I try the Dynamic flowsheet tutorial. Is this the issue of Pyomo or Ipopt? Can't see where the problem is. 

Thanks.

[Tutorial_3_Dynamic_Flowsheets.ipynb.zip](https://github.com/IDAES/idaes-pse/files/3541794/Tutorial_3_Dynamic_Flowsheets.ipynb.zip)

**Comment by vinayvm** [comment]
Hi,

"you have either fixed too many variables" Indeed that was the case. Had accidently fixed volume. 

Thanks.

**Comment by dangunter** [comment]
Looks like this is resolved. Closing.
