### ISSUE TITLE
Generic property packages are not copyable

### ISSUE THREAD

**Issue by jsiirola** [IDAES/idaes-pse#166]
We (@MAZamarripa) recently hit a snag where a model using the generic Cubic EOS was not compatible with GDPOpt because the model was not cleanly clonable.  We tracked it down to the property parameter data definitions, specifically the definitions of:
```python
{ #...
"enth_mol_ig_comp": NIST,
}
```

The problem is that `NIST` is a module, and therefore not deepcopyable.  Talking to @andrewlee94 we think we can create a static class (`NIST`) that should resolve the issue:
```python
class cp_mol_ig_comp():
    @staticmethod
    def build_parameters(cobj):
        # ...

    @staticmethod
    def return_expression(b, cobj, T):
        # ...


class enth_mol_ig_comp():
    @staticmethod
    def build_parameters(cobj):
        # ...

    @staticmethod
    def return_expression(b, cobj, T):
        # ...


class entr_mol_ig_comp():
    @staticmethod
    def build_parameters(cobj):
        # ...

    @staticmethod
    def return_expression(b, cobj, T):
        # ...

class pressure_sat_comp():
    @staticmethod
    def build_parameters(cobj):
        # ...

    @staticmethod
    def return_expression(b, cobj, T, dT=False):
        # ...

    @staticmethod
    def dT_expression(b, cobj, T):
        # ...

class NIST(object):
    cp_mol_ig_comp = cp_mol_ig_comp
    enth_mol_ig_comp = enth_mol_ig_comp
    entr_mol_ig_comp = entr_mol_ig_comp
    pressure_sat_comp = pressure_sat_comp
```
The challenge is that this would need to be propagated to all the property packages.

**Comment by andrewlee94** [comment]
As part of tracking this down, it was also pointed out that the example code in the docs does not include the imports to show where to find the library modules for the user.

**Comment by adowling2** [comment]
@agarciadiego FYI
