### ISSUE TITLE
Ipopt Scaling Option

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-pse#169]
When you use the IDAES scaling tools and Ipopt, you should pretty much always use the "user-scaling" option.  I'm not sure what the best way to make people are aware of this is.  Maybe it would be a good idea to somehow make user-scaling the IDAES default?

Another issue with user-scaling is that if it is not the default, we have a lot of the solver objects created for initialization, and those should also use user-scaling.  For myself, when I want to make sure every solve uses user scaling, I still monkey-patching the Ipopt solver class, which works, but probably isn't good.

**Comment by carldlaird** [comment]
@eslickj Sorry, John, I don't understand the issue. Is the problem that you want to use user-scaling for the variables, but then use IPOPT's automatic scaling for the constraints?

**Comment by eslickj** [comment]
No just use normal use user scaling.  Everyone should, but nobody knows it.  I'm suggesting we just somehow make user scaling the default.  I'll edit the issue to make it more clear.

**Comment by carldlaird** [comment]
@eslickj Ah, I understand. Does IDAES have a set of "wrapper" classes for the solvers / solver factory?
@jsiirola Should we consider an approach to change the defaults for specific solvers? Or maybe allow "new" solvers (e.g., "ipopt-idaes" that could essentially be a wrapper with different defaults / reporting?

**Comment by eslickj** [comment]
@carldlaird, I like those ideas.  I'm not totally sure how it works, but maybe I could create as you say an "ipopt-idaes" solver class that inherits the ipopt one, and just have some default solver options that make sense for IDAES, maybe just user scaling.  It seems pretty straight forward, but there is probably a reason I haven't done it already. Then we could slowly migrate everything over to the new solver class.  If we go to user scaling by default, and no one uses the scaling framework, a lot of stuff will break.  Getting everyone on board and everything updated is a little delicate.

**Comment by eslickj** [comment]
Ok PR #180 implements @carldlaird's suggestion.  It also lets you configure other solver options, so later we can adjust other things if needed.  You just need to ```import idaes.core.plugins``` then the "ipopt-solver" is available and the default solver options are part of the idaes configuration.

**Comment by eslickj** [comment]
Changed the approach here now PR #207 maybe?
