### ISSUE TITLE
Revisit functionality to enforce all tests to be categorized with a pytest.mark

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/idaes-pse#170]
See also IDAES/idaes-dev#1038.

Adding @dangunter and @andrewlee94 as "persons of interest".

**Comment by dangunter** [comment]
@lbianchi-lbl where is this now? Do you think it is possible to re-use some of the pytest collection machinery to find all the tests and then introspect to see what mark they have?

**Comment by lbianchi-lbl** [comment]
@dangunter I've tried something quick and it seems to be working. I should have a PR up in the next few days.
