### ISSUE TITLE
Offset units in pyomo

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-pse#173]
@MAZamarripa and I found that supplying a temperature unit of degF or degC to the temperature arg of the htpx() function in IAPWS leads to an error like offset units not supported.  I use a convert() to convert the temperature units to K, but this is just an evaluation, and I don't need to keep a Pyomo expression around for the conversion (just converting the number is fine).  I could probably do something to handle the temperature conversion in my own function, but there is probably a better way.

Is there a good way to handle this?  Is it going to be an issue other places in IDAES?  I can imagine like delta T in heat exchangers could have this issue if one property package is in K and one is in degC.

**Comment by andrewlee94** [comment]
@carldlaird can give a more detailed answer, but dealing with relative units is extremely difficult (if not impossible). Sort answer is that Pyomo (and by extension IDAES) does not support the use of relative measurement in models.

There are special functions for converting degC to K, but those are only for input/output use - you have to use absolute units in the actual calculations.

**Comment by eslickj** [comment]
@andrewlee94 thanks.  I can use the special purpose converts for my particular problem with htpx.  I'm still a bit worried about the convert in the heat exchanger.  I've never really known anyone to use Rankine so it seems like it won't do much but raise an exception if you have two property packages with different temperature units.

**Comment by eslickj** [comment]
Okay, I think we can close this, but just to confirm.  For models like the heat exchange that use convert on a temperature in their constraints, the convert likely won't do any converting, but it will raise an exception about offset units being unsupported if you use a property package in F or C.  That may be a fine result.  We just have to document that if you use two different property packages for the sides of the heat exchange, they either need to have the same temperature units or absolute temperature units.  I guess this path would be catch the exception and produce an specific informative one.

I guess an alternative option is to use an expression for temperature in the model where we check the property packages and write the appropriate temperature expression for one of the sides if the property package of the two sides is not the same.  Something like, say one side is C and the other is F, both sides in C would be fine.

```
if side_1.temperature.unit != side_1.temperature.unit:
    if side_1.teperature unit is "C":
        if side_2.temperature unit is "F":
             side_2.temperature_expressions = Expressions(expr=
                 (remove_unit(side_2.temperature) + 32)*5/9*units.K)
....

```

It a bit ugly, but from a user perspective it's easier, since any temperature will be fine.  I can make either update easy enough.

**Comment by andrewlee94** [comment]
I personally think it is best as it is for two reasons:

1. IDAES And Pyomo do not support relative units in expressions in any form, so there should be no case of property packages using Celsius or Fahrenheit.
2. Having the `convert` method will catch any (admittedly rare) cases where a modeler uses something like Rankine in one of their property packages. This way, we allow for any combination of absolute temperature units that might arise in the future.

**Comment by eslickj** [comment]
Maybe I failed to comment on this earlier, but @andrewlee94 sounds good.  I catch the offset units exception in the heat exchanger and raise a clear expatiation sometime soon.  Otherwise the consensus seems to be that it's goo how it is.  I'll go ahead and close this, but we may want to add a bit about avoiding C and F to the property package guidelines if it's not there already.
