### ISSUE TITLE
Convergence evaluation feature requests

### ISSUE THREAD

**Issue by carldlaird** [IDAES/idaes-pse#176]
The Convergence evaluation code will be pushed soon. This issue is here to collect some feature requests for the tool.

To-do:
- [x] Modify the command line tool to support calling a single sample point. This would be useful for testing failed cases - will need to turn off the code that captures output so it is shown. 
- [ ] Add another callback between get_initialized_model and the solve. This would allow the test writer to have some special code that ensures the model is consistent. One good example given was compositions. One could specify the N-1 compositions and then compute the Nth in this method (or normalize) before calling solve. 
- [x] allow statistics output in json format (for archive and analysis) 
- [x] replace printing with IDAES logging
- [x] get the command-line interface (convergence.py) correctly installed with setup.py
- [x] make sure the pytests are being picked up by the main testing harness
- [x] test with different versions of Python (only tested on 3.6 now)
- [x] add tests for the CLI that pass arguments to the arg parser.

Related issues:

**Comment by eslickj** [comment]
@carldlaird, I think I knocked off most of these.  Can you explain the unchecked item about a callback?  I can probably take care of that.
