### ISSUE TITLE
Units problem with drum.py model when updating to Pyomo master

### ISSUE THREAD

**Issue by jghouse88** [IDAES/idaes-pse#189]
@jsiirola and I are testing idaes tests with the Pyomo master before we bump the IDAES Pyomo version. We encountered the following error with the test_drum.py in the power generation unit model library. 

> Units problem with expression fs.unit.control_volume.volume[0.0] - (((asin((fs.unit.drum_level[0.0] - (0.5*fs.unit.drum_diameter))/(0.5*fs.unit.drum_diameter))) + 1.5707963267948966*rad)*(0.5*fs.unit.drum_diameter)**2 + (0.5*fs.unit.drum_diameter)*cos(asin((fs.unit.drum_level[0.0] - (0.5*fs.unit.drum_diameter))/(0.5*fs.unit.drum_diameter)))*(fs.unit.drum_level[0.0] - (0.5*fs.unit.drum_diameter)))*fs.unit.drum_length
> Error in units when checking fs.unit.volume_eqn[0.0]
> Error in units when checking fs.unit
> Error in units when checking fs
> Error in units when checking unknown
> ================================================================================================================================= slowest 100 durations =================================================================================================================================
> 0.83s call     idaes/power_generation/unit_models/tests/test_drum.py::test_units
> 0.20s call     idaes/power_generation/unit_models/tests/test_drum.py::test_initialize_drum
> 0.10s setup    idaes/power_generation/unit_models/tests/test_drum.py::test_basic_build
> 0.09s call     idaes/power_generation/unit_models/tests/test_drum.py::test_run_drum
> 
> (8 durations < 0.005s hidden.  Use -vv to show these durations.)
> ================================================================================================================================ short test summary info ================================================================================================================================
> FAILED test_drum.py::test_units - pyomo.core.base.units_container.InconsistentUnitsError: Error in units found in expression: ((asin((fs.unit.drum_level[0.0] - (0.5*fs.unit.drum_diameter))/(0.5*fs.unit.drum_diameter))) + 1.5707963267948966*rad)*(0.5*fs.unit.drum_diameter)**2 + (...

To reproduce this error, you will need the following:
1. Current Pyomo master
2. `units-updates` from @jsiirola's idaes fork: https://github.com/jsiirola/idaes-pse/tree/units-updates  

Once fixed, I think it is best to push changes back to @jsiirola's branch and we can create a PR from there.

**Comment by eslickj** [comment]
Here is the answer, make this change in the drum.

```
        def alpha_drum(b, t):
            return asin((b.drum_level[t]-b.drum_radius)/b.drum_radius)/pyo.units.rad
```

**Comment by eslickj** [comment]
Made PR on @jsiirola's fork

**Comment by jsiirola** [comment]
I realize that that passes units verification, but I suppose that I am a bit confused: `alpha_drum` is an angle, so shouldn't it have units?

**Comment by andrewlee94** [comment]
@jsiirola Units are rather slip-shod in the detailed powerplant models, so `alpha_drum` is probably marked as unitless (or probably doesn't even have units assigned).

**Comment by eslickj** [comment]
I'm a bit unclear on the formula here.  I didn't write it, but I think what's happening is that the area of part of a circle.  In some of the formulas for sector area and arc length radian act dimensionless.  You could make this work by taking the radians out somewhere else.  Whatever you like.
