### ISSUE TITLE
support of Mac OS

### ISSUE THREAD

**Issue by TheHuangs** [IDAES/idaes-pse#19]
I find that Mac OS is Not supported by ideas. is it possible to let it be supported.

**Comment by ksbeattie** [comment]
@TheHuangs, the update to the main readme file to be more clear about the Mac OS support will be pushed out later today.

In general the instructions for OS X is the same as for Lunix.  Start with the [Minimal install with IPOPT/MUMPS for Mac/OSX](https://idaes-pse.readthedocs.io/en/latest/install/minimal.html#minimal-install-with-ipopt-mumps-for-mac-osx) section of the docs.

Unfortunately, OS X is not a primary platform for us.  Most of the developers work on Linux systems during development.  If you come across problems on OS X, please let us know and we'll do our best to addresses them.
