### ISSUE TITLE
Solver Swap (ipopt -> ipopt-idaes)

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-pse#194]
We need to swap every solver object in all of IDAES from "ipopt" to "ipopt-idaes".  The change over won't hurt anything (by default they are the same thing), and I can do it myself with a find-and-replace.  The problem is it will touch a whole lot of files, so I figured it's probably a good idea to coordinate.

In case you haven't been keeping up, the difference is just that "ipopt-idaes" takes default solver options from the IDAES config system.  This means that if you want to change the solver settings for everything, you don't have to track down every solver object for all the initializations or sub-problems or whatever and set the solver options.  The main motivation was originally to set everything to "nlp_scaling_method" = "user-scaling" with one line, to switch to using scaling factors supplied by IDAES, but there are a lot of uses.

**Comment by andrewlee94** [comment]
@eslickj As part of this, we should consider the use of the `get_default_solver` method in the core utility methods. For one, I think we should standardize on whether we use this method or not - either use it for (almost) everything, or do away with it entirely.

I think a lot of the tests are written to use this method as it is, which would mean we could hopefully cover a lot o the code by just updating the `get_default_solver` method (if we go that route). That might mean there are far fewer instances of a stand-alone solver that needs to be changed than expected.

Also, we don't necessarily need to do all the changes in one PR - we could consider breaking it up to keep the PR reviews more manageable (not that the changes will be particularly large in any one file though).

**Comment by eslickj** [comment]
@andrewlee94, that's a good question.  It also brings up another thing that is a bit of a hole in this for testing.  What if someone has a custom config file with solver settings that break tests?  

I guess the safest thing to do is figure out how to get tests to ignore configuration files and use the default.  Then still keep ```get_default_solver()``` and use "ipopt-idaes".  It's possible we add the solver options from ```get_default_solver()``` to our standard solver defaults, but that would change things, and we probably don't want to sneak that in on people.

**Comment by andrewlee94** [comment]
@eslickj I am less concerned about users with custom configuration files breaking the tests - I am not sure how many users even run the tests themselves (except for maybe on a new install). We can't protect the user from all possible issues that could arise. In a similar vein, we now assume users will have access to the HSL libraries as part of our tests, even though it is technically an optional download.

The initial purpose of the `get_default_solver` method was in part to give us a way to set a standard set of options to use during testing to avoid such issues. However, the use of config files is probably a better overall approach, and that is what prompted me to ask whether it is required anymore. It does have the advantage of making changes like this easier in future however (even if the method doesn't actually do much).

**Comment by eslickj** [comment]
@andrewlee94, do you think it makes sense to add the "linear_solver" = ma27 and the "tol" = 1e6 options to the defaults settings?  At first I was thinking it could cause trouble, and there is an outside chance it may, but I guess users doing their own thing would probably be using the standard "ipopt" solver, so I guess it may be safer than I was originally thinking.  I would let us deprecate get_default_solver and give us possibly better solver defaults.

**Comment by andrewlee94** [comment]
@eslickj If we are setting default solver settings in a configuration file, then I think it makes perfect sense to add the linear solver and tolerance there as well. In fact, I would say it makes more sense to keep these in a single, central location than to have them dispersed throughout the code as it makes future changes easier, and helps ensure standardisation of the tests. If a user requires something else then they are free to change these as required.

**Comment by eslickj** [comment]
@andrewlee94, you're definitely right about centralizing.  I'll try adding those options into the defaults in the first batch of changes we make to switch over.  I guess I should have pointed out too in case it wasn't clear that the central configuration for the solver is just the default.  Once you create a solver object, you can configure it just like normal.

**Comment by Robbybp** [comment]
Why do solver objects in the tests (or anywhere, really) _need_ to be changed? I was under the impression that this was an enhancement for people who want to easily toggle solver options for an entire workflow, and would be recommended for future use, but that it wouldn't be necessary to change existing solver objects.

**Comment by eslickj** [comment]
@Robbybp, sorry I didn't clearly explain.  The new ipopt-ideas class is the same as the regular Pyomo ipopt class we usually use, except that it reads a set of default options from the IDAES config.  It's not strictly necessary to to switch over to the new class.  We should at least change over the initialization solver classes though, since they are hidden from the user and in a complicated flowsheet there are a lot of them, those are the ones I'm most interested in switching out.  That way I can configure them all centrally.  As for the rest of the solvers, I was thinking it would just be good standard practice to use the ipopt-idaes.  It doesn't really change anything, it just adds the ability to change all the solver settings in one central place.

**Comment by eslickj** [comment]
I think, I'll change the approach and go with a solver factory wrapper instead of a solver class wrapper.  That makes this a nonissue.  Once we get the details worked out, I'll open a new issue to switch over to the IDAES version of SolverFactory (probably).
