### ISSUE TITLE
setup.py file error while installing mac os

### ISSUE THREAD

**Issue by anezkap** [IDAES/idaes-pse#20]
Hi!

I followed the Minimal installation for IPOPT/MUMPS (https://idaes-pse.readthedocs.io/en/stable/install/minimal.html#min-install-osx) and I got to the step 6 without problem. But when I run the setup.py file (python setup.py develop) I got 

File "setup.py", line 162
    print(f"alamopy dir: {alamopy_dir}")
                                      ^
SyntaxError: invalid syntax

Can I ignore it and continue to the next step or should I do something about it? 
Thank you

**Comment by anezkap** [comment]
Thanks for the reply. It's Python 2.7.10.

**Comment by anezkap** [comment]
I have Python 3.7.0 installed as well, I just did not realise that my computer will use 2.7.10 as default when I type "python setup.py develop". When I use "python3 setup.py develop", it works fine.

But then another problem arises - when I try "pytest idaes/unit_models" I get "29 failed, 255 passed, 85 skipped, 51 error in 127.48s (0:02:07)".

**Comment by andrewlee94** [comment]
Hi @anezkap, can you give us the output from pytest so we can see which tests are failing and why?

**Comment by ksbeattie** [comment]
> I have Python 3.7.0 installed as well, I just did not realise that my computer will use 2.7.10 as default when I type "python setup.py develop". When I use "python3 setup.py develop", it works fine.

We somewhat skip over it in the docs, but it might be better for you to use a conda environment with the default there being python3.

**Comment by ksbeattie** [comment]
@anezkap, could you try again with the new 1.4.0 release?  We now have a PyPi package so you can `pip install` to make the install easier.
