### ISSUE TITLE
ASL install has errors

### ISSUE THREAD

**Issue by milesabarr** [IDAES/idaes-pse#21]
When I follow the instruction for a full Windows install of IDAES [here](https://idaes-pse.readthedocs.io/en/latest/install/windows-full.html#full-install-windows), I get errors when installing ASL. 

When I run this code:

```
wget https://ampl.com/netlib/ampl/solvers.tgz
tar -zxvf solvers.tgz
cd solvers
./configure
make
```

I get the following error after the final line of code (make):
```
$ make
cd ${OBJDIR=sys.`uname -m`.`uname -s`}; make
make[1]: Entering directory '/c/Users/miles/src/solvers/sys.x86_64.MSYS_NT-10.0-17763'
gcc -c -O -DNO_RUSAGE -DASL_NO_FPINITMT fpinit.c
make[1]: gcc: Command not found
make[1]: *** [makefile:234: arith.h] Error 127
make[1]: Leaving directory '/c/Users/miles/src/solvers/sys.x86_64.MSYS_NT-10.0-17763'
make: *** [makefile:2: amplsolver] Error 2
```

Also, I thought I should note that I noticed a few other errors in the installation documentation. 
- You don't seem to mention the need to install wget
- After creating the src folder with MSYS2 you cannot simply type cd src to get to that folder. You instead need to put in the full path.
- when I forked IDAES from GitHub, the cloned directory is named idaes-pse rather than idaes_pse as referenced in the documentation.

A couple of these errors are extremely minor, but figured you may want to edit them.

**Comment by eslickj** [comment]
We're switching to per-compiled binaries with the November release.  No one should need to do these steps anymore.
