### ISSUE TITLE
Error in NIST enthalpy equation

### ISSUE THREAD

**Issue by AlexNoring** [IDAES/idaes-pse#220]
The equation for enthalpy in idaes.generic_models.properties.core.pure.NIST is not consistent with [the equation posted](https://webbook.nist.gov/cgi/cbook.cgi?ID=C1333740&Units=SI&Mask=1#Thermo-Gas) at NIST webbook. The reference temperatures need to be removed.

**Comment by andrewlee94** [comment]
PR #291 contains a temporary workaround for this issue which will need to be removed once this issue is fixed.

**Comment by jghouse88** [comment]
@anujad95  May be relevant for you as well.

**Comment by adowling2** [comment]
@agarciadiego Any thoughts?

**Comment by andrewlee94** [comment]
@agarciadiego I have been working on fixing this and have most of it up and running now, however there is one test hat is still failing. It is `test_temp_swing` in `test_CO2_H2O_Ideal_VLE.py` and I wanted to check to see if the expected heat duty data was  verification data from an external source, or was just a compiled list of results you got from running the model - i.e. should I be concerned that these values have changed.

**Comment by agarciadiego** [comment]
@andrewlee94 I didn't create the 'CO2_H2O_Ideal_VLE.py' file. I haven't used the equation for enthalpy in idaes.generic_models.properties.core.pure.NIST for my examples as I could not find all the parameters for all the species I needed, so I used different versions of RPP and Perry.

**Comment by andrewlee94** [comment]
@anujad95 It appears the failing test is one of yours - do you know where the heat duty numbers came from in `test_temp_swing` in `test_CO2_H2O_Ideal_VLE.py`? The values changed after I corrected the NIST correlation, so I want to know if these values are from an external source or not (i.e. whether I should be concerned that the value changed or not).

**Comment by anujad95** [comment]
@andrewlee94 The heat duty values are based on CO2_H2O_Ideal_VLE.py itself. I need to check if the coefficient 'H' in the configuration dictionary needs to be modified according to your corrections in the NIST correlation.

**Comment by andrewlee94** [comment]
Fixed in #223.
