### ISSUE TITLE
IDAES-EXT Testing

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-pse#224]
I'm not totally sure which repo this belongs in, but I have tests for IDAES-EXT that are basically to run the IDAES-PSE tests, but instead of using the the current binary release, use the testing release.  I just run these tests when I build new binaries.  I got to thinking it would be a lot better if I could just somehow piggy back in the IDAES-PSE test setup and run the tests here when I want to test a new binary release.  I would just need to change the get-extensions like to pull the testing binary release.  Maybe setup binary test actions that we could manually trigger that somehow pass an argument to the existing test actions that pull the binaries from a different location?

Does anyone have ideas about how best to do that?  It's not really my area of expertise.

**Comment by eslickj** [comment]
I guess the part of this I forgot was that I test the binaries on several Linux platforms using docker containers, so it may not be quite as easy as I was first thinking.  It still seems like we may want to integrate the testing of both repos as much as possible seeing as they run the same tests.

**Comment by lbianchi-lbl** [comment]
@ksbeattie and I will have to look into this in more detail, but this looks reasonable. In my opinion the Docker approach is a good one, and we should be able to keep it without too many complications, as GitHub Actions supports using Docker images (both from a registry and a Dockerfile) as the base of the running environment (in addition to the ready-made Linux environments based on Ubuntu LTS).

**Comment by eslickj** [comment]
If we make a little progress on this is may resolve issue #108 or we may need to revisit that issue in the process.
