### ISSUE TITLE
Pip install requirments issue

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-pse#23]
External user email issue:

We wiped the computer clean and reinstalled Ubuntu and Anaconda and all that seemed to work well. However when we executed “pip install ideas-pse” command we received an error “Building wheel for psutil (setup.py)” ……”Failed building wheel for psutil”. Then “Running setup.py clean for psutil error”. So the idaes software installation is not completed.

The python version is 3.7.

On occasion it seems that pip tries to compile some required packages.  This isn't necessarily an IDAES problem, but we should try to identify what causes pip to try to compile a package and improve documentation to avoid it.

**Comment by andrewlee94** [comment]
I am assuming this was fixed in Pr 730 in the dev repo.
