### ISSUE TITLE
Trace file issue when running ALAMO

### ISSUE THREAD

**Issue by 4dsoftware** [IDAES/idaes-pse#24]
I got the following error: AlamoError: Cannot read from trace file "trace.trc": [Errno 2] No such file or directory: 'trace.trc', after running alamopy.alamo(xdata = data,zdata = label). Here my data is a DataFrame, and label is an array. I tried converting data to an array, and label to Series, but it didn't work either. Would you please let me know where to find that "trace.trc" file?

**Comment by niksah** [comment]
Please provide a python file that we can use to reproduce this issue.

**Comment by niksah** [comment]
Please provide a python file that demonstrates this issue so that we can reproduce it and look into it.

**Comment by 4dsoftware** [comment]
Hello,

Thank you for your prompt response. I don't think GitHub allows uploading csv files, so I will detail the description. My data is a 300*6 dataframe with all NAN filled with 0, so it is purely numeric. My label is a 300*1 numpy array. After loading the data and label, I ran the following simple code:

from idaes.surrogate import alamopy
alamopy.alamo(xdata = data,zdata = label)

I got the following error:

Traceback (most recent call last):

  File "<ipython-input-105-e73f7694f971>", line 1, in <module>
    alamopy.alamo(xdata = aa,zdata = label)

  File "C:\Users\sds\Anaconda3\lib\site-packages\idaes\surrogate\alamopy\doalamo.py", line 292, in alamo
    readTraceFile(vargs, data, debug)

  File "C:\Users\sds\Anaconda3\lib\site-packages\idaes\surrogate\alamopy\doalamo.py", line 1011, in readTraceFile
    'Cannot read from trace file "{}": {}'.format(trace_str, err)

AlamoError: Cannot read from trace file "trace.trc": [Errno 2] No such file or directory: 'trace.trc'

**Comment by niksah** [comment]
Hello,

 

If it’s not possible to upload your files, would you please send them to me by email at niksah@gmail.com <mailto:niksah@gmail.com> ? Also, what version of windows are you using? Is it 10 or an order version?

 

Best wishes, Nick

**Comment by mengleCMU** [comment]
Close this and add task of better error messages from ALAMOpy including data input, ALAMO existing on the computer, and errors in running.

**Comment by ksbeattie** [comment]
@4dsoftware, if you can get us more details to try and reproduce the problem please do.  Until then, I'll close this specific issue assuming that your problem is that ALAMO was not installed and we will work on improving the error reporting in that situation so that ALAMO not being installed is more clearly reported.
