### ISSUE TITLE
Stoichiometric Reactor Enhancement

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-pse#243]
I have a couple enhancement requests for the stoichiometric reactor.  I may have missed these if they exist already, so just let me know and close the issue if I overlooked something.

1.) The docs say a typical degree of freedom is extent of reaction, but they don't explicitly say what the variable is and don't show it in the variables table.

2.) It would be nice if you could specify conversion of components in addition to extent of reaction.  It's not a big deal, but it would keep me from having to write an extra constraint (or constraints) for it.

**Comment by andrewlee94** [comment]
@eslickj Point 1 is easily addressed, but point 2 is little more challenging. Conversion is written in terms of a specific component, which means the user need to specify what that component is - currently we make them do that by writing the constraint themselves. WE could add a config argument to let the user input this information, but we didn't think it was worth it originally.

**Comment by chineduobiora** [comment]
@eslickj I agree with @andrewlee94's points. @andrewlee94 I think you are in the better position to address this as I haven't worked on this model in the past 2 years.
