### ISSUE TITLE
"dangling" references cause problems with cloning and transformations

### ISSUE THREAD

**Issue by michaelbynum** [IDAES/idaes-pse#247]
Here is the example:

```
import pyomo.environ as pe
import idaes.core
import idaes.generic_models.unit_models
import idaes.generic_models.properties.swco2
from pyomo.network import Arc

m = pe.ConcreteModel()
m.fs = idaes.core.FlowsheetBlock()
m.fs.properties = idaes.generic_models.properties.swco2.SWCO2ParameterBlock()
m.fs.heater = idaes.generic_models.unit_models.Heater(default={'dynamic': False,
                                                               'property_package': m.fs.properties,
                                                               'has_pressure_change': True})
m.fs.heater2 = idaes.generic_models.unit_models.Heater(default={'dynamic': False,
                                                                'property_package': m.fs.properties,
                                                                'has_pressure_change': True})
m.fs.stream = Arc(source=m.fs.heater.outlet,
                  destination=m.fs.heater2.inlet)

try:
    m2 = pe.TransformationFactory('network.expand_arcs').create_using(m)
except Exception as err:
    print(err)
```

outputs

```
'NoneType' object has no attribute 'component'
```

Also, 

```
print(m.fs.heater.inlet.flow_mol[0] is m.fs.heater.control_volume.properties_in[0].flow_mol)  # True
```

outputs

```
True
```

but 

```
m2 = m.clone()
print(m2.fs.heater.inlet.flow_mol[0] is m2.fs.heater.control_volume.properties_in[0].flow_mol)  # False
```

outputs

```
False
```

Trying to clone `m2` produces the same error as above.
```
try:
    pe.TransformationFactory('network.expand_arcs').apply_to(m2)
except Exception as err:
    print(err)
```

outputs

```
'NoneType' object has no attribute 'component'
```

The transformation applied to the original model works because no cloning occurs.
```
pe.TransformationFactory('network.expand_arcs').apply_to(m) # okay
```

Note that some transformations do "work" (no exception is raised) after cloning. For example, the BigM transformation "works" with a cloned model. However, the result is that accessing anything on an inlet or outlet of a unit model in the resulting model does not do what is expected. You end up modifying the original model.

**Comment by michaelbynum** [comment]
I forgot to link the Pyomo issue: pyomo/pyomo#1675

**Comment by andrewlee94** [comment]
So, given the Pyomo discussion, what is the correct solution to this? @jsiirola @michaelbynum Should we always be attaching these `References` to a model somewhere?

**Comment by michaelbynum** [comment]
I think so.

**Comment by andrewlee94** [comment]
@michaelbynum Additionally - do you have a test that we could use to confirm that we have fixed the issue?

**Comment by michaelbynum** [comment]
I think the example I posted above would be a good test?

**Comment by Robbybp** [comment]
https://github.com/IDAES/idaes-dev/pull/1074 is the PR I mentioned. Re-adding the three lines we removed there I believe will fix your particular example.

**Comment by michaelbynum** [comment]
Thanks, @andrewlee94 !

**Comment by andrewlee94** [comment]
@michaelbynum I just put up a draft PR with what I have so far (#249). Attaching the dangling `References` to a `Block` fixed the issue with asserting that the reference component was the source component, but trying to clone the model whilst doing the `Arc` expansion still fails.

So, I think there is something more to this problem, but I don't know where to start looking. I am hoping the you or @jsiirola can take a look and tells us what the remaining issue is.

**Comment by andrewlee94** [comment]
@michaelbynum Also, is there something we could assert after doing the transformation (once it works) to ensure it worked properly.
