### ISSUE TITLE
ideas get-extensions sslerror and urlerror 

### ISSUE THREAD

**Issue by makaylas** [IDAES/idaes-pse#25]
A user send me an email with the following problem:

When I run command “ideas get-extensions” , get the sslerror and urlerror  

![5](https://user-images.githubusercontent.com/11697891/72098083-a3273c80-32d2-11ea-87fe-2ced0f5074d5.jpg)
![23](https://user-images.githubusercontent.com/11697891/72098094-a6bac380-32d2-11ea-83b3-7c5bfa57f1ed.jpg)

**Comment by makaylas** [comment]
Emailed reply from @eslickj 

I’m not really sure what the problem could be.  Let’s try to discuss this at the developer call on Thursday, and hopefully have a solution by the end of the week.  Judging by the file separator characters in the screenshots I wonder if it is a localization issue.

Yujeongwon,

Can you go to https://github.com/IDAES/idaes-ext/releases/tag/1.0.1 and download the zip files (lib and solvers) for your OS?  Then you can set the get extensions script to get the extensions from your local filesystem.

Run a command like this (but changed for wherever you put the files):

`idaes get-extensions --url file:///C:/users/eslickj/downloads/`

Let us know if that works.  Even if it does we’ll still want to get this fixed properly for you.

**Comment by makaylas** [comment]
We are closing this because the user did not get back to us.

**Comment by neiljonesdeloitte** [comment]
Hi Idaes team! I am hoping you can help me on a similar issue to this one. I am tryin to use Pyomo and IpOpt in a Docker Container, solving a non-linear problem. Please see my dockerfile photo below - everything works on install until I try to run idaes get-extensions. I also tried your suggestion (idaes get-extensions --url file:///C:/users/eslickj/downloads/), and that did not work either. Any help you can provide is super appreciated! Have been stuck for a day.
![Screen Shot 2022-09-29 at 8 17 30 AM](https://user-images.githubusercontent.com/92811267/193072160-181bd005-40de-4219-ae32-aa39adf0ccc6.png)
![Screen Shot 2022-09-29 at 8 18 05 AM](https://user-images.githubusercontent.com/92811267/193072201-509f0e06-aece-41d7-8acf-5026f09dd09c.png)

![Screen Shot 2022-09-29 at 8 17 50 AM](https://user-images.githubusercontent.com/92811267/193072187-862151f3-4ee5-4b63-8413-fadac913ee09.png)

**Comment by neiljonesdeloitte** [comment]
Update: I realized I needed to install lsb_release, which fixed the original error. BUT! Now it seems like ipopt doesnt actually get installed in the container when running idaes get-extensions. I am now trying to install via binary but am struggling there too.

**Comment by neiljonesdeloitte** [comment]
Hey everyone, i was able to get IPOPT running in Docker. Below are the run.py, dockerfile, and docker compose files that got it running. It takes forever to build, but it works for now! 
<img width="258" alt="Screen Shot 2022-10-03 at 8 55 31 AM" src="https://user-images.githubusercontent.com/92811267/193622737-0a6148aa-4550-493e-b741-6d8bea2eadf9.png">
<img width="417" alt="Screen Shot 2022-10-03 at 8 55 22 AM" src="https://user-images.githubusercontent.com/92811267/193622757-e3c8e9a2-ec00-4333-afd0-965e97326551.png">
<img width="535" alt="Screen Shot 2022-10-03 at 8 53 26 AM" src="https://user-images.githubusercontent.com/92811267/193622831-0f392d74-a77f-4173-ab73-822886ef77fe.png">

**Comment by ksbeattie** [comment]
@neiljonesdeloitte, glad you got it working.

Your Dockerfile, etc above might be useful to others, would you mind creating an entry in our [discussion forum](https://github.com/IDAES/idaes-pse/discussions) (say under the "Show and Tell" category) with your example?

**Comment by NNSJ** [comment]
Hello, we encountered a similar problem, if you do not add "--no-download", it will default to download, and then we could not access and have error "urllib.error.URLError: <urlopen error [Errno 111] Connection refused>"
.If we add the parameter "--no-download", although the installation is displayed successfully, but the running model still can not find solver"ipopt"
![问题](https://github.com/IDAES/idaes-pse/assets/38006441/c7dcd7b5-a7e8-421d-8bb8-f3bb60be09da)

**Comment by linshumeng** [comment]
Hi team,

I also use `--url` as an optional command, but I receive such error `urllib.error.HTTPError: HTTP Error 404: Not Found`. I put all '.tar' files either lib or solver under the dir.  I hope to know how I can use `--url` command. Is it a command that we can install lib and solver on our local machine. Thanks.

![image](https://github.com/IDAES/idaes-pse/assets/54089164/576f7c8f-360b-4b5b-95fe-9a56fb162596)

![image](https://github.com/IDAES/idaes-pse/assets/54089164/a62ae597-b6fe-4d46-9b9d-37628e904a51)
