### ISSUE TITLE
Tray column test issues.

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-pse#254]
I ran into a couple problems testing solvers, tray column related.  I guess since Ipopt generally seems to be working correctly, this may indicate that the tests are very delicate. 

1) 

```
__________________________ TestBTXIdeal.test_solution __________________________

self = <idaes.generic_models.unit_models.distillation.tests.test_tray_column.TestBTXIdeal object at 0x7f2e427d3b10>

....

 >       assert (pytest.approx(377.28, abs=1e-2) ==
                value(btx_fctp.fs.unit.reboiler.
                      bottoms.temperature[0]))
E       assert 377.28 ± 1.0e-02 == 377.2929829205527
E        +  where 377.28 ± 1.0e-02 = <function approx at 0x7f2e744275f0>(377.28, abs=0.01)
E        +    where <function approx at 0x7f2e744275f0> = pytest.approx
E        +  and   377.2929829205527 = value(<pyomo.core.base.var.SimpleVar object at 0x7f2e42bbbed0>)
```

2)

```
____________________ TestColumn.test_dynamic_initialization ____________________

self = <idaes.power_generation.carbon_capture.mea_solvent_system.unit_models.tests.test_column.TestColumn object at 0x7f2e40198c50>

....

 E               ValueError: Cannot load a SolverResults object with bad status: error

/root/miniconda/envs/idaes/lib/python3.7/site-packages/pyomo/core/base/PyomoModel.py:238: ValueError

```

**Comment by eslickj** [comment]
This was on Ubuntu 19.10.  Windows was successful.

**Comment by eslickj** [comment]
I guess I should also point out that since our usual automated tests run on Ubuntu 18.04, this isn't necessarily something we would usually see.  It could also be new due to PR #55 being merged.

**Comment by jghouse88** [comment]
I have seen this OS related failure once before. I'm not sure how to fix this as I don't have Ubuntu or CentOS anymore.

**Comment by jghouse88** [comment]
The first one can be fixed if I changed the tolerance to rel instead of abs. The second is MEA column related and it is a solver failure and that will be a more challenging thing to fix.

**Comment by andrewlee94** [comment]
It is possible that PR #55 did something, if so the problem will be in either the condenser or reboiler so should be easier to track down.

**Comment by ksbeattie** [comment]
This hasn't happened in a while, so closing it.
