### ISSUE TITLE
Flowsheet Visualization not working with new IDAES v1.9 install under Windows

### ISSUE THREAD

**Issue by MikeErbes** [IDAES/idaes-pse#255]
I recently updated to IDAES v1.9 (from 1.7) and am unable to get the flowsheet visualization running properly. It would not work under v1.7 previously, either. I am running on a Windows 10 PC. When I add the following line to my python model file:
    m.fs.visualize("My_Flowsheet", save_as="my_flowsheet.json")
everything seems to run OK and at the end of the execution it opens a browser window that includes some of the IDAES graphics, but it doesn't display the flowsehet and fails to properly construct the command menu. The resulting browser window looks like this:
 
![image](https://user-images.githubusercontent.com/69171683/111834827-616c2b80-88b1-11eb-950f-0ed8f7e32b0f.png)

This was using Chrome as the browser. I also tried using Microsoft Edge with the same effect. I wondered if running the python model from Spyder be the issue, so I tried running the model using IDLE, but the same thing happened.

Can anyone help? I don't know if something else needs to be installed, or if we need to adjust the browser settings, or what. 

Thanks,
Mike Erbes
Enginomix, LLC

**Comment by dangunter** [comment]
Looks like it's not finding the CSS and possibly other files.

**Comment by makaylas** [comment]
I think this might be a problem with upgrading and your conda env. If you want some help with this we can meet at Keith's office hours on Wednesdays at 9am pacific.

**Comment by dangunter** [comment]
@ksbeattie Did this get resolved at your office hours?

**Comment by MikeErbes** [comment]
Dan,

 

This didn’t get resolved yet. Our IDAES-related work is on pause at the moment (until summer, assuming we get follow-on funding). When/if we restart work, I’ll try completely un-installing/re-installing and see if we can figure out what the issue is.

 

Cheers,

 

Mike Erbes  

 

Michael R. Erbes, PhD | Enginomix, LLC | Menlo Park, CA  USA | Office 650.289.0670 ext 1#  | Cell 650.339.9483 |  <http://www.enginomix.net> www.enginomix.net
