### ISSUE TITLE
Document fix to Python 3.8 DLL error

### ISSUE THREAD

**Issue by dangunter** [IDAES/idaes-pse#258]
For Python 3.8 and maybe others, you can get an error when running Jupyter on Windows 10 about missing the win32api DLL.

There is a relatively easy fix:

```
pip uninstall pywin32
pip install pywin32==225
```

We should add this to the docs

**Comment by ksbeattie** [comment]
Perhaps this should go into a new? FAQ or troubleshooting section of the docs?
