### ISSUE TITLE
Add more than one inlet/outlet to a control volume

### ISSUE THREAD

**Issue by WheatZhang** [IDAES/idaes-pse#26]
I'm trying to define a unit block that has multiple inputs/outputs. How do I construct the balance equation using "ControlVolume0DBlockData" or some basic class else? - It seems the "properties_in" and "properties_out" are only indexed by time in "ControlVolume0DBlockData"?

**Comment by andrewlee94** [comment]
Hi @WheatZhang. This depends on what sort of behavior you are trying to model and how the inlets and outlets interact.

Control volumes represent a single, well defined volume over which we write a set of material and energy balances, with a single flow in and a single flow out, plus a potential mass transfer term which links it to some other control volume.

When dealing with multiple inlets and outlets, you generally have two cases (or a combination of the two):

1. Some inlets are mixed together into a single flow which passes through a control volume and are then split into some number of outlets. In this case, you would combine a Mixer, Control Volume and Separator block within your unit model.
2. Flows do not mix, and the only interaction between them is via mass transfer (e.g. membranes, gas-solids contactors, gas-liquid contactors). In this case, you would have different control volumes for each flow/phase with mass transfer terms, and a set of constraints linking the mass transfer terms and describing the magnitude of the mass transfer.

Hope that helps to get you started on understanding how to model your system in IDAES, and feel free to ask more questions when you have them.

**Comment by WheatZhang** [comment]
Thank you for your prompt response and I think the first case you explained is suitable for me. I misunderstood the role of the control volume block. For me, the Mixer-ControlVolume-Separator structural is something unusual to set up a Pyomo model manually. 
Hope the more predefined library models will save the users from concerning the details of IDAES implementation.
