### ISSUE TITLE
IDAES install on Ubuntu 19.10

### ISSUE THREAD

**Issue by allanc1** [IDAES/idaes-pse#27]
Hi
I have followed the instructions with pip3 install idaes-pse, idaes get-extensions, set PATH to (in my case) /home/allan/.local/bin but when I run the test, I get the following errors:

```
  File "/home/allan/.local/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 152, in exec_module
    exec(co, module.__dict__)
  File "/home/allan/anaconda3/lib/python3.7/site-packages/hypothesis/__init__.py", line 26, in <module>
    from hypothesis.core import example, find, given, reproduce_failure, seed
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/home/allan/.local/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 152, in exec_module
    exec(co, module.__dict__)
  File "/home/allan/anaconda3/lib/python3.7/site-packages/hypothesis/core.py", line 67, in <module>
    from hypothesis.internal.conjecture.engine import ConjectureRunner, sort_key
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/home/allan/.local/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 152, in exec_module
    exec(co, module.__dict__)
  File "/home/allan/anaconda3/lib/python3.7/site-packages/hypothesis/internal/conjecture/engine.py", line 41, in <module>
    from hypothesis.internal.conjecture.pareto import NO_SCORE, ParetoFront, ParetoOptimiser
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/home/allan/.local/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 152, in exec_module
    exec(co, module.__dict__)
  File "/home/allan/anaconda3/lib/python3.7/site-packages/hypothesis/internal/conjecture/pareto.py", line 22, in <module>
    from hypothesis.internal.conjecture.shrinker import sort_key
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/home/allan/.local/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 152, in exec_module
    exec(co, module.__dict__)
  File "/home/allan/anaconda3/lib/python3.7/site-packages/hypothesis/internal/conjecture/shrinker.py", line 1447, in <module>
    @attr.s(slots=True, eq=False)
TypeError: attrs() got an unexpected keyword argument 'eq'
```

I was unable to install libgfortran3 on this distro and instead installed libgfortran9 which is the default.

Any help please.

Cheers

**Comment by eslickj** [comment]
It looks like hypothesis is some unit testing frame work, but we don't use it for IDAES.  My guess is it's being triggered by running pytest somehow.

I have two suggestions.
1) Uninstall  hypothesis
2) If you need hypothesis, try installing IDAES in another environment using conda environments, vitualenv, or similar.

On the separate issue of gfortan3. We are aware this isn't readily available on Ubuntu 19.10.  We will probably provide another version of the binaries that are compatible with newer versions.  For what we have, I think libgfortan3 is specifically required.

**Comment by eslickj** [comment]
On the IDAES team @dangunter encountered the gfortran issue, so I paster his fix below.

> fwiw, the "custom installation" mentioned above is downloading:
> 
>     https://packages.debian.org/stretch/libgfortran3
>     https://packages.debian.org/stretch/gcc-6-base
> 
> and installing both with sudo dpkg -i. So I guess we could add that to the install notes, but it seems like a lot of work for a regular user.

**Comment by allanc1** [comment]
Thanks for your help and there is good progress. Unfortunately it fails with the iapws.py tests.

Regards

**Comment by eslickj** [comment]
Can you post the details of the test failure?  I know there may be a large amount of output so it may not be easy.  The iapws stuff uses a compiled dynamically linked library, so there could be an issue there.

**Comment by allanc1** [comment]
John
Here are the details:
================================================================================================= FAILURES =================================================================================================
________________________________________________________________________________________ TestPHvalues.test_tau_sat _________________________________________________________________________________________

self = <test_iapws95.TestPHvalues object at 0x7f46631b6f10>, model = <pyomo.core.base.PyomoModel.ConcreteModel object at 0x7f466d4362d0>

    def test_tau_sat(self, model):
        cond = read_data("sat_prop.txt", col=2)
        for c in cond:
            tau = value(model.prop_in.func_tau_sat(c[1]/1000.0))
            T = 647.096/tau
            print("{}, {}, {}".format(c[1], c[0], T))
>           assert(abs(T-c[0]) < 0.1)
E           assert nan < 0.1
E            +  where nan = abs((nan - 647.096))

/home/allan/.local/lib/python3.7/site-packages/idaes/property_models/tests/test_iapws95.py:2284: AssertionError

__________________________________________________________________________________ TestPHvalues.test_liquid_enthalpy_sat ___________________________________________________________________________________

self = <test_iapws95.TestPHvalues object at 0x7f46646e5a90>, model = <pyomo.core.base.PyomoModel.ConcreteModel object at 0x7f466d4362d0>

    def test_liquid_enthalpy_sat(self, model):
        cond = read_data("sat_prop.txt", col=5)
        for c in cond:
            if c[0] > 645:  # getting very close to critical point
                tol = 0.01
            else:
                tol = 0.001
            model.prop_in.pressure = c[1]
            enth = value(model.prop_in.enth_mol_sat_phase["Liq"] /
                         model.prop_in.mw/1000.0)
>           assert(abs((enth-c[2])/c[2]) < tol)
E           assert nan < 0.01
E            +  where nan = abs(((nan - 2084.3) / 2084.3))

/home/allan/.local/lib/python3.7/site-packages/idaes/property_models/tests/test_iapws95.py:2320: AssertionError
___________________________________________________________________________________ TestPHvalues.test_vapor_enthalpy_sat ___________________________________________________________________________________

self = <test_iapws95.TestPHvalues object at 0x7f46631b6410>, model = <pyomo.core.base.PyomoModel.ConcreteModel object at 0x7f466d4362d0>

    def test_vapor_enthalpy_sat(self, model):
        cond = read_data("sat_prop.txt", col=17)
        for c in cond:
            if c[0] > 645:  # getting very close to critical point
                tol = 0.01
            else:
                tol = 0.001
            model.prop_in.pressure = c[1]
            enth = value(model.prop_in.enth_mol_sat_phase["Vap"] /
                         model.prop_in.mw/1000.0)
>           assert(abs((enth-c[2])/c[2]) < tol)
E           assert nan < 0.01
E            +  where nan = abs(((nan - 2084.3) / 2084.3))

/home/allan/.local/lib/python3.7/site-packages/idaes/property_models/tests/test_iapws95.py:2332: AssertionError
________________________________________________________________________________ TestPHvalues.test_enthalpy_of_vaporization ________________________________________________________________________________

self = <test_iapws95.TestPHvalues object at 0x7f465f697810>, model = <pyomo.core.base.PyomoModel.ConcreteModel object at 0x7f466d4362d0>

    def test_enthalpy_of_vaporization(self, model):
        cond_liq = read_data("sat_prop.txt", col=5)
        cond_vap = read_data("sat_prop.txt", col=17)
        for i, c in enumerate(cond_liq):
            if c[0] > 645:  # getting very close to critical point
                tol = 0.05
            else:
                tol = 0.001
            model.prop_in.pressure.value = c[1]
            enth = value(model.prop_in.dh_vap_mol/model.prop_in.mw/1000.0)
            enth_dat = cond_vap[i][2] - c[2]
            if abs(enth_dat) > 1e-8:
                assert(abs((enth-enth_dat)/enth_dat) < tol)
            else:
>               assert(abs(enth-enth_dat) < tol)
E               assert nan < 0.05
E                +  where nan = abs((nan - 0.0))

/home/allan/.local/lib/python3.7/site-packages/idaes/property_models/tests/test_iapws95.py:2348: AssertionError
========================================================================================= short test summary info ==========================================================================================
FAILED .local/lib/python3.7/site-packages/idaes/property_models/tests/test_iapws95.py::TestPHvalues::test_tau_sat - assert nan < 0.1
FAILED .local/lib/python3.7/site-packages/idaes/property_models/tests/test_iapws95.py::TestPHvalues::test_liquid_enthalpy_sat - assert nan < 0.01
FAILED .local/lib/python3.7/site-packages/idaes/property_models/tests/test_iapws95.py::TestPHvalues::test_vapor_enthalpy_sat - assert nan < 0.01
FAILED .local/lib/python3.7/site-packages/idaes/property_models/tests/test_iapws95.py::TestPHvalues::test_enthalpy_of_vaporization - assert nan < 0.05
========================================================================== 4 failed, 1567 passed, 11 skipped in 323.88s (0:05:23) ==========================================================================

Regards

Allan

**Comment by eslickj** [comment]
Thanks.  That's a new one for me.  I'll look into it.

**Comment by allanc1** [comment]
John

There is a potential clash with Coolprop which includes iapws95 and iapws if97 libraries. I would be very reluctant to remove Coolprop.

Regards

**Comment by eslickj** [comment]
I'm pretty sure it's not a conflict with Coolprop, so we should be okay there.

**Comment by andrewlee94** [comment]
@eslickj Is this beign addressed in the new binary builds?

**Comment by ksbeattie** [comment]
@allanc1, could you try this again with the latest release?

**Comment by ksbeattie** [comment]
Assuming this is ok now.  Feel free to re-open if not.
