### ISSUE TITLE
Convergence issues with equilibrium reactor and Gibbs Energy equation

### ISSUE THREAD

**Issue by Andresj89** [IDAES/idaes-pse#281]
Upon further testing of the Gibbs Energy form for Keq, I'm getting numerical issues when trying to converge an equilibrium reactor. The initialization method fails, and the issue seems to be caused by the Log function. I added scaling factors based on the known solution of the example and added bounds to `equilibrium_reaction_extent` but the issue still persists. I attach the files necessary to replicate this issue.

[density_contribution.zip](https://github.com/IDAES/idaes-pse/files/6251188/density_contribution.zip)

**Comment by andrewlee94** [comment]
The problem has been found and does not require fixing.
