### ISSUE TITLE
Possibility to build all unit models with control volume.

### ISSUE THREAD

**Issue by TheHuangs** [IDAES/idaes-pse#29]
![image](https://user-images.githubusercontent.com/50746074/77518051-0e3ae500-6eb8-11ea-8353-5a81d5b42547.png)
Hi, would you like to answer me these questions?
(1)Is that possible to build all the unit models(including columns, separators, heat exchangers, even other complicated unit) using the ControlVolume0DBlock or ControlVolume1DBlock as shown in the picture? 
(2)Is that possible to add "add_material_balances"/"add_total_enthalpy_balances"/"add_state_blocks" into the ControlVolume0DBlock in theory, just the same as what "property_package"/"dynamic" does.

**Comment by andrewlee94** [comment]
Hi @TheHuangs,

I am not quite sure I follow your questions, but for what I think you are asking:

1. The intent is that most unit models can be constructed from one or more Control Volumes, with more complex unit operations requiring more than one (e.g. heat exchangers). However, there are many cases where you need something else (e.g. the isentropic pressure changer) or it is more efficient to build a custom unit (e.g. the upcoming tray model for a distillation column which will hopefully be released in a few weeks).
2. We deliberately left the `add_material_balances`, etc., out of the automated part of the control volume, as we felt this obscured too much of what was going on and left too many questions for the user. However, we did add an `auto_construct` option in the Control Volume arguments - if set to `auto_construct=True` the Control Volume will try to automatically construct the balance equations by looking at the Unit Model's config arguments (specifically it looks for arguments like `material_balance_type` in `unit.config`). You can see this in control_volume_base.py, along with a template `ConfigBlock` for a unit model which has all the required arguments.

**Comment by TheHuangs** [comment]
Hi @andrewlee94 ,
As for the first question, is it possible to build a distillation column using  one or more Control Volumes?  I want to know whether all the units in Aspen plus or any other simulation softwares  can be built on Control Volumes.

**Comment by andrewlee94** [comment]
@TheHuangs Yes, it is possible to build a distillation column using Control Volumes, Mixers and Splitters. A tray in a column can be modelled as a mixer -> control volume -> splitter, and then a series of these connected to make a column. This is a rather inefficient implementation (it duplicates a lot of states), but it should work.

However, we are currently working on a model library for distillation that will hopefully be released next month. Once that is available, there will be a distillation column model that you will be able to use directly. This will also have initialisation routines we have developed for distillation columns so you do not have to create your own (which is not easy).

**Comment by andrewlee94** [comment]
@TheHuangs Have we sufficiently answered your questions regarding on using control volumes to build unit models? I am going through current issues and cleaning up those that have been addressed.

**Comment by TheHuangs** [comment]
@andrewlee94 yes, you can clean up this issue. thank you

**Comment by sabualkaz** [comment]
Hi @andrewlee94  I am wondering what is the status of the distillation model. I don’t yet see it in the documentation.

> However, we are currently working on a model library for distillation that will hopefully be released next month. Once that is available, there will be a distillation column model that you will be able to use directly. This will also have initialisation routines we have developed for distillation columns so you do not have to create your own (which is not easy).

**Comment by davidstadem** [comment]
Hi @sabualkaz you can check out [https://github.com/IDAES/idaes-pse/tree/main/idaes/generic_models/unit_models/distillation](https://github.com/IDAES/idaes-pse/tree/main/idaes/generic_models/unit_models/distillation). You're right it does not seem to be in the documentation anywhere.

**Comment by andrewlee94** [comment]
@sabualkaz Sorry for the delay responding. The distillation models have taken a lot longer than exacted, and we are still doing the final touches (notably documentation). However, as @davidstadem noted, the models themselves are now available although I don't think they have made it into a formal release yet.
