### ISSUE TITLE
CH4 standard entropy

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-pse#300]
I think the CH4 standard entorpy here https://github.com/IDAES/idaes-pse/blob/a2851a8f054b25249df14cb245ec642ff7765e51/idaes/power_generation/properties/natural_gas_PR.py#L244 may be wrong.

**Comment by AlexNoring** [comment]
That number agrees with the value on NIST. What source are you looking at?
https://webbook.nist.gov/cgi/cbook.cgi?ID=C74828&Units=SI&Mask=1#Thermo-Gas

**Comment by eslickj** [comment]
@AlexNoring is it supposed to be negative?  NIST has it as positive I think.
