### ISSUE TITLE
Commas in the variable name in the stream table break the csv export in the UI

### ISSUE THREAD

**Issue by makaylas** [IDAES/idaes-pse#306]
If there is a comma in the variable name in the stream table it messes up the csv export and you get extra cells.

The commas need to be stripped out of the variable names

**Comment by andrewlee94** [comment]
I will note that the most common appearance of commas in variable names will be as part of an indexed variable; `var["a", "b"]`.

In this case the comma is fairly important, so we should think about what to do about it.

**Comment by ksbeattie** [comment]
@jsiirola points out that now with Pyomo 6.0, variable names quoting is improved so this might be easier to fix now.
