### ISSUE TITLE
AttributeError after upgrade from IDAES v1.7 to v1.9

### ISSUE THREAD

**Issue by sk2blue** [IDAES/idaes-pse#311]
Hello,

Recently, I faced AttributeError issue after upgrade from IDAES v1.7 to v1.9.
I tried several ways such as removal legacy of old version of IDAES, reinstall anaconda but could not solve it.
Then, I just format PC and it was well working but realized that IDAES v1.9 is not working after installation of ASPEN Plus.
Note that it was okay for IDAES v1.7 but problem is occurred for new version of IDAES v1.9.
So, could you advise to fix this problem?? Following is error message.

IPython 7.19.0 -- An enhanced Interactive Python.

runfile('C:/Users/User/anaconda3/Lib/site-packages/idaes/power_generation/flowsheets/supercritical_steam_cycle/supercritical_steam_cycle.py', wdir='C:/Users/User/anaconda3/Lib/site-packages/idaes/power_generation/flowsheets/supercritical_steam_cycle')
Traceback (most recent call last):

  File "C:\Users\User\anaconda3\Lib\site-packages\idaes\power_generation\flowsheets\supercritical_steam_cycle\supercritical_steam_cycle.py", line 33, in <module>
    from idaes.core import FlowsheetBlock  # Flowsheet class

  File "C:\Users\User\anaconda3\lib\site-packages\idaes\core\__init__.py", line 3, in <module>
    from .unit_model import UnitModelBlockData, UnitModelBlock

  File "C:\Users\User\anaconda3\lib\site-packages\idaes\core\unit_model.py", line 24, in <module>
    from .property_base import StateBlock

  File "C:\Users\User\anaconda3\lib\site-packages\idaes\core\property_base.py", line 43, in <module>
    from idaes.core.util import scaling as iscale

  File "C:\Users\User\anaconda3\lib\site-packages\idaes\core\util\scaling.py", line 34, in <module>
    from pyomo.contrib.pynumero.interfaces.pyomo_nlp import PyomoNLP

  File "C:\Users\User\anaconda3\lib\site-packages\pyomo\contrib\pynumero\interfaces\pyomo_nlp.py", line 26, in <module>
    from ..sparse.block_matrix import BlockMatrix

  File "C:\Users\User\anaconda3\lib\site-packages\pyomo\contrib\pynumero\sparse\__init__.py", line 11, in <module>
    from ..dependencies import numpy_available, scipy_available

  File "C:\Users\User\anaconda3\lib\site-packages\pyomo\contrib\pynumero\dependencies.py", line 30, in <module>
    scipy_sparse.generate_import_warning('pyomo.contrib.pynumero')

AttributeError: module 'scipy.sparse' has no attribute 'generate_import_warning'

**Comment by adowling2** [comment]
@sk2blue Thank you for your question. What version of python are you using?

**Comment by sk2blue** [comment]
Thank you for your response. The version of my python is 3.8.5 (installed with latest Anaconda). Actually, I also tried to install latest version of python (v3.9 from python official website), but it was still not working.

**Comment by adowling2** [comment]
Can you add a link to the IDAES installation instructions you followed? Can you also share the version of Pyomo you are using?

**Comment by sk2blue** [comment]
After installation of Anaconda, I followed the generic installation instruction on the 'https://idaes-pse.readthedocs.io/en/stable/getting_started/index.html' as following. (using Anaconda Powershell Prompt (admin))

pip install idaes-pse
idaes get-extensions
idaes get-examples

And, my Pyomo version is Pyomo-5.7.3 and scipy version is 1.5.2.

**Comment by Robbybp** [comment]
Looks like a bug where `pyomo.common.dependencies` believes scipy is not available, but scipy.sparse is. This could be a bug in the Pynumero dependencies.py logic, where it checks `scipy_available` rather than `scipy_sparse_available`, or it could be a bug in `pyomo.common.dependencies` where we can detect and import scipy.sparse, but not scipy itself.

You might try running
```python
>>> from pyomo.contrib.pynumero.interfaces.pyomo_nlp import PyomoNLP
```
in your Python interpreter. If you get the same error, I would open a bug report in the Pyomo repo.

**Comment by sk2blue** [comment]
@Robbybp Exactly. The same error is occured as below when I trying your instruction.

(base) PS C:\Users\User> python
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (
![error capture](https://user-images.githubusercontent.com/62978443/116628613-73e68400-a98a-11eb-8c8a-75c7d7ef7946.PNG)
AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyomo.contrib.pynumero.interfaces.pyomo_nlp import PyomoNLP
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\anaconda3\lib\site-packages\pyomo\contrib\pynumero\interfaces\pyomo_nlp.py", line 26, in <module>
    from ..sparse.block_matrix import BlockMatrix
  File "C:\Users\User\anaconda3\lib\site-packages\pyomo\contrib\pynumero\sparse\__init__.py", line 11, in <module>
    from ..dependencies import numpy_available, scipy_available
  File "C:\Users\User\anaconda3\lib\site-packages\pyomo\contrib\pynumero\dependencies.py", line 30, in <module>
    scipy_sparse.generate_import_warning('pyomo.contrib.pynumero')
AttributeError: module 'scipy.sparse' has no attribute 'generate_import_warning'

**Comment by Robbybp** [comment]
I tried to reproduce this with a fresh Python 3.8.5, Scipy 1.5.3, Pyomo 5.7.3 install, and was unable to. The problem seems to be that Pyomo does not believe that Scipy is available, even though it clearly is. You are getting a confusing error message because of a typo in pyomo.contrib.pynumero.dependencies, where we call `scipy.sparse.generate_import_warning` rather than `scipy.generate_import_warning`. I think there were some recent changes to the pyomo.common.dependencies module, which might be better able to detect scipy. You might try (probably in a fresh conda environment):
```sh
$ pip install git+https://github.com/PyUtilib/pyutilib.git
$ pip install git+https://github.com/Pyomo/pyomo.git
$ pip install idaes-pse
```
Then try:
```python
>>> from pyomo.common.dependencies import scipy_available
>>> bool(scipy_available)
```
If the result is `True`, try running whatever code generated your original error. No guarantee this will work, as I have no idea why Scipy is not getting detected.

**Comment by sk2blue** [comment]
@Robbybp 
Thank you for detailed advise. However, unfortunately, it is still not working with 'False' message if I run 'bool(scipy_available)'.
It seems the problem is more complicated than expected due to conflicting with ASPEN products.

**Comment by sk2blue** [comment]
@Robbybp @adowling2 
I just found an alternative solution for this issue. I installed 'Miniconda' insteand of 'Anaconda' and run the file, so it is now well working! It seems there is some problem between Anaconda and ASPEN products, but miniconda is okay.
Thank you for your advises so far!

**Comment by Robbybp** [comment]
Glad you found a workaround! Out of curiosity, was IDAES 1.9 working before ASPEN Plus was installed?

**Comment by sk2blue** [comment]
Thank you and yes, It was working before ASPEN Plus was installed. I had no trouble with IDAES 1.7 even ASPEN Plus installed but do not know why it's not working with new IDAES 1.9.

**Comment by adowling2** [comment]
@sk2blue For documentation sake, what version of ASPEN Plus are you using. This will be helpful to know if someone else runs into the same issue.

When you were installing IDAES 1.9 using Anaconda, did you create an environment?

**Comment by sk2blue** [comment]
@adowling2 My ASPEN Plus version is v11. And, I don't know what exactly creating an environment, but I just followed generic installation procedure on IDAES documentation. My colleague here also troubled with same issue as she installed ASPEN Plus v11.
