### ISSUE TITLE
Create IDAES environment info command

### ISSUE THREAD

**Issue by adowling2** [IDAES/idaes-pse#313]
Proposal: create a command that prints out the following information:
- Python version
- idaes version (and if dev, githash)
- Pyomo version
- numpy, scipy, etc. version
- operating system

Then add this to the documentation.

**Comment by eslickj** [comment]
I about to do this, but I'm not so sure how to get the git hash reliably.  Maybe it should be part of the Version class in ver.py.  Looks like that was @dangunter's doing.  I got the rest though.  I will also look into the hash, but if I can't do it fast, I'll leave it for the future.  I guess maybe you need to grab that information when you install IDAES, if you don't install it in-place?
