### ISSUE TITLE
Cannot find library "/Users/eden/.idaes/lib/cubic_roots.so".

### ISSUE THREAD

**Issue by TheHuangs** [IDAES/idaes-pse#32]
When I  test the PR CEOS, I encounter the error "Cannot find library "/Users/eden/.idaes/lib/cubic_roots.so".
function ceos_z_liq not available"  encouted.  Would you like to tell me how to compile the cubic_roots.c to get cubic_roots.so?

**Comment by jghouse88** [comment]
If you are using recent versions, just run the following from command line or terminal: 

```
idaes get-extensions 
```

**Comment by TheHuangs** [comment]
@jghouse88 ,  I install get-extensions, the error  shows :"raise Exception('Mac OSX currently unsupported')"I checked the document, it says that Mac/OSX not be supported.
![image](https://user-images.githubusercontent.com/50746074/79931366-719b4100-847d-11ea-8a3d-b0bc2d9faa25.png)

**Comment by jghouse88** [comment]
Yes, unfortunately we do not suport Mac/OSX yet. @ksbeattie @eslickj  ETA on when we will have this support?

**Comment by eslickj** [comment]
I'm not sure.  Let's add this to the developer call topics tomorrow.  Not having access to a Mac, I can't really provide good instructions, but you can find what you need to build the libraries at https://github.com/IDAES/idaes-ext. You should be able to follow the steps in scripts/compile_libs.sh

**Comment by andrewlee94** [comment]
This is part of https://github.com/IDAES/idaes-dev/issues/513.
