### ISSUE TITLE
Add units column to stream table in IFV

### ISSUE THREAD

**Issue by makaylas** [IDAES/idaes-pse#322]
Add a column to the flowsheet viewer stream table that shows the units for a given row.

There is a possibility that the row may contain different units (ex. lb/ft and kg/m) so you may need to get the units of the first entry of the row and then convert the entire row to those units via `pyunits.convert(var[index], to_units=output_units)`

To get the units:
```
from pyomo.environ import units as pyunits

pyunits.get_units(var[index])
```

Note: `get_units` only works on an element of an indexed variable so you shouldn't use it on a variable container.

**Comment by dangunter** [comment]
See also #44
