### ISSUE TITLE
Uncertainty example runs code on import

### ISSUE THREAD

**Issue by andrewlee94** [IDAES/idaes-pse#332]
One of the examples for the uncertainty propagation tools runs code on import:

idaes/apps/uncertainty_propagation/examples/simple_opt_problem.py

This causes the IDAES imports test (idaes/tests/test_import.py) to fail.

Additionally, some of the test for uncertainty propagation lack pytest marks.

**Comment by adowling2** [comment]
@andrewlee94 What specifically is wrong with this file?
https://github.com/IDAES/idaes-pse/blob/main/idaes/apps/uncertainty_propagation/examples/simple_opt_problem.py

It has similar import statements as other examples. This example does include a few assert statements that can (perhaps should) be removed.

@adowling2 TODO. Add pytest marks in this file https://github.com/IDAES/idaes-pse/blob/main/idaes/apps/uncertainty_propagation/tests/test_uncertainties.py:
- [ ] test_clean_variable_name1
- [ ] test_clean_variable_name2

**Comment by andrewlee94** [comment]
The issue is not the import statements, but rather the fact that the body of the code is written at the module level rather than wrapped inside a function. When the module is imported, Python runs all the code at the module level immediately, meaning that importing the file triggers the building and execution of the model immediately.

See https://github.com/IDAES/idaes-pse/blob/main/idaes/power_generation/flowsheets/subcritical_power_plant/steam_cycle_flowsheet.py for example.

Note that all the code is wrapped in methods (e.g. `add_unit_models`), and that at the end there is a final `if __name__ == "__main__":` section. This prevents the code from being run on import, but allows the script to still be run from the command line if desired.

**Comment by adowling2** [comment]
@andrewlee94 Got it. This will be an easy fix.

**Comment by jsiirola** [comment]
@dangunter: Pyomo has a test ([here](https://github.com/Pyomo/pyomo/blob/baf79e549edf410d2e07392b0072671a5f1ffbc6/pyomo/environ/tests/test_environ.py#L87)) for testing the import time of all the modules.  You might be able to adapt that for catching modules that do "too much" work upon import.

**Comment by ksbeattie** [comment]
@adowling2, could you assign someone to make these fixes?  These will soon start failing tests....

**Comment by lbianchi-lbl** [comment]
Just FYI: the missing pytest markers (but not the other fixes) have been added as part of #382.

**Comment by ksbeattie** [comment]
@adowling2, do you have someone (a student) you could assign this to?

**Comment by adowling2** [comment]
@ksbeattie @lbianchi-lbl I just opened a PR to fix this. I just had to add `if __name__ == "__main__":` to three files... Did this need a more complex change?
