### ISSUE TITLE
Generic properties components not is phase

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-pse#338]
There is a least one maybe more places where components that don't exist in a phase cause trouble in the general properties module.  Here is one I know of:

``` python
    def _mw(self):
        try:
            self.mw = Expression(
                    doc="Average molecular weight",
                    expr=sum(self.phase_frac[p] *
                             sum(self.mole_frac_phase_comp[p, j] *
                                 self.params.get_component(j).mw
                                 for j in self.params.component_list)
                             for p in self.params.phase_list))
```

The component list needs to be restricted to the components that exist in a phase.  @minhwvu brought this to my attention.

**Comment by adowling2** [comment]
@agarciadiego Have you encounter any other issues with calculating physical properties when one component is not in a phase (e.g., non-condensibles)?

**Comment by andrewlee94** [comment]
There are probably a few of these hiding somewhere in the code, as it is hard to do a general search for them.

The fix is easy enough, you just need to add `if (p, j) in self.params.phase_component_set else 0` as shown below.

```
    def _mw(self):
        try:
            self.mw = Expression(
                    doc="Average molecular weight",
                    expr=sum(self.phase_frac[p] *
                             sum(self.mole_frac_phase_comp[p, j] *
                                 self.params.get_component(j).mw
                                 for j in self.params.component_list
                                 if (p, j) in self.params.phase_component_set else 0)
                             for p in self.params.phase_list))
```
