### ISSUE TITLE
Upstream Pyomo changes

### ISSUE THREAD

**Issue by dangunter** [IDAES/idaes-pse#340]
From John Siirola:

FYI: there are a bunch of semi-significant changes coming from upstream Pyomo (some will make the 6.0 release, and some will hit just after):
1. https://github.com/Pyomo/pyomo/pull/1954 - casting a logical expression to a bool will generate an exception unless the expression is a constant.  This will mean that we will probably need to add a lot more value() calls through IDAES (especially in tests)
2. https://github.com/Pyomo/pyomo/pull/1960 - the Disjunct indicator_var  is switching from a Var (binary) to a BooleanVar.  There is a deprecation path, so it shouldn't break anything
3. https://github.com/Pyomo/pyomo/pull/1971 - Pyomo is finally renaming the scalar components from, e.g.,  SimpleVar  to ScalarVar.  The old names will still exist, but will issue deprecation warnings
4. (good news): https://github.com/Pyomo/pyomo/pull/1966 you can (finally) set united Vars / Params using united expressions.  Any necessary conversions happen automatically.  This won't require an immediate change in IDAES, but we will be able to change things like rhoc = 322  # kg/m3 to rhoc = 322 * units.kg/units.m**3
5. [After 6.0]: there are ongoing discussions as to if it makes sense to change (well, clearly define) the semantics of value().  One proposal would be for the value() of an expression with units to return a pint quantity (i.e., magnitude*units) instead of a float.  The bare float would be accessible (efficiently) through a new numeric_value() method.

**Comment by andrewlee94** [comment]
To test this and find any issues, we are going to need a version of Pyomo to test against. I am hopeful that the first issue should not be much of a problem as we (or at least I) try to use `value()` everywhere.

The third point is more one for us to think about in terms of simplifying our APIs in future.

The fourth point will cause problems however, so we should work out how we plan to address this as it comes up.

**Comment by eslickj** [comment]
I may be too trouble avoidant, but on point 3, does it make more sense to keep value as is and add like value_with_units()?  Then fix could take a value with no units and assume the units are the same as the variable you are fixing, or take a value with units and do the conversion.  Then everything is smooth with no major overhauls required.

**Comment by jsiirola** [comment]
The first 4 have PRs we can start testing against. @andrewlee94, your counting confuses me [I just went back and explicitly numbered them], as I think (5) is the one that will potentially cause us significant work, followed by (1) - I was surprised how many tests we were implicitly using equality.  

(2) and (4) should be no-ops.  

(3) will cause some noise.  I just searched through IDAES-PSE, and it looks like it won't affect much (other than breaking matopt - there are "`is`" comparisons with `SimpleParam` there that will break.

**Comment by adowling2** [comment]
@jsiirola Does Pyomo 6.0 deprecate PySP? If so, that might cause some parmest examples to fail. I am just mentioning it here in case IDAES examples/tests that use parmest start failing.

**Comment by andrewlee94** [comment]
@jsiirola I went back and updated the numbering to match your (my count was off). I agree that [5] will be the most work and [1] will depend on how lazy people were when writing tests.

**Comment by jsiirola** [comment]
@adowling2: yes, 6.0 removes PySP form the Pyomo distribution (it is now available as a separate package).  We have been testing with it as a new dependency until Pyomo/pyomo#1778 was merged.  Now we should have no dependencies on PySP in Pyomo or IDAES.

**Comment by jsiirola** [comment]
> I may be too trouble avoidant, but on point 3, does it make more sense to keep value as is and add like value_with_units()? 

@eslickj, by point 3, I assume you mean [5]? That is something that we have discussed, and while that would be backwards compatible, it introduces some unpleasant asymmetries and potentially require users to change how they work with models based on if the model (or variable) had units or not.  That said, *nothing* has been formally proposed or decided on, and this group will be able to weigh in on the proposal.

**Comment by andrewlee94** [comment]
I have started testing and fixing point 1. There are a lot of things that this broke, but the fixes are not hard.

**Comment by PTA0001** [comment]
@andrewlee94 , my code is broken,**error msg below**: is this as a result of the changes mentioned here or previous update?
``` ImportError: cannot import name 'ModelComponentFactory' from 'pyomo.core.base.component' ```

**Comment by andrewlee94** [comment]
@PTA0001 Did you update your version of Pyomo? IDAES has moved to using Pyomo 6, which made a lot of changes in the Pyomo code.

**Comment by PTA0001** [comment]
@andrewlee94, Thanks,  upgrading Pyomo to Pyomo 6 resolves the ImportError.
