### ISSUE TITLE
dyn_utils can attempt to set value of Fixed Var to None

### ISSUE THREAD

**Issue by andrewlee94** [IDAES/idaes-pse#346]
The dynamic utilities tools have a potential edge case where the `copy_values_at_time` method can set the value of a fixed `Var` to `None` - see line 736 in the `dyn_utils` module. Obviously, this is a bad idea to start with, and as of the current main of Pyomo results in an `Exception` (although this is due to a bug/edge case in the unit conversion tools).

However, looking at the `copy_values_at_time` method, it is not clear what should happen in this case. As the variable is a fixed variable that tends to imply it is important (unless it is stale at the new time point), so the value chosen cannot be arbitrary.

**Comment by andrewlee94** [comment]
This issue is currently blocking #343.

**Comment by Robbybp** [comment]
I think the correct option here is to not copy values of None. Is there a failing test I can look at to see if this is appropriate for the particular use case that is failing?

**Comment by andrewlee94** [comment]
https://github.com/IDAES/idaes-pse/pull/343/checks?check_run_id=2603599808

**Comment by andrewlee94** [comment]
I might have been mistaken on the variable being fixed too - I misread the logic originally. The best approach is probably to just not copy the value if the value is None.

**Comment by andrewlee94** [comment]
Talking to @jsiirola, he suggests we just copy the `None` value and let the sub-solve handle it - i.e. the `None` is there for a reason.

**Comment by Robbybp** [comment]
Fair enough, I'm fine with that.

**Comment by andrewlee94** [comment]
https://github.com/Pyomo/pyomo/pull/1977 appears to have resolved the underlying issue with setting he value of a `Var` to `None`, so based on our discussion I think we can close this.
