### ISSUE TITLE
Zip big json

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-pse#352]
We should probably consider zipping large json files that come from serializing models.  For example this one https://github.com/IDAES/idaes-pse/blob/main/idaes/power_generation/flowsheets/NGFC/NGFC_flowsheet_init.json, is 61 Mb.  Just adding ".gz" on the end of the file name in ``to_json()`` and ``from_json()``, should zip it.

**Comment by andrewlee94** [comment]
Looking at this a bit more, I note that this file (or something very similar) is duplicated in the tests as well. WE should use the same object both the reduce size, and to make sure the file in the repo is correct.
