### ISSUE TITLE
Documentation "latest" and "master" versions

### ISSUE THREAD

**Issue by TimBartholomew** [IDAES/idaes-pse#36]
It would be nice if users could access the most recent documentation. Currently, when I click on "master" and "latest" versions on https://idaes-pse.readthedocs.io/ it states that those pages don't exist.

**Comment by andrewlee94** [comment]
Whilst this hasn't been an issue yet, this might be useful for the "Advanced User" who wants to make use of some of our more recent changes to iDAES (or even just follow the development progress).

**Comment by dangunter** [comment]
Probably the same for examples-dev; given cross-linking between the two.

**Comment by ksbeattie** [comment]
I just checked and all of those links for for me.  "[master](https://idaes-pse.readthedocs.io/en/master/)" is new, but "[latest](https://idaes-pse.readthedocs.io/en/latest/)", "[stable](https://idaes-pse.readthedocs.io/en/stable/)" and the version specific ones have been there working for quite a while.

Can you double check?  I'm guessing this was a RTD hiccup or some such.

If you still find they don't work can you paste here the links that you are using?
