### ISSUE TITLE
Expanding Property Packages

### ISSUE THREAD

**Issue by dimi3saad** [IDAES/idaes-pse#372]
Hello!

I have been trying to develop my own property package (cubic EoS). I initially began following the IDAES documentation, only to find that a lot of it is very close to the generic BT one available. Therefore, I opted to modify the already existing BT one to include my components of interest (CO2, H2, etc.). I thus gathered all the required parameters for these species.

Initially I had errors with allowing CO2 and H2 to exist in anything other than the vapor phase. When I removed this, the error changed, and now the final error statement goes like:
_ValueError: math domain error_

I have a few questions:
1- Is modifying the generic property package a good idea, or is there a better way?
2- What could this error mean?

Thanks in advance for your help. I am willing and ready to share with you the files I am using.

**Comment by andrewlee94** [comment]
Hi @dimi3saad, a `math domain error` indicates that there is an issue evaluating on of the numerical expression in the model, such as a very large number or a division by zero. Given what you said above, my guess is that you tried to make CO2 or H2 a component in both phases and that the vapour pressure of those components is causing the problem. At the temperatures and pressures of interest for a benzene-toluene system, CO2 bad H2 are both supercritical and cannot be modeled using Raoults' Law - this is why they were set as vapour phase only components.

If you want to model dissolution of thee species in the liquid phase, you would need to use Henry's Law instead. However, the existing property package do not support Henry's Law yet, so you would need to custom code this yourself for now (we are looking at adding Henry's Law to the generic property framework in the upcoming month).

If you do chose to write your own property package, I would suggest not starting with the generic framework - there is far to much complexity in there to make it easy to modify. Instead, you could look at the older Cubic EoS model (https://github.com/IDAES/idaes-pse/tree/main/idaes/generic_models/properties/cubic_eos) as a starting point.

**Comment by andrewlee94** [comment]
We would need more information on the code and actual error to give you anything more specific. Given that this is a math domain error and not a solver error, it implies that this is occurring during evaluation of an expression during code execution. This could theoretically happen for any expression, so there is no way to narrow it down without more information.

Could you provide us with the full stack trace for the error message, as well as the files you are using?

**Comment by dimi3saad** [comment]
Definitely. I have attached the files here in a ZIP file. The first is the actual property package code, which should be put in the cubic EoS folder on your PC. The 2nd is the one I was running, which is a modified version of the heater example.

Thank you so much. Please let me know if you need anything else.
[CO2_propertypackage.zip](https://github.com/IDAES/idaes-pse/files/6585753/CO2_propertypackage.zip)
