### ISSUE TITLE
Question about Power generation unit model

### ISSUE THREAD

**Issue by sk2blue** [IDAES/idaes-pse#38]
Hi,

I currently try to modify example power generation steam cycle model to suit our USC power generation system.
First attachment is our scheme and is aimed to produce 2MW power.
So, I used example model (600 MW) to downsize but faced problem when I reduce the Cv value.
To meet our power capacity(2MW), inlet steam should be decreased but it results error even if I slightly modify Cv. Also, if I adjust valve opening, it results same error.
Could you please advise on this issue? One attachment is our scheme and another is ongoing py file(zipped).

[2MW USC steam turbine.pdf](https://github.com/IDAES/idaes-pse/files/5039480/2MW.USC.steam.turbine.pdf)
[supercritical_steam_cycle.zip](https://github.com/IDAES/idaes-pse/files/5039483/supercritical_steam_cycle.zip)

**Comment by jghouse88** [comment]
@eslickj Can you take a look at this?

**Comment by eslickj** [comment]
@sk2blue.  It's pretty hard to figure the correct flow coefficients for the turbine.  There is a new feature that I think isn't quite released that calculates the turbine flow coefficients during initialization based on your specified flow.  The new version of the power plant flowsheet you started from uses it.

I think the easiest thing to do is the grab the latest version of IDAES from idaes-pse repository so you can get the updated flowsheet.  I'm not quite sure if idaes-pse repo is up-to-date enough, but we have a developer meeting today.  I should be able to get back to you today on when and how to get an updated version.

**Comment by ksbeattie** [comment]
@sk2blue, you should be able to get our latest development version now.  The steps for using a development version is different from installing normally.  It is described, in details in the [Developer Documentation](https://idaes-pse.readthedocs.io/en/stable/advanced_user_guide/developer/devsw.html) section of our docs.  A quick (but possibly incomplete) list of commands is something like the following:

```
conda create --name idaes-pse-master python=3.7   # Assumes you have Mini/Anaconda installed
conda activate idaes-pse-master
git clone git@github.com:IDAES/idaes-pse.git
cd idaes-pse
pip install .
```
From there, in the idaes-pse-master conda env, you should get the dev version, just cloned.

**Comment by eslickj** [comment]
@sky2blue, I think I may have been mistaken about using the initialization method to calculate flow coefficients in the example.  I'm working on documentation updates now.  In the mean time, if you start with the new supercritical plant example, you can add the the calculate\_cf arguments  to the initialization for the turbine.  I don't know exactly how the model is set up but it should look something like:

```python
        m.fs.turb.initialize(
            outlvl=outlvl,
            optarg=solver.options,
            calculate_outlet_cf=True,
            calculate_inlet_cf=True)
```

Let me know if you have any trouble.  Another thing to consider is your inlet pressure.  Your pressure ratios outside the inlet and outlet stages still need to make sense when you look at the inlet and outlet pressure and the number of stages you have.

**Comment by sk2blue** [comment]
@ksbeattie Thanks to your advise, I have installed latest version of IDAES (1.6.3) successfully. However, I have still have a problem with downsizing of the steam cycle from your scale (i.e. about 600MW) to our scale (i.e. about 2MW).

@eslickj 
As per your advise, I have tried to add the options of 'calculate_outlet_cf=True' and 'calculate_inlet_cf=True' but it shows some error. Should I release some value in steam valve or in this model?!

Aside from that, I have tried following actions to reduce the steam flowrate to the turbine.

1. First trial is adjusting the value of 'throlle_cv_fix' and 'valve_opening.fix'. But downsizing of this value caused error. I assumed it is due to initialization so tried to adjust the initialization value in the steam valve model but still shows same problem.

2. Second trial is to reduce 'm.fs.turb.inlet_split.inlet.flow_mol[:].value'. Down to some value (e.g. from 20000 to 200) simulation running is okay but the flowrate is not really significantly reduced as I want. 

3. Because above trials does not solve the problem, I looked into the steam valve model. There are some values to be adjusted, maybe Cv and flow_scale. Because adjustment of Cv does not solve the problem, I have adjusted flow_scale but still cannot reduce the steam flowrate significantly.

My first target is reducing the steam flowrate down to the flowrate in the attached flowsheet. Then, will adjust other variables to match the operating conditions of turbines.

Could you please look at it and advise?! 




[supercritical_steam_cycle (1).zip](https://github.com/IDAES/idaes-pse/files/5116607/supercritical_steam_cycle.1.zip)
[2MW.USC.steam.turbine (1).pdf](https://github.com/IDAES/idaes-pse/files/5116609/2MW.USC.steam.turbine.1.pdf)

**Comment by eslickj** [comment]
@sk2blue, I don't really think the valve model should have much to do with your problem.  For a smaller process it should be smaller, but it doesn't really affect things much.  If your valve coefficient is way too high, that will mostly just mean that to reduce the steam flow that valve opening will have to be really small.  It's definitely the turbine flow coefficients you want to look at first.

**Comment by eslickj** [comment]
@sk2blue, I took a look at your file, and you have to many degrees of freedom, so I think when you reduced the flowsheet to just the turbine, you probably needed to fix some more variables.  I didn't look to close.  If you want to start out with just the turbine, check out the multistage turbine unit tests as a place to start.  One of the tests uses the new calculate flow coefficient initialization.  https://github.com/IDAES/idaes-pse/blob/master/idaes/power_generation/unit_models/helm/tests/test_turbine_multistage.py

Let's start from there.  Let me know if you have trouble.

**Comment by sk2blue** [comment]
@eslickj 
Thanks to your previous advise, it is successfully scale down around 2MW power generation by adjusting cf factors.
As a next step, we need to exactly match the flowrate as our data, we are utilizing 'parmest'.
But, we faced unclear error such as 'AttributeError: 'function' object has no attribute 'ctype'', so could you please advise on this?!
I have attached zip file including our latest py and csv data files as well as our flowsheet with data.

[supercritical_steam_cycle_200929.zip](https://github.com/IDAES/idaes-pse/files/5295774/supercritical_steam_cycle_200929.zip)

**Comment by eslickj** [comment]
The flow coefficient variables are there m.fs.turb.outlet_stage.flow_coeff.  The flow is mostly controlled by the outlet stage flow coefficient.  You can unfix the flow coefficient and add an objective function to try to match flow.  Another possibility is to simply unfix the flow coefficient and fix flow.

**Comment by jghouse88** [comment]
@sk2blue Can this issue be closed?

**Comment by sk2blue** [comment]
@jghouse88 @eslickj 
Yes, Thanks to your advise, everything is solved so far. I will close this issue.
