### ISSUE TITLE
Add model disagnostic tools section in our docs?

### ISSUE THREAD

**Issue by jghouse88** [IDAES/idaes-pse#380]
Just coming off from a very nice presentation from @Robbybp on different diagnostic tools available within Pyomo/IDAES for DAE systems. I think we need a dedicated page on our docs to have information for the different diagnostic tools we have access to. I feel all of us as developers use different diagnostic tools but they are only available to folks who know what they are looking for. 

Do we have a page for this in our docs now? I couldn't find it. We really need to update the docs again.

**Comment by andrewlee94** [comment]
This is somewhat peripherally related, but @dangunter and I have been discussing ways to better organise our docs which would try to make it easier to find content. This will be coming up in one of the developer meetings before long.

**Comment by andrewlee94** [comment]
A basic version of this has been added, and will be expanded in 2023 scope.
