### ISSUE TITLE
Perform link checking in (generated) documentation

### ISSUE THREAD

**Issue by dangunter** [IDAES/idaes-pse#389]
The documentation cross-links and links to external targets enough now that it would be useful to automate the process of looking for broken links. There are a number of tools that does this. One that looks promising is: https://github.com/wjdp/htmltest , which emulates the features of a popular Ruby link-checker but is written in Go so it is several times faster.

**Comment by ksbeattie** [comment]
Related to https://github.com/IDAES/examples-pse/pull/75

**Comment by ksbeattie** [comment]
This is partially complete, we believe.
