### ISSUE TITLE
State with Vapour and Liquid phase fails at lower pressure

### ISSUE THREAD

**Issue by venumadhavgangur** [IDAES/idaes-pse#39]
Hello Team,
While we were verifying the working of IDAES, we were testing without any units but just trying to get the cubic roots for certain composition. 
The state consists of both the states viz Liquid and Vapor and we were testing it for methane, ethane and propane.
The inlet pressure was set at 0.1MPa (i.e. 0.1e6) and temp at 233.15

But runs without any error with pressure 0.1e7 (or 1001325).

Since valid phase we are providing as Vap and Liq, we expect system would calculate it and provide right output even at lower pressure.

When we ran, it was notices that the code exited with below error.

****************************************ERROR BEGINS********************************************************
2020-08-20 13:41:46 [INFO] idaes.init.fs.state: Starting initialization
Traceback (most recent call last):

  File "<ipython-input-4-7fbabca9519b>", line 1, in <module>
    runfile('<file_path>/<file_name>.py', wdir='<file_path>')

  File "<file_path>\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "<file_path>\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "<file_path>/<file_name>.py", line 48, in <module>
    m.fs.state.initialize(outlvl=0)

  File "<file_path>\lib\site-packages\idaes\generic_models\properties\cubic_eos\cubic_prop_pack.py", line 416, in initialize
    res = solve_indexed_blocks(opt, [blk], tee=slc.tee)

  File "<file_path>\lib\site-packages\idaes\core\util\initialization.py", line 206, in solve_indexed_blocks
    results = solver.solve(tmp, **kwds)

  File "<file_path>\lib\site-packages\pyomo\opt\base\solvers.py", line 633, in solve
    default_variable_value=self._default_variable_value)

  File "<file_path>\lib\site-packages\pyomo\core\base\PyomoModel.py", line 242, in load_from
    % str(results.solver.status))

ValueError: Cannot load a SolverResults object with bad status: error
  File "<filepath>\lib\site-packages\idaes\generic_models\properties\cubic_eos\cubic_prop_pack.py", line 420, in initialize
    res = solve_indexed_blocks(opt, [blk], tee=slc.tee)

  File "<file_path>\lib\site-packages\idaes\core\util\initialization.py", line 206, in solve_indexed_blocks
    results = solver.solve(tmp, **kwds)

  File "<file_path>\lib\site-packages\pyomo\opt\base\solvers.py", line 633, in solve
    default_variable_value=self._default_variable_value)

  File "<file_path>\lib\site-packages\pyomo\core\base\PyomoModel.py", line 242, in load_from
    % str(results.solver.status))

[file_for_IDAES.txt](https://github.com/IDAES/idaes-pse/files/5102031/file_for_IDAES.txt)

[BT_PR_NewCase.txt](https://github.com/IDAES/idaes-pse/files/5102041/BT_PR_NewCase.txt)

ValueError: Cannot load a SolverResults object with bad status: error

****************************************ERROR ENDS********************************************************

During review of the code we think at lower pressure (1bar) the constraints are not getting satisfied. 

In the cubic_prop_pack.py;  need to clarify on the bubble point calculation of function bubble_temp_vap, while calculating 'am' the _mole_frac_tbub mole fraction is considered where as in the function `bubble_tem_liq `while calculating 'am' the mole_frac_comp is consdiered.

Curious to know if this is to calculate optimal values different variables of mole fractions are used?

Please suggest.

I am attaching the test file used for further reference. 

Please let us know if our observations are correct or there are any issue with our setup file. Kindly provide your findings.

**Comment by andrewlee94** [comment]
Hi @venumadhavgangur, thanks for reporting this.

Looking at what is happening, the initialization is not getting past the first step, so the main problem isn't even being solved yet. Something is going wrong in the calculation of the ideal bubble and dew points that is causing the solver to fail. I still do not know the cause however, but I am looking into it.

I did find one small error in the configuration file so far:
Line 59 needs to read `self.phase_equilibrium_idx = Set(initialize=[1, 2, 3])` as there are three phase equilibrium reactions that are occurring. However, this is not what is causing your problem.

Regarding your question about different mole fraction variables, this is because the values are being calculated at different states. At the bubble point, the liquid phase composition is equal to that of the total mixture (as there is essentially no vapour present), hence the use of `mole_frac_comp`, whilst the vapour phase has a different composition which needs to be calculated (`mole_frac_comp_tbub`). The opposite is true at the dew point.

**Comment by venumadhavgangur** [comment]
Thanks Andrew for your reply. Will wait to hear further on the fix.

**Comment by andrewlee94** [comment]
@venumadhavgangur I found the bug - the calculation of the initial guess for mole fractions at the bubble point was wrong. I will add a fix to the main code, but to get you working in the mean time, do the follwoing:

1. Open the file `idaes/generic_models/properties/cubic_eos/cubic_prop_pack.py`
2. Go to line 331 and replace the if statement with the following (note that it reverses the positions of pressure and antoine_P):

```
for j in blk[k].params.component_list:
                    blk[k]._mole_frac_tbub[j].value = value(
                            blk[k].mole_frac_comp[j] *
                            antoine_P(blk[k], j, Tbub0) /
                            blk[k].pressure)
```

That at least gets the model running for me, although I have not checked the final results.

**Comment by venumadhavgangur** [comment]
Thanks Andrew this is great. I will check this out.

Also I found another issue regards to FLASH unit. Shall I be creating new bug or add the details here? Please suggest.

Thanks,
Venu

**Comment by jghouse88** [comment]
@venumadhavgangur suggest adding a separate issue. Thanks.
