### ISSUE TITLE
Modeling of Turbine with FlueGasParameterBlock

### ISSUE THREAD

**Issue by aspitarl** [IDAES/idaes-pse#40]
Hi, I am trying to model a turbine powered with combustion gasses using FlueGasParameterBlock for the working fluid. I am able to do this fine with the water/steam property model, but I get an PropertyNotSupportedError when using FlueGasParameterBlock. Here is a script to reproduce the error 

```
from pyomo.environ import ConcreteModel
from idaes.core import FlowsheetBlock
from idaes.generic_models.unit_models import Turbine
from idaes.power_generation.properties import FlueGasParameterBlock

m = ConcreteModel()
m.fs = FlowsheetBlock(default={"dynamic": False}) # dynamic or ss flowsheet needs to be specified here
m.fs.properties = FlueGasParameterBlock()

#Causes error 
m.fs.turbine = Turbine(default={"property_package": m.fs.properties})
```

Which raises the error
```
PropertyNotSupportedError: fs.turbine.properties_isentropic[0.0] package property metadata method does not contain a method for entr_mol. Please select a package which supports the necessary properties for your process.
```

I think this may be due to the fact that the flue gas property model uses 'entropy' instead of 'entr_mol' even though both refer to entropy per mol, see [this line](https://github.com/IDAES/idaes-pse/blob/461c20ef8217d0210580aa498bac9aa7bcfd4ebc/idaes/power_generation/properties/flue_gas_ideal.py#L262)

Is there something I'm missing about how to do something like this? In general the property model system in IDAES seems very powerful but a bit overwhelming if I wanted to just try different simple gasses. Perhaps there could be some interface to make standard property packages from [CoopProp](http://www.coolprop.org/) data? This is what a similar packages to IDAES, [TESpy](https://tespy.readthedocs.io/en/master/), uses and in that package I am able to just declare 'air', 'co2', 'ar' as the working fluid, though with perhaps less flexibility. Please let me know if I'm missing something basic, I'm new to this kind of modeling.

**Comment by andrewlee94** [comment]
Hi @aspitarl, thank you for posting this issue.

The cause of the immediate error is the non-standard name for entropy used in the flue gas property package - it should ineed be named `entr_mol` by the standard convention. This is just a case of the developer not following the standards, and I will follow up with them to get it fixed.

As for a standard interface, we do have one but it is still in the relatively early stages of development - it works, but there it probably needs polishing.

Documentations: https://idaes-pse.readthedocs.io/en/stable/user_guide/components/property_package/general/index.html#generic-property-package-framework

Some examples: https://github.com/IDAES/idaes-dev/tree/master/idaes/generic_models/properties/core/examples

**Comment by aspitarl** [comment]
Great, thanks for the reply. Makes sense. 

Adding the functionality of being able to generate standard property packages from some standard library like CoolProp sounds like an idea to consider while the standard interface is in development. If that idea is feasible, perhaps that would be a good separate issue with the feature request tag.

**Comment by eslickj** [comment]
I'm going to overhaul the flue gas properties and bring it up to the standards.  Unfortunately this may cause some breakage in some power plant models depending on who has been using these.  I'll at least make sure we get all the IDAES models updated.  There is also an inconsistency in molecular weight https://github.com/IDAES/idaes-dev/issues/1065.

**Comment by andrewlee94** [comment]
I believe this was fixed at some point.
