### ISSUE TITLE
Typing error in PySMO

### ISSUE THREAD

**Issue by GranjalCruz** [IDAES/idaes-pse#401]
Hello,

I found a typo in the following link example:

https://lbl-idaes-dev.readthedocs-hosted.com/en/1.5.1/surrogate/pysmo/pysmo_sampling_properties.html#sampling-details

When you are importing the module, you import as **idaes.surrogates** instead of **idaes.surrogate**.

Took me some time to check if I had the my env setup correctly and was actually a problem with conda. It is a easy fix so I thought I should mention it ! 
Keep up the good work ! :)

**Comment by OOAmusat** [comment]
@GranjalCruz , thanks for catching the typo. A pull request is (#406) up to fix the typo.
