### ISSUE TITLE
Plotting Utils?

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-pse#405]
A long time ago (two or three years?) we discussed utilities plotting indexed variables.  Now I'm working on a model that's 2D and dynamic, and I was just thinking how nice it would be to have some generic plotting functions.  Did we ever create those plotting utilities or even start on them?  I was thinking about writing some, but I don't want to reinvent anything, and if we did start, I should probably pick up where we left off.

**Comment by andrewlee94** [comment]
I think someone started them, but I have no idea where they went.

**Comment by eslickj** [comment]
Yeah, I feel like there may be something that we abandoned due to disuse, but I can quite remember and don't know where to look.

**Comment by andrewlee94** [comment]
I think I found the old tools: https://github.com/IDAES/idaes-private/tree/master/idaes/vis

However, this is going back a long time, and uses bokeh as a dependency.

**Comment by eslickj** [comment]
Thanks.  I'll take a look.  Sounds like no one will mind if start something new.
