### ISSUE TITLE
Property Integrator Example Shows Error Message

### ISSUE THREAD

**Issue by sodanetworks** [IDAES/idaes-pse#41]
I ran the property integrator example listed on the IDAES docs: 

https://idaes-pse.readthedocs.io/en/stable/technical_specs/model_libraries/generic/property_models/interrogator.html

I installed IDAES on a mac computer. The error message is the following:

2020-08-21 19:21:06 [WARNING] idaes.core.flowsheet_model: DEPRECATED: No units were specified for the time domain. Users should provide units via the time_units configuration argument.

**Comment by andrewlee94** [comment]
Hi @sodanetworks, yes it is just a warning. We are in the process of adding support for units of measurement into the IDAES framework, which means that there are places where users will be required to define units of measurement in the future. 

We are trying to maintain backwards compatibility wherever possible, but these warnings are to let users know about these changes in advance.
