### ISSUE TITLE
Finish new IDAES website

### ISSUE THREAD

**Issue by dangunter** [IDAES/idaes-pse#425]
https://idaes.org/

**Comment by jghouse88** [comment]
@jghouse88 

- [ ] A-Z update for NETL
- [ ] Leadership tasks/sub-tasks association
- [ ] Research areas page

@ksbeattie 

- [ ] Stakeholders page; intro from John Shinn on Box (https://app.box.com/notes/824734996533)
- [ ] Update upcoming meeting info under SAB Meetings and under "News and Events"
- [ ] Software development info; update software page
- [ ] Reviewing language on contact us/support/pointing to GitHub discussions page

@dangunter 
- [ ] Update bios from notes in box note; https://app.box.com/folder/139667729998
