### ISSUE TITLE
Grid Integration: double-loop generalization

### ISSUE THREAD

**Issue by xiangao1** [IDAES/idaes-pse#432]
Timeline:

07/23/2021

- [x] Finish generalization of MIP model objects
- [x] Add documentation
- [x] Ask @adowling2  for review

07/30/2021

- [x] MILP with and without energy storage running
- [x] Add documentation
- [x] Ask @jsiirola  and @Robbybp  for review 

08/06/2021

- [x] Rankine cycle model from Jaffer running

08/13/2021

- [ ] Finish documentation
- [ ] PR under review

08/20/2021

- [ ] Reply to all reviews
- [ ] Last chance for input

08/23/2021

- [ ] Merge PR

Future enhancements:

- Advance time

**Comment by lbianchi-lbl** [comment]
@xiangao1 we're looking at open PRs in preparation for the August release. Is this work expected to be completed in the next few days? Otherwise, we can keep tracking this PR as part of the November release.

**Comment by xiangao1** [comment]
@lbianchi-lbl I don't think this will be finished in the next few days.

**Comment by lbianchi-lbl** [comment]
@xiangao1 thanks for the update---we just wanted to make sure we're not moving PRs without their authors' knowledge.

**Comment by xiangao1** [comment]
@lbianchi-lbl Sorry, but I think I should ask @adowling2 first. 

Alex, do you think we should target the August release?

**Comment by adowling2** [comment]
November release is best.

**Comment by ksbeattie** [comment]
@adowling2, @xiangao1 is this still possible for the Nov release?  As in within the next week?

**Comment by adowling2** [comment]
No, but release after Nov.

**Comment by adowling2** [comment]
@darrylmelander you mentioned today the option to create a Prescient plug-in in memory instead of writing to a file. Can you provide @xiangao1 with an example link here?
