### ISSUE TITLE
Display units of measurement in model outputs

### ISSUE THREAD

**Issue by andrewlee94** [IDAES/idaes-pse#44]
Now that IDAES models support explicit declaration of units of measurement on all components, we should update our reporting methods to include these in the report outputs and include the ability for users to provide a set of preferred units of measurement for the output results. However, we don't want to have to force users to declare preferred units unless they want to, so we need to have a fall back for these cases.

For single values this is straight forward: check to see if the user has provided a preferred set of unit. If they have, convert the value and print the result followed by the preferred units, otherwise take the value as is and print the declared units of the component. Pyomo will probably want to implement the underlying methods for this, as this is general to any Pyomo model using units, and we can just use this method in our reporting functions.

However, this becomes more complicated for aggregate outputs such as stream tables as now we have multiple use-cases to consider. Ideally, the user would declare a set of preferred units for their table and all values in the streams would have units, so we could just put a summary of units in the row headers and convert all the values to the desired units and be done. However, we need to consider the following:

1. Flowsheets can have multiple property packages which use different units. If a user does not declare a set of preferred units, we have to take the values as they are, but how do we report units? We cannot just use the row headers anymore as there is no guarantee of consistent units, so do we need to put units on each value (this would get crowded fast)? Also how do we determine when we can put units in the row header and when we can't?
2. What happens in a property package doesn't include units but user specified a set of units to use? Convert methods will now fail due to incompatible units, so do we just raise the exception and tell users to give the properties units, or do we just report the value as is and somehow flag units as undefined?

We would also need to define an API for specifying the preferred units for a flowsheet. As this is a user-output level, I think we need to provide the ability to specify units by quantity, rather than just the 5 base quantities - e.g. users need to be able to say report enthalpies in kJ/kmol and entropies in BTU/lb.R. We could provide pre-defined output units sets (maybe via the DMF) that provide a basis that users could modify if desired.

**Comment by andrewlee94** [comment]
1. The easy approach to this would be to insist users define their preferred output units, and to provide a simple interface for this with some default unit sets. Then, we don't have to worry about any of these complications.
2. I think in this case we go with the all-or-nothing approach to units. If you gave units for the output but your model doesn't have units, you need to go fix your model (or not ask for specific units in the output).

**Comment by eslickj** [comment]
Pint has a thing that lets you specify a system of units.  I think we could expand on that.  We could also use something like the Pyomo value function.  This is probably full of holes but just to start a discussion with something concrete to take apart...

Let's say m.x is a variable with units of meters

```python

> with_units(m.x)

returns: "10 m"

> with_units(m.x, to="cm")

returns: "1000 cm"

> with_units(m.x, system="cgs")

returns: "1000 cm"
```

That's the basics. If that's okay, we can have the function check up the block hierarchy for a defined system of display units.  We could also have display units be an IDAES config option.  If there are no units on a number that's fine would just not show any units.

**Comment by andrewlee94** [comment]
@eslickj I like the idea of specifying a system of units, but the challenge would be working out what the units of the component correspond to in the system. I.e. given a list of output units in the system definition, how do I work out which of those is consistent with the unit of my `Var` given only the units of the `Var`. We could do an iterative search, but that is hardly efficient and we could run into issues multiple matches (e.g. multiple quantities with consistent units, but different desired output units).

**Comment by andrewlee94** [comment]
Seeing as we have a milestone coming up for this, I have put together an idea for a function that will take a Pyomo component and a definition of a system of units and return a value. This depends on the proposed changes to how Pyomo handles units in the `value` method, and is based on the assumption that `value` returns an expression of the form `float*units`.

First, unit definitions would take the form of a `dict` where the keys are quantities of interest and values are the desired output units. E.g.:

```
units_system = {
    "temperature": pyunits.degC,
    "pressure": pyunits.MPa,
    "heat": pyunits.BTU/pyunits.hr}
```

The following function could then take a Pyomo component and a unit definition and convert the value of most quantities to the desired output (assuming standard names).

```
convert_output_units(component_data, unit_system=None):

    v = value(component_data)

    # Check for dimensionless quantities upfront
    if (get_units(component_data) == pyunits.dimensionless or get_units(component_data) is None):
        return v

    if unit_system is None:
        # Let users define a global default set of units
        unit_system = idaes.default_units

    q_name = component_data.parent_component().local_name

    # Remove phase and component qualifiers from q_name
    # For anything using the naming standards, this should be a standard name
    if q_name.endswith("_comp"):
        q_name = q_name[:-5]  # Python 3.9 has an inbuilt tool for this
    if q_name.endswith("_phase"):
        q_name = q_name[:-6]  # Python 3.9 has an inbuilt tool for this
    # Need to catch some common variations (mostly unit level)
    # Need to be careful here that we don't confuse specific quantities with absolute
    if q_name.startswith("work"):
        q_name = "work"
    elif q_name_startswith("Heat"):
        q_name = "heat"

    if q_name in unit_system:
        # Quantity defined in users unit system
        try:
            return convert(v, to_units=unit_system[q_name])
        except UnitCoversionError:
            # User defined units did not match units of quantity
            raise UnitConversionError("Add a descriptive message here")
    else:
        # Don't know how to convert quantity
        logger.debug("Couldn't work out how to convert quantity {}".format(component.local_name))
        return v
```

**Comment by eslickj** [comment]
@andrewlee94, I think this look pretty good.  It solves a major issue with not knowing what to make of derived units.  It would be nice if we could add a component quantity type label attribute rather than depending on naming.  Something like (probably not working code):

```python

class QtyUnitType(Enum):
    PRESSURE = 1,
    HEAT = 2,
    WORK = 3,
    VISCOSITY = 4
    ...

   m.v = Var([1,2,3])
   m.v.unit_type = QtyUnitType.PRESSURE
   ...
   if v[1].parent_component().unit_type:
      ...

```

**Comment by andrewlee94** [comment]
@eslickj The only problem I see with that approach is that it would mean having to add those quantity type to everything, which would be a lot of work (especially for user-developers). That and the potentially large number of unit types we have to deal with (energy, molar specific energy, mass specific energy, etc).

That said, it would be nice and unambiguous, and name could still be used as a fall back (or a way of not having to define a type for things with standard names).

Actually, now I think about it, that would be the easy way to handle unit level variables with non-standard names (e.g. work_mechanical` or `heat_duty`). That would limit the scope of components we need to add quantity definitions too and the number of different quantity types we would need to look for, and lets us get around trying to guess the correct set of units in those cases. Property packages on the other hand need to be standardized, so we can just rely on name there.

**Comment by jsiirola** [comment]
So, I really want `value(m.x)` to return a pint `Quantity` (i.e., magnitude + units) if `m.x` is defined with units.  The idea would be for the units to be the units of the object, so you wouldn't need to specify a system of units for I/O - you would get it automatically (eventually, from the property package).  Then, if you want a different set of units, you can use standard `pint` utilities.

Because IDAES / Pyomo require that expressions be unit consistent (i.e., no implicit conversions), the same logic will hold for `value(m.e)` where `m.e` is an expression.

**Comment by eslickj** [comment]
Yeah the combined, name/attribute approach should work.  I guess since it's just a display thing, it's not highly critical that everything be property labeled.  

I don't know what support core Pyomo may want to add, but a consideration may be that it should be possible to infer the quantity type by the unit assignments.  Like if I say viscosity has units of Pa*s, I should be able to infer that I want to report it in Pressure*time.  My experience with Pint is that it converts things to base units when you convert. We may be able to do something more automatic in assigning the quantity type.

**Comment by carldlaird** [comment]
A couple of comments:
1. I think pint already has the quantity type built in.
2. If value() returns a pint expression, then we are committing to pint. The current implementation allows Pyomo to change how it is using units under the hood. If we decide to expose pint, then I expect there is lots of code that can be deleted.

**Comment by jsiirola** [comment]
While I am thinking of this, if you want to allow a user to specify a units system for reporting, why not just list the desired units in a list:
```python
units_system = [
    pyunits.degC,
    pyunits.MPa,
    pyunits.BTU/pyunits.hr},
]
```
then when you go to output it, you check to see which unit he units from the expression are "convertable to", do the conversion, and print the result.  For efficiency, you could build a map from the (string representation of the?) units that you have seen to the conversion factor -- that way you would only have to do the "search" once.  It seems a little convoluted, but it would the eliminate the need to key off "known component names".

**Comment by andrewlee94** [comment]
@jsiirola One reason for linking quantity to units was to allow for two quantities with the same base units (i.e. equivalent units) to have different reporting units if desired (e.g. concentration and density). I am not sure how often this would be useful, but I am fairly certain there are cases where that could be useful.

**Comment by eslickj** [comment]
Well if Pint has a quantity type built in maybe we should look more into that.  As I mentioned in the past converting pressure for example was frustrating because it would report in something like kg/s^2/m or whatever it is, although, I admittedly haven't really seen how things behave.  If we could key Pints quantity type to Andrew's dict, it would eliminate the need for name checking maybe.

**Comment by andrewlee94** [comment]
In the end, I think all of this depends heavily on how Pyomo choses to handle the value of unitted components. I.e. if Pyomo goes with `pint`, then a lot of what we need is already there for us (e.g. systems of units) and we don't actually need to do much. Much of my thinking so far was based around having to do most of the work ourselves.

So, we probably should hold off on doing too much here until that is resolved.

**Comment by andrewlee94** [comment]
As much for my own reference as any, one case where we might want the same basic quantity to be displayed with different units in different situations is energy. For power generation, heat is often reported in BTUs, work in kW.hr, and other thermodynamic quantities in some variant of J.
