### ISSUE TITLE
Drop support for Python 3.6?

### ISSUE THREAD

**Issue by dangunter** [IDAES/idaes-pse#444]
The last release of the Python 3.6 series was in December 2018. Some time in early 2022 security fixes will end. Is there any reason not to just drop it now? I happen to have just hit a place where 3.6 fails but more modern versions are fine, so I am being the squeaky wheel.

**Comment by eslickj** [comment]
I'm okay with it.

**Comment by lbianchi-lbl** [comment]
I, too, agree and gladly join the squeaky choir. As I understand from [this](https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table), numpy dropped support for 3.6 more than one year ago (Jun 2020).

**Comment by jsiirola** [comment]
FWIW, Pyomo's policy is to support a Python release through the first Pyomo release after the EOL date of the Python release (so Pyomo will likely drop 3.6 sometime in February).

That said, other IDAES dependencies / related packages have already dropped Python 3.6 (notably Egret/Prescient, and I think Coramin)

**Comment by andrewlee94** [comment]
I think we have hit other cases where we want to use features that are not supported by Python 3.6 (although I cannot remember what they are), so I have no objections to dropping support for 3.6.

**Comment by ksbeattie** [comment]
What does this actually mean in terms of actions?  This sounds like a job for a checklist!  I'll start one:

- [ ] Remove 3.6 from GitHub Actions and test
- [ ] Update documentation (sphinx & readmes)
- [ ] What else?

**Comment by ksbeattie** [comment]
Possibly add a deprecation warning when imported in 3.6 for the Nov release?

**Comment by ksbeattie** [comment]
Moving this to the Feb release for when 3.6 will be official removed from support.
