### ISSUE TITLE
Pytest fails on brand-new installation for Miniconda on Windows.

### ISSUE THREAD

**Issue by dallan-keylogic** [IDAES/idaes-pse#453]
I followed the [advanced user guide](https://idaes-pse.readthedocs.io/en/stable/advanced_user_guide/advanced_install/index.html#advanced-user-installation) to fork and install IDAES using Miniconda on Windows, and a single unit test is failing. 

![image](https://user-images.githubusercontent.com/88728506/129056587-ae5a453e-0a70-4598-ac81-c1ac0db4940b.png)

Note---before I found the advanced guide, I had begun installing it in the base environment using pip, before uninstalling it and creating a dedicated idaes dev environment. IDAES might have been uninstalled, but a lot of its dependencies may have stuck around. I assume that creating an environment should have isolated this installation from them, but perhaps I'm assuming wrong.

**Comment by lbianchi-lbl** [comment]
I've just checked and I can confirm we got rid of this test because of its flakiness, so this issue can be closed.
