### ISSUE TITLE
Fix deprecation warnings from Pyomo 6.1

### ISSUE THREAD

**Issue by andrewlee94** [IDAES/idaes-pse#469]
A change in Pyomo 6.1 results in a number of deprecation warnings that we should fix before our upcoming release.

The one known deprecation warning (so far) is:

WARNING: DEPRECATED: Using __getitem__ to return a set value from its (ordered) position is deprecated.  Please use card()  (deprecated in 6.1,  will be removed in 7.0) (called from c:\miniconda\envs\proteuslib-dev\lib\site-packages\idaes\generic_models\properties\core\state_definitions\FTPx.py:148)

The fix is easy - all cases where we reference a Pyomo Set with an index need to be replaced by `set.card(index)` (or `set.first()`, etc. if appropriate). The hard part however will be finding all cases where this appears.

**Comment by lbianchi-lbl** [comment]
@andrewlee94 I'm trying to reproduce the `Set.__getitem__()` deprecation messages while running the IDAES test suite, but it looks like they are not being generated. Do you have a minimal example where they are generated in IDAES?

This is the output of `pip show pyomo`:

```txt
Name: Pyomo
Version: 6.1.1
Summary: Pyomo: Python Optimization Modeling Objects
Home-page: http://pyomo.org
Author: None
Author-email: None
License: BSD
Location: /opt/conda/envs/idaes-469/lib/python3.8/site-packages
Requires: ply
Required-by: rbfopt, idaes-pse
```

**Comment by andrewlee94** [comment]
@lbianchi-lbl I do not have one on hand. This issue was brought to my attention by the NAWI team, as it is causing some of their tests to fail.
