### ISSUE TITLE
Problem visualizing a Flowsheet for a converged model: The UI shows a blank display area

### ISSUE THREAD

**Issue by elbashandy** [IDAES/idaes-pse#479]
User's comments on the issue:

- "trying to add the flowsheet visualizer to my model so I can see the results in a nice graphical format.  My model converges but the visual flowsheet doesn’t come up.  A web page is launched but the main display area is blank (see the following image)."

![image002](https://user-images.githubusercontent.com/1439632/130650765-7c9b023f-a992-49cb-90f3-91e504134d95.jpg)

- "This Python model contains a call to visualize from the ideas.ui.fsvis package.  If I replace that line with a call to the visualize method of the flowsheet object, the display generated in Chrome is even worse than the screenshot I sent with my original email (I just get the menu items as a combination of plain text and hyperlink text vertically along the left edge of the browser screen with no styling).  I tried using both IE and Edge as my browser for display instead of Chrome.  In both cases. the browser starts but immediately shuts down."

**Comment by ksbeattie** [comment]
Waiting for user to respond for more input.

**Comment by lbianchi-lbl** [comment]
@elbashandy followed up with the original reporter and this can now be considered addressed.
