### ISSUE TITLE
Pynumero Issue New Release

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-pse#500]
I just discovered that our pynumero binary is out of date for the new version of Pyomo.  I guess we probably new a new set of binaries to go with the newest IDAES release, or anything using pynumero will be broken.

**Comment by ksbeattie** [comment]
Yikes.  Let me know when you've updated idaes-ext.

Any way we can create a smoke test of some kind to give us a heads on this this sort of thing in the future?

**Comment by eslickj** [comment]
@ksbeattie, good question.  We do have a test to see if we have pynumero.  Maybe my version of Pyomo is too new.  I'll have to investigate this more, but maybe the release is fine.  Either way I guess we'll need the new binaries.  I'm building them.

**Comment by eslickj** [comment]
Well I don't know.  Our test for having pynumero passes, but when I try to use some scaling utils in my model I get an error that I need to update to pynumero 2.  Maybe only certain features trigger the warning?  I'll figure it out.

**Comment by eslickj** [comment]
Ok, I figured it out.  I was getting a warning, and got confused the real reason it was failing is that pynumero stopped working with external functions.  So we need to update Pynumero to avoid the warning, but there seems to be a new bug in Pyomo.  I'll report it over there.

```
WARNING: The current pynumero_ASL library is version=2, but found version=1.
    Please recompile / update your pynumero_ASL library.
function cbrt not available  <--- this is the real problem
```

**Comment by eslickj** [comment]
Reported Pyomo bug https://github.com/Pyomo/pyomo/issues/2126

**Comment by eslickj** [comment]
This whole thing was a mix-up on my part.  The IDAES binaries are fine.  I just had a old version that loaded before the IDAES version and I didn't realize it was there.
