### ISSUE TITLE
Running error with IDAES 1.7.0 new version

### ISSUE THREAD

**Issue by sk2blue** [IDAES/idaes-pse#52]
Hi,

I noticed that IDAES 1.7.0 new version is now available, while I am using previous 1.6.3 version.
I installed new one and tried to run the attached py file, but it is not working with some errors.
The main error message when I run it is as below.

AttributeError: 'SimplePort' object has no attribute 'flow_component'. It seems the model of heat exchanger modifed?!
Is there another way to set flow component?

[supercritical_steam_cycle_201109.zip](https://github.com/IDAES/idaes-pse/files/5515083/supercritical_steam_cycle_201109.zip)

**Comment by MAZamarripa** [comment]
variable name changed to `flow_mol_comp`
i.e. m.fs.unit.side_2_inlet.flow_mol_comp[0, "H2O"].fix(FGrate*8.69/100)
use test file as an example: 
https://github.com/IDAES/idaes-pse/blob/main/idaes/power_generation/unit_models/tests/test_boiler_heat_exchanger.py

**Comment by ksbeattie** [comment]
@sk2blue, I'm going to close this issue assuming @MAZamarripa's answer is ok for you.  If not, please feel free to reopen this issue.
