### ISSUE TITLE
Air separation example broken

### ISSUE THREAD

**Issue by andrewlee94** [IDAES/idaes-pse#557]
The air separation example in the examples-pse repo (https://github.com/IDAES/examples-pse/blob/main/src/Examples/Advanced/CustomProperties/air_separation_case_study.ipynb) was broken by PR #531. Specifically, it appears that the failure setting an upper bound on mole fractions of 1.001.

Some quick testing has revealed the following:

* a looser upper bound of 1.01 works, as does no upper bound.
* using `calculate_scaling_factors` without providing any additional scaling information caused the example to fail earlier
* all solves (even before these issues) were ending in restoration, indicating that the underlying model has issues.

Seeing as the example had solver issues even before this issue, I think the correct response here is to take a closer look at this problem and fix the underlying issues rather than just loosening the bounds applied to the mole fractions. As part of this, I would suggest we include proper use of the scaling tools in this example, as we need to show users how to apply them (and I suspect better scaling will resolve a number of the issues we are seeing).

**Comment by viiibhav** [comment]
I think I have got it to work. Scaling didn't help with the problem, but a smaller barrier parameter `mu_init` improves the performance and avoids restoration. I have updated the notebook locally and will open a PR for it.

**Comment by andrewlee94** [comment]
This was fixed in https://github.com/IDAES/examples-pse/pull/68
