### ISSUE TITLE
Interface to CoolProp

### ISSUE THREAD

**Issue by dangunter** [IDAES/idaes-pse#593]
Provide an appropriate IDAES interface to relevant parts of the CoolProp database

**Comment by dangunter** [comment]
e.g., for the property  vapour pressure (Psat), where Psat = A + B/(T+C) , use CoolProp to derive the A, B and C

**Comment by andrewlee94** [comment]
Some other low hanging fruit are the critical temperature, pressure and acentricity factor for components. I managed to find a set of json files which contained those for a long list of components easily.

**Comment by dangunter** [comment]
Is the acentricity factor calculable from Tc, Psat, and Pc?

**Comment by andrewlee94** [comment]
No, acentricty factor is normally a parameter in its own right (although its definition is based on measurements at a specific value of Tc and Pc).

**Comment by dallan-keylogic** [comment]
It would be good to create some batches of data from CoolProp to validate our implementation of some property package. In particular, they have a [cubic EoS implementation](http://www.coolprop.org/coolprop/Cubics.html) that we could use to generate data to check our own implementation against. Their website isn't the greatest (I know, those who live in glass houses...), but [I did find that it's available through pip and CondaForge](http://www.coolprop.org/coolprop/wrappers/Python/index.html). I doubt we want to make it a prerequisite for running tests, but generating some batches of data seems doable.

**Comment by andrewlee94** [comment]
@dallan-keylogic Actually, CoolProp is likely to be come at least a partial dependency for our tests by the end of the year. WE are separately looking at ways to load parameter data from CoolProp's database, so that will become past of our testing.

**Comment by andrewlee94** [comment]
Closing this as we now have such an interface.
