### ISSUE TITLE
Uncertainty Propagation Test Failures

### ISSUE THREAD

**Issue by bpaul4** [IDAES/idaes-pse#602]
The first two tests in idaes/apps/uncertainty_propagation/tests/test_uncertainty.py fail due to a Numpy TypeError. On lines 53 and 83, the code calls `np.testing.assert_array_almost_equal(results.theta, [19.142575284617866, 0.53109137696521])`, where `results.theta` is a dictionary list that is compared to a list of float objects. Replacing each line with `np.testing.assert_array_almost_equal(list(results.theta.values()), [19.142575284617866, 0.53109137696521])` solved the issues. I'd appreciate thoughts on the cause of these errors, since they did not occur when I locally ran the test suite last week.

============================================================================== FAILURES ===============================================================================
___________________________________________________ TestUncertaintyPropagation.test_quantify_propagate_uncertainty1 ___________________________________________________

self = <test_uncertainties.TestUncertaintyPropagation object at 0x0000024CAC6624C0>

    @pytest.mark.unit
    def test_quantify_propagate_uncertainty1(self):
        '''
        It tests the function quantify_propagate_uncertainty with rooney & biegler's model.
        '''
        from idaes.apps.uncertainty_propagation.examples.rooney_biegler import rooney_biegler_model,rooney_biegler_model_opt
        variable_name = ['asymptote', 'rate_constant']
        data = pd.DataFrame(data=[[1,8.3],[2,10.3],[3,19.0],
                                  [4,16.0],[5,15.6],[7,19.8]],
                            columns=['hour', 'y'])
        def SSE(model, data):
            expr = sum((data.y[i] - model.response_function[data.hour[i]])**2 for i in data.index)
            return expr

        results =  quantify_propagate_uncertainty(rooney_biegler_model,rooney_biegler_model_opt, data, variable_name, SSE)

        assert results.obj == approx(4.331711213656886)
>       np.testing.assert_array_almost_equal(results.theta, [19.142575284617866, 0.53109137696521])

test_uncertainties.py:53:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

x = array({'asymptote': 19.14257528461787, 'rate_constant': 0.5310913769652098},
      dtype=object), y = array([19.14257528,  0.53109138])

    def compare(x, y):
        try:
            if npany(gisinf(x)) or npany( gisinf(y)):
                xinfid = gisinf(x)
                yinfid = gisinf(y)
                if not (xinfid == yinfid).all():
                    return False
                # if one item, x and y is +- inf
                if x.size == y.size == 1:
                    return x == y
                x = x[~xinfid]
                y = y[~yinfid]
        except (TypeError, NotImplementedError):
            pass

        # make sure y is an inexact type to avoid abs(MIN_INT); will cause
        # casting of x later.
        dtype = result_type(y, 1.)
        y = array(y, dtype=dtype, copy=False, subok=True)
>       z = abs(x - y)
E       TypeError: unsupported operand type(s) for -: 'dict' and 'float'

c:\users\bpaul\miniconda3\lib\site-packages\numpy\testing\_private\utils.py:1035: TypeError
-------------------------------------------------------------------------- Captured log call --------------------------------------------------------------------------
WARNING  pyomo.contrib.pynumero.asl:asl.py:191 The current pynumero_ASL library is version=2, but found version=1.  Please recompile / update your pynumero_ASL library.
___________________________________________________ TestUncertaintyPropagation.test_quantify_propagate_uncertainty2 ___________________________________________________

self = <test_uncertainties.TestUncertaintyPropagation object at 0x0000024CAD392340>

    @pytest.mark.component
    def test_quantify_propagate_uncertainty2(self):
        '''
        This is the same test as test_quantify_propagate_uncertainty1,
        but with the second argument of quantify_propagate_uncertainty as Pyomo Concrete Model.
        '''
        from idaes.apps.uncertainty_propagation.examples.rooney_biegler import rooney_biegler_model
        variable_name = ['asymptote', 'rate_constant']
        data = pd.DataFrame(data=[[1,8.3],[2,10.3],[3,19.0],
                                  [4,16.0],[5,15.6],[7,19.8]],
                            columns=['hour', 'y'])
        def SSE(model, data):
            expr = sum((data.y[i] - model.response_function[data.hour[i]])**2 for i in data.index)
            return expr
        model_uncertain= ConcreteModel()
        model_uncertain.asymptote = Var(initialize = 15)
        model_uncertain.rate_constant = Var(initialize = 0.5)
        model_uncertain.obj = Objective(expr = model_uncertain.asymptote*( 1 - exp(-model_uncertain.rate_constant*10  )  ), sense=minimize)

        results =  quantify_propagate_uncertainty(rooney_biegler_model,model_uncertain, data, variable_name, SSE)

        assert results.obj == approx(4.331711213656886)
>       np.testing.assert_array_almost_equal(results.theta, [19.142575284617866, 0.53109137696521])

test_uncertainties.py:83:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

x = array({'asymptote': 19.14257528461787, 'rate_constant': 0.5310913769652098},
      dtype=object), y = array([19.14257528,  0.53109138])

    def compare(x, y):
        try:
            if npany(gisinf(x)) or npany( gisinf(y)):
                xinfid = gisinf(x)
                yinfid = gisinf(y)
                if not (xinfid == yinfid).all():
                    return False
                # if one item, x and y is +- inf
                if x.size == y.size == 1:
                    return x == y
                x = x[~xinfid]
                y = y[~yinfid]
        except (TypeError, NotImplementedError):
            pass

        # make sure y is an inexact type to avoid abs(MIN_INT); will cause
        # casting of x later.
        dtype = result_type(y, 1.)
        y = array(y, dtype=dtype, copy=False, subok=True)
>       z = abs(x - y)
E       TypeError: unsupported operand type(s) for -: 'dict' and 'float'

c:\users\bpaul\miniconda3\lib\site-packages\numpy\testing\_private\utils.py:1035: TypeError

 File "C:\Users\bpaul\AppData\Local\Temp/ipykernel_23396/731694044.py", line 1, in <module>
    np.testing.assert_array_almost_equal(results.theta.values(), [19.142575284617866, 0.53109137696521])

  File "c:\users\bpaul\miniconda3\lib\site-packages\numpy\testing\_private\utils.py", line 1042, in assert_array_almost_equal
    assert_array_compare(compare, x, y, err_msg=err_msg, verbose=verbose,

  File "c:\users\bpaul\miniconda3\lib\site-packages\numpy\testing\_private\utils.py", line 788, in assert_array_compare
    val = comparison(x, y)

  File "c:\users\bpaul\miniconda3\lib\site-packages\numpy\testing\_private\utils.py", line 1035, in compare
    z = abs(x - y)

TypeError: unsupported operand type(s) for -: 'dict_values' and 'float'

**Comment by lbianchi-lbl** [comment]
@bpaul4 could you run `pip list` in the same environment and post the output here? It's just a guess, but it looks like something that could be caused by an update in one of IDAES's dependencies.

**Comment by bpaul4** [comment]
Package                            Version             Location
---------------------------------- ------------------- -------------------------------
absl-py                            0.13.0
addheader                          0.2.3
alabaster                          0.7.12
appdirs                            1.4.4
argon2-cffi                        20.1.0
arrow                              1.1.1
astroid                            2.5.6
astunparse                         1.6.3
async-generator                    1.10
atomicwrites                       1.4.0
attrs                              21.2.0
autopep8                           1.5.7
Babel                              2.9.1
backcall                           0.2.0
backports.shutil-get-terminal-size 1.0.0
bcrypt                             3.2.0
binaryornot                        0.4.4
black                              21.7b0
bleach                             3.3.0
brotlipy                           0.7.0
bunch                              1.0.1
cachetools                         4.2.2
certifi                            2020.6.20
cffi                               1.14.3
chardet                            3.0.4
click                              7.1.2
cloudpickle                        1.6.0
colorama                           0.4.4
conda                              4.9.2
conda-package-handling             1.7.2
cookiecutter                       1.7.3
coverage                           5.5
cryptography                       3.2.1
cycler                             0.10.0
debugpy                            1.3.0
decorator                          4.4.2
defusedxml                         0.7.1
diff-match-patch                   20200713
docutils                           0.17.1
entrypoints                        0.3
et-xmlfile                         1.1.0
flake8                             3.9.2
Flask                              2.0.1
Flask-Cors                         3.0.10
flatbuffers                        1.12
fpdf2                              2.4.3
gast                               0.4.0
google-auth                        1.32.1
google-auth-oauthlib               0.4.4
google-pasta                       0.2.0
grpcio                             1.34.1
h5py                               3.1.0
idaes-examples                     1.11.0
idaes-pse                          1.12.0.dev0         c:\users\bpaul\github\idaes-pse
idna                               2.10
imagesize                          1.2.0
importlib-metadata                 4.6.4
inflection                         0.5.1
iniconfig                          1.1.1
intervaltree                       3.1.0
ipykernel                          6.0.1
ipython                            7.25.0
ipython-genutils                   0.2.0
ipywidgets                         7.6.3
isort                              5.9.1
itsdangerous                       2.0.1
jedi                               0.18.0
Jinja2                             3.0.1
jinja2-time                        0.2.0
joblib                             1.0.1
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     6.1.12
jupyter-console                    6.4.0
jupyter-contrib-core               0.3.3
jupyter-contrib-nbextensions       0.5.1
jupyter-core                       4.7.1
jupyter-highlight-selected-word    0.2.0
jupyter-latex-envs                 1.4.6
jupyter-nbextensions-configurator  0.4.1
jupyterlab-pygments                0.1.2
jupyterlab-widgets                 1.0.0
keras-nightly                      2.5.0.dev2021032900
Keras-Preprocessing                1.1.2
keyring                            23.1.0
kiwisolver                         1.3.1
lazy-object-proxy                  1.6.0
lxml                               4.6.3
Markdown                           3.3.4
MarkupSafe                         2.0.1
matplotlib                         3.4.2
matplotlib-inline                  0.1.2
mccabe                             0.6.1
menuinst                           1.4.16
mistune                            0.8.4
mpmath                             1.2.1
mypy-extensions                    0.4.3
nbclient                           0.5.3
nbconvert                          6.1.0
nbformat                           5.1.3
nest-asyncio                       1.5.1
networkx                           2.5.1
notebook                           6.4.0
numpy                              1.19.5
numpydoc                           1.1.0
oauthlib                           3.1.1
openpyxl                           3.0.7
opt-einsum                         3.3.0
packaging                          21.0
pandas                             1.3.0
pandocfilters                      1.4.3
paramiko                           2.7.2
parso                              0.8.2
pathspec                           0.9.0
pecos                              0.2.0
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             8.3.0
Pint                               0.17
pip                                20.2.4
pluggy                             0.13.1
ply                                3.11
pockets                            0.9.1
poyo                               0.5.0
prometheus-client                  0.11.0
prompt-toolkit                     3.0.19
protobuf                           3.17.3
psutil                             5.8.0
ptyprocess                         0.7.0
py                                 1.10.0
pyasn1                             0.4.8
pyasn1-modules                     0.2.8
pycodestyle                        2.7.0
pycosat                            0.6.3
pycparser                          2.20
pydocstyle                         6.1.1
pyflakes                           2.3.1
Pygments                           2.9.0
pylint                             2.8.3
pyls-spyder                        0.4.0
PyNaCl                             1.4.0
Pyomo                              6.1.3a0
pyOpenSSL                          19.1.0
pyparsing                          2.4.7
PyQt5                              5.12.3
PyQt5-sip                          12.9.0
PyQtWebEngine                      5.12.1
pyrsistent                         0.18.0
PySocks                            1.7.1
pytest                             6.2.4
pytest-cov                         2.12.1
python-dateutil                    2.8.1
python-lsp-black                   1.0.0
python-lsp-jsonrpc                 1.0.0
python-lsp-server                  1.2.1
python-slugify                     5.0.2
pytz                               2021.1
pywin32                            225
pywin32-ctypes                     0.2.0
pywinpty                           1.1.3
PyYAML                             5.4.1
pyzmq                              22.1.0
QDarkStyle                         3.0.2
qstylizer                          0.2.1
QtAwesome                          1.0.3
qtconsole                          5.1.1
QtPy                               1.9.0
rbfopt                             4.2.2
regex                              2021.8.3
requests                           2.24.0
requests-oauthlib                  1.3.0
rope                               0.19.0
rsa                                4.7.2
Rtree                              0.9.7
ruamel-yaml                        0.15.87
scikit-learn                       0.24.2
scipy                              1.7.0
Send2Trash                         1.7.1
setuptools                         50.3.1.post20201107
six                                1.15.0
sklearn                            0.0
snowballstemmer                    1.2.1
sortedcontainers                   2.4.0
Sphinx                             4.0.3
sphinx-argparse                    0.2.5
sphinx-rtd-theme                   0.5.2
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             2.0.0
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-napoleon             0.7
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.5
spyder                             5.1.1
spyder-kernels                     2.1.0
sympy                              1.8
tensorboard                        2.5.0
tensorboard-data-server            0.6.1
tensorboard-plugin-wit             1.8.0
tensorflow                         2.5.0
tensorflow-estimator               2.5.0
termcolor                          1.1.0
terminado                          0.10.1
testpath                           0.5.0
text-unidecode                     1.3
textdistance                       4.2.1
threadpoolctl                      2.2.0
three-merge                        0.1.1
tinycss2                           1.1.0
tinydb                             4.5.0
toml                               0.10.2
tomli                              1.2.1
tornado                            6.1
tqdm                               4.51.0
traitlets                          5.0.5
typing-extensions                  3.7.4.3
ujson                              4.1.0
urllib3                            1.25.11
watchdog                           2.1.3
wcwidth                            0.2.5
webencodings                       0.5.1
Werkzeug                           2.0.1
wheel                              0.35.1
widgetsnbextension                 3.5.1
win-inet-pton                      1.1.0
wincertstore                       0.2
wrapt                              1.12.1
yapf                               0.31.0
zipp                               3.5.0

**Comment by lbianchi-lbl** [comment]
@bpaul4 @andrewlee94 I thought this was ringing a bell and I now remember I briefly looked into the code. It looks to me like the logic in these lines (https://github.com/IDAES/idaes-pse/blob/main/idaes/apps/uncertainty_propagation/uncertainties.py#L139-L145) could be related to the error: 

```py
    if variable_clean:
        theta_out = {}
        for i in var_dic.keys():
            theta_out[var_dic[i]] = theta[i]
        theta_names = [var_dic[v] for v in theta_names] 
    else:
        theta_out = theta
```

e.g., depending on whether `variable_clean` is true or not, a different type is returned, which then causes the error in the comparison (`dict` cannot be compared with `float`).

Not sure how likely this is, but maybe someone with more knowledge of the code can chime in?

**Comment by andrewlee94** [comment]
@lbianchi-lbl That does sound like there is an underlying bug in the code. However, it is also unusual that @bpaul4 is seeing errors whilst running a test that passes on other systems.

**Comment by adowling2** [comment]
I quickly looked at the code. I believe `theta` will be a dictionary if `variable_clean` is true or false.

Any chance that the behavior of `np.testing.assert_array_almost_equal` changed? Perhaps in the version in our testing suite, it was okay with the type error. But now it is not? Is there an equivalent "assert almost equal" for dictionaries?

**Comment by adowling2** [comment]
Looks like https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_array_almost_equal.html

fell out of favor and https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_almost_equal.html

should be used instead.

**Comment by bpaul4** [comment]
After updating my local Numpy packages, these failures no longer appear on my local machine. I believe this issue has been resolved and may be closed.

**Comment by adowling2** [comment]
Can you post your package versions post upgrade? Mainly to document if this resurfaces.

**Comment by bpaul4** [comment]
```
Package                            Version             Location
---------------------------------- ------------------- -------------------------------
absl-py                            0.13.0
addheader                          0.2.3
alabaster                          0.7.12
appdirs                            1.4.4
argon2-cffi                        20.1.0
arrow                              1.1.1
astroid                            2.5.6
astunparse                         1.6.3
async-generator                    1.10
atomicwrites                       1.4.0
attrs                              21.2.0
autopep8                           1.5.7
Babel                              2.9.1
backcall                           0.2.0
backports.shutil-get-terminal-size 1.0.0
bcrypt                             3.2.0
binaryornot                        0.4.4
black                              21.7b0
bleach                             3.3.0
brotlipy                           0.7.0
bunch                              1.0.1
cachetools                         4.2.2
certifi                            2021.10.8
cffi                               1.14.3
chardet                            3.0.4
click                              7.1.2
cloudpickle                        1.6.0
colorama                           0.4.4
conda                              4.11.0
conda-package-handling             1.7.2
cookiecutter                       1.7.3
coverage                           5.5
cryptography                       3.2.1
cycler                             0.10.0
debugpy                            1.3.0
decorator                          4.4.2
defusedxml                         0.7.1
diff-match-patch                   20200713
docutils                           0.17.1
entrypoints                        0.3
et-xmlfile                         1.1.0
flake8                             3.9.2
Flask                              2.0.1
Flask-Cors                         3.0.10
flatbuffers                        1.12
fpdf2                              2.4.3
gast                               0.4.0
google-auth                        1.32.1
google-auth-oauthlib               0.4.4
google-pasta                       0.2.0
grpcio                             1.34.1
h5py                               3.1.0
idaes-examples                     1.11.0
idaes-pse                          1.12.0.dev0         c:\users\bpaul\github\idaes-pse
idna                               2.10
imagesize                          1.2.0
importlib-metadata                 4.6.4
inflection                         0.5.1
iniconfig                          1.1.1
intervaltree                       3.1.0
ipykernel                          6.0.1
ipython                            7.25.0
ipython-genutils                   0.2.0
ipywidgets                         7.6.3
isort                              5.9.1
itsdangerous                       2.0.1
jedi                               0.18.0
Jinja2                             3.0.1
jinja2-time                        0.2.0
joblib                             1.0.1
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     6.1.12
jupyter-console                    6.4.0
jupyter-contrib-core               0.3.3
jupyter-contrib-nbextensions       0.5.1
jupyter-core                       4.7.1
jupyter-highlight-selected-word    0.2.0
jupyter-latex-envs                 1.4.6
jupyter-nbextensions-configurator  0.4.1
jupyterlab-pygments                0.1.2
jupyterlab-widgets                 1.0.0
keras                              2.7.0
keras-nightly                      2.5.0.dev2021032900
Keras-Preprocessing                1.1.2
keyring                            23.1.0
kiwisolver                         1.3.1
lazy-object-proxy                  1.6.0
libclang                           12.0.0
lxml                               4.6.3
Markdown                           3.3.4
MarkupSafe                         2.0.1
matplotlib                         3.4.2
matplotlib-inline                  0.1.2
mccabe                             0.6.1
menuinst                           1.4.16
mistune                            0.8.4
mpmath                             1.2.1
mypy-extensions                    0.4.3
nbclient                           0.5.3
nbconvert                          6.1.0
nbformat                           5.1.3
nest-asyncio                       1.5.1
networkx                           2.5.1
notebook                           6.4.0
numpy                              1.21.5
numpydoc                           1.1.0
oauthlib                           3.1.1
omlt                               0.3.0
openpyxl                           3.0.7
opt-einsum                         3.3.0
packaging                          21.0
pandas                             1.3.0
pandocfilters                      1.4.3
paramiko                           2.7.2
parso                              0.8.2
pathspec                           0.9.0
pecos                              0.2.0
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             8.3.0
Pint                               0.17
pip                                20.2.4
pluggy                             0.13.1
ply                                3.11
pockets                            0.9.1
poyo                               0.5.0
prometheus-client                  0.11.0
prompt-toolkit                     3.0.19
protobuf                           3.17.3
psutil                             5.8.0
ptyprocess                         0.7.0
py                                 1.10.0
pyasn1                             0.4.8
pyasn1-modules                     0.2.8
pycodestyle                        2.7.0
pycosat                            0.6.3
pycparser                          2.20
pydocstyle                         6.1.1
pyflakes                           2.3.1
Pygments                           2.9.0
pylint                             2.8.3
pyls-spyder                        0.4.0
PyNaCl                             1.4.0
Pyomo                              6.2
pyOpenSSL                          19.1.0
pyparsing                          2.4.7
PyQt5                              5.12.3
PyQt5-sip                          12.9.0
PyQtWebEngine                      5.12.1
pyrsistent                         0.18.0
PySocks                            1.7.1
pytest                             6.2.4
pytest-cov                         2.12.1
python-dateutil                    2.8.1
python-lsp-black                   1.0.0
python-lsp-jsonrpc                 1.0.0
python-lsp-server                  1.2.1
python-slugify                     5.0.2
pytz                               2021.1
pywin32                            227
pywin32-ctypes                     0.2.0
pywinpty                           1.1.3
PyYAML                             5.4.1
pyzmq                              22.1.0
QDarkStyle                         3.0.2
qstylizer                          0.2.1
QtAwesome                          1.0.3
qtconsole                          5.1.1
QtPy                               1.9.0
rbfopt                             4.2.2
regex                              2021.8.3
requests                           2.24.0
requests-oauthlib                  1.3.0
rope                               0.19.0
rsa                                4.7.2
Rtree                              0.9.7
ruamel-yaml                        0.15.87
scikit-learn                       0.24.2
scipy                              1.7.0
Send2Trash                         1.7.1
setuptools                         50.3.1.post20201107
six                                1.15.0
sklearn                            0.0
snowballstemmer                    1.2.1
sortedcontainers                   2.4.0
Sphinx                             4.0.3
sphinx-argparse                    0.2.5
sphinx-rtd-theme                   0.5.2
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             2.0.0
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-napoleon             0.7
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.5
spyder                             5.1.1
spyder-kernels                     2.1.0
sympy                              1.8
tensorboard                        2.7.0
tensorboard-data-server            0.6.1
tensorboard-plugin-wit             1.8.0
tensorflow                         2.7.0
tensorflow-estimator               2.7.0
tensorflow-io-gcs-filesystem       0.23.1
termcolor                          1.1.0
terminado                          0.10.1
testpath                           0.5.0
text-unidecode                     1.3
textdistance                       4.2.1
threadpoolctl                      2.2.0
three-merge                        0.1.1
tinycss2                           1.1.0
tinydb                             4.5.0
toml                               0.10.2
tomli                              1.2.1
tornado                            6.1
tqdm                               4.51.0
traitlets                          5.0.5
typing-extensions                  3.7.4.3
ujson                              4.1.0
urllib3                            1.25.11
watchdog                           2.1.3
wcwidth                            0.2.5
webencodings                       0.5.1
Werkzeug                           2.0.1
wheel                              0.35.1
widgetsnbextension                 3.5.1
win-inet-pton                      1.1.0
wincertstore                       0.2
wrapt                              1.12.1
yapf                               0.31.0
zipp                               3.5.0
```
