### ISSUE TITLE
as_quantity utility function?

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-pse#605]
[referring to ``_as_quantity()`` function see link] Seeing as this is turning up in a few places, should we be making this a general utility somewhere?

_Originally posted by @andrewlee94 in https://github.com/IDAES/idaes-pse/pull/600#discussion_r752274020_

**Comment by ksbeattie** [comment]
this is related to #44

**Comment by andrewlee94** [comment]
This is basically done.
