### ISSUE TITLE
Request for confidence intervals in surrogate metrics

### ISSUE THREAD

**Issue by GuillermoGarciaF** [IDAES/idaes-pse#643]
Function `alamopy.almconfidence(data=result)` throws the following TypeError

` 54         # print(f"numerator {float(data['ssr'][okey])}") `
` 55         print(f"denominator {(float(ndata) - float(nlinterms))}") `
` ---> 56         sigma = float(data['ssr'][okey]) / (float(ndata) - float(nlinterms)) `
` 57         ci = np.zeros([nlinterms])`
` 58         covar = sigma * np.linalg.inv(np.matmul(np.transpose(sensmat), sensmat))`
` TypeError: string indices must be integers `

where `result` is the output of `alamopy.alamo()`, i.e., the output of running ALAMO on some data.

Revising the function source code, I have checked that
`if(isinstance(data['model'], type({}))):`
    `    for okey in data['model'].keys():`

iterates over all `data['model'].keys()` i.e., over all targets to predict. In my case, I'm predicting a unique target "T" (simplest case).
Now, the error arises here:
`sigma = float(data['ssr'][okey]) / (float(ndata) - float(nlinterms))`

Note that `data['ssr']` is the Sum of Squares due to Regression, i.e., it is a numeric value that evaluates how well performs the model.
As we saw, `okey` is the target "T". It therefore doesn't make sense to subset a numeric value (`data['ssr']` ) using the key "T" (or any other key, as a numeric value cannot be filtered using a key) thus the error is raised.

Could you please revise & update the `alamopy.almconfidence()` function? I believe it is a very useful function.
PS: for testing, you can use any of the idaes-examples, e.g. IDAES/Examples/SurrMod/ALAMO/ackley.py or /branin.py

Thank you

**Comment by andrewlee94** [comment]
@GuillermoGarciaF The version of `alamopy` (along with `almconfidence`) you are using has been deprecated in favour of a new implementation, thus we are no longer supporting and updating this code. The new version of `alamopy` can be found in the latest release (v1.12) here: https://github.com/IDAES/idaes-pse/blob/main/idaes/surrogate/alamopy.py.

The new `alamopy` is part of a new integrated interface for all surrogate modeling tools in IDAES, and contains its own metrics package (https://github.com/IDAES/idaes-pse/blob/main/idaes/surrogate/metrics.py), however we do not have confidence intervals yet. I'll rename this issue to propose adding calculation of confidence intervals to the metrics package.
