### ISSUE TITLE
unit model's `add_state_material_balances` relies on a "params" attribute

### ISSUE THREAD

**Issue by Robbybp** [IDAES/idaes-pse#646]
`add_state_material_balances`, which I believe is used to add material balance equations for unit models that do not need a control volume, relies on its two state blocks having a "params" attribute, which I don't think is a strict requirement of property packages (correct me if I'm wrong). It seems like accessing `state.config.parameters` would be safer.

**Comment by andrewlee94** [comment]
@Robbybp The `params` property is part of the `StateBlockData` base class, so I think it is fair to say it is a strict requirement of a property package. The main purpose of the `params` property is for things like this.

**Comment by Robbybp** [comment]
Yep, had a bug that gave me an error here, then I misread the **property_base.py** and missed that params was being added with the property decorator. Not an issue.
