### ISSUE TITLE
Expand set of environments on which CI checks are run to detect OS- and OS-version-specific problems

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/idaes-pse#648]
## Description

- Recently there have been some instances of solver errors that only occur on a specific OS or OS version. One example is e.g. IDAES/examples-pse#83, where the solver fails when running the notebook on CentOS 8, but not on Ubuntu 18.04, which is the OS version we're using in GitHub Actions (GHA) to run our CI checks on Linux
- This is a "false negative" for our current CI setup: this error would have been caught if CentOS 8 was among the list of OSes where the CI checks are run in GHA

## Possible solutions

- Configure the GHA workflows to include OSes and version that are supported by IDAES (using e.g. `idaes-ext` builds as a reference) but are not currently being used

## Challenges

- If the OS is not one of those provided by default by GHA (as it is for e.g. CentOS), the CI job cannot be parametrized using the `matrix` syntax, but requires a separate job definition
- Because the number of CI jobs that can run simultaneously at a given time is limited, we should think carefully how to distribute the various OS/version combinations in the various CI workflows so that they don't "clog" the CI pipelines for the repo

**Comment by lbianchi-lbl** [comment]
Other issues that are connected with this:

- #752 
- #224

**Comment by ksbeattie** [comment]
Closing this as "complete" in that we don't build on CentOS anymore.
