### ISSUE TITLE
FS vis tests opening browser windows

### ISSUE THREAD

**Issue by dangunter** [IDAES/idaes-pse#654]
OS: Linux

But should also fix so it *cannot* happen on MacOS and Windows.

**Comment by dangunter** [comment]
Note that the fix does not need to be universal or permanent. Something used only by the tests to turn off opening browser windows will suffice.. for now.

**Comment by dangunter** [comment]
@elbashandy Did you look at this?

**Comment by elbashandy** [comment]
@dangunter yes! I fixed it here https://github.com/IDAES/idaes-pse/pull/656
