### ISSUE TITLE
Add wall temperature and heat accumulation terms to the 0D heat exchanger

### ISSUE THREAD

**Issue by rustygentile** [IDAES/idaes-pse#673]
# Summary 
Hello IDAES team. I have a unit model that, I think, would make a nice contribution as a pull request. A draft of it can be found [here](https://github.com/CATER-UCF/sco2-air-cooler/blob/master/models/heat_exchanger_lumped_capacitance.py). Our use case was for a transient simulation of an sCO2 power cycle, though there's nothing really sCO2 or power plant specific here. This could be used to model any heat exchanger.

# Questions 
* Would this be better suited as a new unit model in `/generic_models` or in `/power_generation` ? Another option could be to add my new code directly to `/idaes/generic_models/unit_models/heat_exchanger.py`
* I'd also like to include an example flowsheet. Should this be added to one of the `/flowsheets` folders here or to the `examples-pse` repository? (See also #577). If we opt for the latter, how would you prefer to keep the changes in sync? Maybe submit the PR's to feature branches instead of main?

Any other early feedback or considerations would be welcome too, of course.

**Comment by rustygentile** [comment]
Another note: it seems that, as an external user, I don't have permission to assign this to myself as the [docs](https://idaes-pse.readthedocs.io/en/stable/advanced_user_guide/developer/devsw.html#create-an-issue-on-github) suggest.

**Comment by eslickj** [comment]
This looks great.  I didn't look at the details really close, but I have some notes on style.  To accommodate the possibility of indexed models and to have your constraints built automatically, you can inherit HeatExchangerData and implement the build method.

Here's an example (see one of the IDAES model for a concrete example):

```python
...
@declare_process_block_class("HeatExchangerLumpedCapacitance", doc="...")
class HeatExchangerLumpedCapacitanceData(HeatExchangerData):
    CONFIG = HeatExchangerData.CONFIG(implicit=True)
    ...Additional config options if any...
    def build(self):
        super().build()
        self.add_dynamic_variables()
        self.add_dynamic_variable_constraints()
        ...

 
    ...special initialization methods? if yes implement initialize...

    ...special scaling factor calculations? if yes implement calculate_scaling_factors...
```

**Comment by eslickj** [comment]
As for the questions, I'd say the model looks like it fits in the generic_models directory, and depending on how complicated your example is I'd say there are two options.  1) Add a documentation page and include the short example in the documentation.  2) If you have a more involved example the examples-pse repo is probably the right place.  For keeping changes in sync, I think you can make a PR in both repos even before the on in idaes-pse is merged.  We'll just need to merge the idaes-pse one first.

**Comment by rustygentile** [comment]
@eslickj, @andrewlee94, thank you both for the feedback and the style hints. I should have the PR submitted within the next week or so. 

> To accommodate the possibility of indexed models and to have your constraints built automatically, you can inherit HeatExchangerData and implement the build method.

Overriding `build` and `initialize` did occur to me, though how to inherit the parent model's config and extend it like that wasn't so obvious.

> 2. We are going to need some tests to go with the model - how many will depend on where the model ends up being put. To go into `generic_models` it will need some fairly extensive tests, but we are also discussing a `contrib` folder with a lower bar for inclusion (but also less promise of continuing support).

That makes sense. To reach the `generic_models` standard, is there another model and set of tests that you recommend I use as a reference? For instance, `test_heat_exchanger.py` might be a little excessive for this. Although including some regression tests from there is probably a good idea. On the other hand, something like `test_hx_ntu.py` probably wouldn't be sufficient since the new model is more complex. My thinking is to aim for something between those two.
