### ISSUE TITLE
Support for Python 3.10

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/idaes-pse#677]
- Python 3.10 is currently the latest stable release of Python; as such, it is (or will soon be) increasingly used as the default version, both at the OS installation level and within Conda environments
- This issue is to track the current status and future support of Python 3.10 compatibility for IDEAS

## Current status

IDAES is currently not tested with Python 3.10, which should therefore be considered **not supported**.

Known issues preventing compatibility include:

- Pyomo: requires `python<=3.9`
  - This is due to the `nose` testing framework being EOL'ed and not supporting Python 3.10
  - Pyomo code itself is most likely fine with Python 3.10
  - 3.10 support will require porting test suit to pytest; it is possible (but not guaranteed) that this will happen by the next Pyomo release

**Comment by blnicho** [comment]
@lbianchi-lbl FYI Pyomo 6.3.0 officially supports (and tests against) Python 3.10

**Comment by lbianchi-lbl** [comment]
This has been implemented in #726.
