### ISSUE TITLE
Cubic function root finder and Cubic EoS

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-pse#701]
I want to take the generic Cubic EoS stuff out of the cubic root calculator function.  This will make the external function simpler and the whole thing more flexible if we want to add a new type of cubic EoS.

Right now how it works is the external function take eos type (Peng-Robinson, SRK, or Van der Waals) and A and B.  Then based on the EoS type, A and B and calculates the roots.  What I want to do is just provide a function that returns the answers to  0 = z^3 + bz^2 + cz +d given b, c, and d.  User's won't know the difference and it's probably a (mostly) a simple find and replace to update the IDAES code.  I feel like nothing should be in an external C function without good reason, and this chunk of the cubic EoS doesn't really have a good reason for being there.

Any thoughts?  I can probably handle this update, if everyone is okay with it.

**Comment by adowling2** [comment]
@bbefort @agarciadiego FYI

**Comment by adowling2** [comment]
Yes, this seems more flexible.

**Comment by viiibhav** [comment]
Seems good to me, I am assuming the derivatives will now be calculated in pyomo. Will this include the mock extension for the cubic EoS?

**Comment by andrewlee94** [comment]
I do not see an issue with this.

**Comment by eslickj** [comment]
@viiibhav, the derivatives for 0 = z^3+bz^2 + cz + d with respect to the coefficients will still be calculated in the external function.  I'm thinking I will add three options, mock root, same root, and error, for when a real root doesn't exist.
