### ISSUE TITLE
Need for Reference State Definitions

### ISSUE THREAD

**Issue by PTA0001** [IDAES/idaes-pse#709]
1. There exists a need for  various options of reference state definitions:
   -  Setting entropy reference and enthalpy reference(while this can be any arbitral constant for non-reactive systems, it becomes important for reactive systems and leads to point number 2)
   -  Setting Gibbs energy reference and enthalpy reference(mostly for reactive systems using the heat of formation  but also applicable to non-reactive systems ) 
 2. Clarity of entropy reference state as defined by the third law of thermodynamic(absolute entropy reference) and entropy of 
 formation. 
3. with the aforementioned, the reference state variables cannot be defined by specific property methods as this will lead to dependencies or inconsistencies.  Alternatively, the current specific methods e.g RPP4 need to take into account the various options for reference state specifications.

**Comment by andrewlee94** [comment]
For this, we rely on the user to specify consistent references states (by necessity); without a reference library of properties at a reference state, the framework has no way of knowing if the conditions provided are consistent or not.

Note that this was a deliberate design choice, as there are cases where a user may be willing to sacrifice strict thermodynamic consistency for simpler model formulation. We allow users to separately assign methods for heat capacity, enthalpy, entropy and Gibbs energy without consideration for consistency, even though all of these can be calculated from each other via Maxwell relations. This is to support the possibility of using simpler correlations for these (e.g. surrogates) in cases where strict consistency (or the guarantee thereof) is not required.
