### ISSUE TITLE
ALAMOPY error when ALAMO termination is not Normal Completion

### ISSUE THREAD

**Issue by sreekanthrajagopalan** [IDAES/idaes-pse#716]
When ALAMO executable terminates without Normal Completion status, a warning is raised and temporary files including any trace file are [cleaned](https://github.com/IDAES/idaes-pse/blob/68dcd0a5964994a3df62a70b78c0102dcf0d9609/idaes/surrogate/alamopy.py#L781). An error in the [call stack](https://github.com/IDAES/idaes-pse/blob/68dcd0a5964994a3df62a70b78c0102dcf0d9609/idaes/surrogate/alamopy.py#L502) occurs when the trace file is [attempted to be read](https://github.com/IDAES/idaes-pse/blob/68dcd0a5964994a3df62a70b78c0102dcf0d9609/idaes/surrogate/alamopy.py#L804) without any checks for existence of the file.

[AlamoTrainer.train_surrogate](https://github.com/IDAES/idaes-pse/blob/68dcd0a5964994a3df62a70b78c0102dcf0d9609/idaes/surrogate/alamopy.py#L471) does check for non-zero return codes from the executable and returns log messages to the caller. The function should be updated to return gracefully without raising errors and let the caller handle the return code, I think.

**Comment by andrewlee94** [comment]
@sreekanthrajagopalan Could you provide us with a simple code snippet demonstrating the issue and the error messages returned? At the moment I am having a little trouble understanding exactly what is happening, and what you think should happen.

**Comment by sreekanthrajagopalan** [comment]
@andrewlee94 Here is a trivial example where I am setting maxtime to 0.01 so that ALAMO terminates with a status other than Normal Completion. (In this case "ALAMO terminated with termination code 68\nMaximum CPU time (MAXTIME) exceeded.") I encountered this issue when running a training that exceed default time limit of 1000.

Example Python code:
```
import numpy as np
import pandas as pd
from idaes.surrogate.alamopy import AlamoTrainer

training_data = pd.DataFrame(np.array(
        [[0.353837234435, 0.99275270941666, 0.762878272854],
         [0.904978848612, -0.746908518721, 0.387963718723],
         [0.643706630938, -0.617496599522, -0.0205375902284],
         [1.29881420688, 0.305594881575, 2.43011137696],
         [1.35791650867, 0.351045058258, 2.36989368612],
         [0.938369314089, -0.525167416293, 0.829756159423],
         [-1.46593541641, 0.383902178482, 1.14054797964],
         [-0.374378293218, -0.689730440659, -0.219122783909],
         [0.690326213554, 0.569364994374, 0.982068847698],
         [-0.961163301329, 0.499471920546, 0.936855365038]]),
        columns=["x1", "x2", "z1"])

# Test end-to-end workflow with a simple problem.
bnds = {"x1": (-1.5, 1.5), "x2": (-1.5, 1.5)}
alamo_trainer = AlamoTrainer(
    input_labels=["x1", "x2"],
    output_labels=["z1"],
    input_bounds=bnds,
    training_dataframe=training_data, maxtime=0.01)

alamo_trainer.train_surrogate()
```

Output:
```
2022-02-18 16:59:51 [WARNING] idaes.surrogate.alamopy: ALAMO executable returned non-zero return code. Check the ALAMO output for more information.
Traceback (most recent call last):
  File "C:\Users\u783624\Codes\External\PSE-idaes-pse.fork\idaes\surrogate\alamopy.py", line 502, in train_surrogate
    trace_dict = self._read_trace_file(
  File "C:\Users\u783624\Codes\External\PSE-idaes-pse.fork\idaes\surrogate\alamopy.py", line 804, in _read_trace_file
    with open(trcfile, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\u783624\\AppData\\Local\\Temp\\tmputcc8b3h.trc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\u783624\Codes\External\PSE-idaes-pse.fork\mytest.py", line 26, in <module>
    alamo_trainer.train_surrogate()
  File "C:\Users\u783624\Codes\External\PSE-idaes-pse.fork\idaes\surrogate\alamopy.py", line 511, in train_surrogate
    self._remove_temp_files()
  File "C:\Users\u783624\Codes\External\PSE-idaes-pse.fork\idaes\surrogate\alamopy.py", line 911, in _remove_temp_files
    self._temp_context.release(remove=remove)
AttributeError: 'NoneType' object has no attribute 'release'
```

Is it expected of the user/caller to call `train_surrogate()` within a try/except block to catch these exceptions? If so, no further action needed.

**Comment by andrewlee94** [comment]
So, in this case yes, it is up to the user to decide to what to do in this case and a try/except would be the way to do it.

I am slightly surprised to see the follow on issues during clean-up, but otherwise this behavior is expected. If ALAMO fails, then it is up to the user to work out how to fix it, and there is no point returning a result.
