### ISSUE TITLE
Error when setting "dynamic" to be True

### ISSUE THREAD

**Issue by mharyoowa** [IDAES/idaes-pse#723]
Hello guys, so I am trying to create a dynamic state flowsheet.  According to the documentation, If dynamic = True, the flowsheet is declared to be a dynamic flowsheet. I tried this but I keep getting an error message. Kindly see below:

![image](https://user-images.githubusercontent.com/99033999/155268009-cd055def-c215-4e1f-9164-e869e1212f99.png)
![image](https://user-images.githubusercontent.com/99033999/155268045-9758e378-3af7-47f1-95c5-bf1100f4f796.png)

**Comment by mharyoowa** [comment]
Also, is it possible to solve DAE problems in IDAES?

**Comment by andrewlee94** [comment]
@mharyoowa For you first question ,when declaring a dynamic flowsheet you also need to specify what units of time will be used for the time domain by also providing the `time_units` argument, e.g.:

```
m.fs = FlowsheetBlock(default={"dynamic"=True, "time_units"=pyo.units.s})
```

For you second question, yes it is possible to solve DAEs in IDAES and we use this for both dynamic models and for spatially discretized unit operations (e.g. PFRs). You should start by looking at the documentation for `pyomo.dae` as you will need to use these form the basis for the IDAES models: https://pyomo.readthedocs.io/en/stable/modeling_extensions/dae.html.

**Comment by mharyoowa** [comment]
I'm still getting an error.

![image](https://user-images.githubusercontent.com/99033999/155341591-44b91088-d556-4057-9ad5-f359b0b96f91.png)

**Comment by andrewlee94** [comment]
You need to import `units` from `pyomo.environ`. In you case, add `units` to the import line, and then use `units.s` instead of `pyo.units.s`.

**Comment by mharyoowa** [comment]
it finally worked. Thank you!!

One last one please, I can follow the examples for steady state to solve my dynamic state model right?

**Comment by andrewlee94** [comment]
@mharyoowa Not really - there is a significant step between solving a steady-state model and a dynamic model. Setting the `dynamic` flag to `True` will automatically add the accumulation and hold up terms to all your unit models, however that is only half the work in setting up a dynamic problem. Notably, with a dynamic system you also need to consider initial conditions for the system in addition to any inlet flows and design conditions, plus you also need to include some form of pressure-flow relationship in the system. In short, adding accumulation terms to the problem adds additional degrees of freedom that you need to satisfy by adding additional specifications and/or constraints,

**Comment by mharyoowa** [comment]
This is a lot and I'm kinda new to all this. Can you guys just create an example for solving dynamic state models?

**Comment by andrewlee94** [comment]
We will add a dynamic example to the list of additional documentation to generate as time/resources permit.  Pull requests are always welcome, though!
