### ISSUE TITLE
Attribute error when initializing IDAES GDP model using .json file 

### ISSUE THREAD

**Issue by esrawli** [IDAES/idaes-pse#725]
I get the following error when initializing an IDAES GDP model using a .json file:

AttributeError: 'AutoLinkedBooleanVar' object has no attribute 'activate'

Any feedback would be great!

**Comment by eslickj** [comment]
By default the JSON serializer tries to write whether a ``Var`` is active.  It seems that ``AutoLinkedBooleanVar`` looks like a subclass of ``Var`` but doesn't have the ``active`` attribute.  I can fix this pretty easy.  Will do it ASAP.  Overall I probably just need to handle the case where an expected attribute is missing more gracefully.

**Comment by eslickj** [comment]
Ok, the issue seems to be that a BooleanVar is not a Var.  I think I can add tests for this and fix it.
