### ISSUE TITLE
Update tests for distillation units

### ISSUE THREAD

**Issue by jghouse88** [IDAES/idaes-pse#73]
From review of IDAES/idaes-dev#1082:

   - Any test that involves a solver (or depends on the result of a solver) should be tagged as a component test. This would be the initialization, solver, solution and conservation tests.
  -  To allow component tests to run independently of unit tests, setting the degrees of freedom should be done in the fixture, not in the dof test itself (otherwise if the component tests are run in isolation, the dof are not set).
  -  Could you separate the different model structures (e.g. state variables) into separate test classes. This will help with debugging in the future, as each test case can be debugged in parallel. As it is, the first failure will mask any subsequent failures.
 - Test other combinations of state variables other than FTPz and FcTP

**Comment by andrewlee94** [comment]
Most of this should be fixed as part of https://github.com/IDAES/idaes-pse/pull/1050 if it hasn't already.
