### ISSUE TITLE
Standardize naming in Heat Exchanger models

### ISSUE THREAD

**Issue by andrewlee94** [IDAES/idaes-pse#730]
Naming of components in heat exchangers still appears to be inconsistent in places (e.g. naming of sides) - we should resolve any remaining issues.

**Comment by eslickj** [comment]
The official side names for the 0D heat exchanger are hot_side and cold_side.  They have other names for backward compatibility.  Users can assign names, which are by default shell for the hot side and tube for the cold side.  We can clean that up and remove old names in IDAES 2.0 (side_1 and side_2 still work).  If there's other specific stuff, we can note it here, and I'll fix it.  I guess the 0D and 1D heat exchanger need to match.  That's probably the main point.

For the 0D heat exchanger, which side is hot and cold sometimes matters.  For 1D I'm not sure if it ever matters, but it is a clear naming convention even if it's not strictly necessary for the hot side to be hotter than the cold side.

**Comment by andrewlee94** [comment]
I had a look through all the HX models (both in `models` and `models_extra` today and here is a quick summary:

1. We have at least 4 different naming conventions across all the models.
2. All but 3 models declare a `hot_side` and `cold_side` (either directly or via aliases).
3. The 0D HX model and Condenser model have a list of aliases as long as my arm (which is too many).

My proposal is:

1. Make `hot_side` and `cold_side` the standard names across all HX models (with the exception of the 3-stream HX model for obvious reasons). These will be the names used for any related config arguments, the control volumes and the ports.
2. Add optional config arguments to all models for `hot_side_name` and `cold_side_name`. If provided, we then create one set of aliases for the control volumes and ports using the user provided names.
