### ISSUE TITLE
Notify users when attempting to install IDAES extensions on incompatible hardware

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/idaes-pse#745]
## Symptoms

- We've been trying to set up a developer environment on a macOS laptop with an Apple Silicon (ARM-based) processor
- Since macOS is not supported by IDAES, we're using an Ubuntu 20.04 virtual machine through Parallels
- The IDAES installation procedure seems to proceed without errors, including `idaes get-extensions`
- However, as soon as any of the IDAES executables are accessed, an error occurs (see watertap-org/watertap#398), e.g. `OSError: [Errno 8] Exec format error: '/home/xb-ubt20/.idaes/bin/ipopt'`

## Diagnosis

- The cause for the errors is most likely the fact that the ARM-based version of the Ubuntu guest OS is being installed (as opposed to the x86-64 version, which we know is compatible with the IDAES extensions; this is something we're trying to work out independently)

## Solutions

- Since we know that hardware architectures other than `x86-64` are not supported by the IDAES extensions, we could add a pre-check in `idaes get-extensions` so that users are made aware of this issue at an earlier stage, e.g. (untested naive example):
  - Get hardware architecture from e.g. `uname -a`
  - Check that it is in a list of supported architectures such as `x86-64`
  - If not, raise an error `Error: hardware architecture not supported: aarch64`

**Comment by eslickj** [comment]
@jsiirola, I'm using Pyomo's FileDownloader class.  I did a quick look at the code and I don't immediately see a way to get the architecture.  Is there a way?  If not should we add that in Pyomo.  Once we have that, I can check it, and add that info to the package names.

**Comment by lbianchi-lbl** [comment]
@eslickj if it can be useful, I've just found out that there's a `platform.machine()` function in Python from the `platform` built-in module that outputs `x86_64` on my laptop.

**Comment by eslickj** [comment]
@lbianchi-lbl, I discovered it's really easy to use docker to build the aarach64 binaries.  I guess it would double the builds and tests but it's pretty trivial to do aside from the time.  If you think it's worth doing I can do it.

**Comment by andrewlee94** [comment]
Completed in #788
