### ISSUE TITLE
Clean up deprecation warnings and backwards compatibility code

### ISSUE THREAD

**Issue by andrewlee94** [IDAES/idaes-pse#748]
As the final step in the release of IDAES v2.0, we should clean up all remaining deprecation warnings and backwards compatibility code, and officially end support for the IDAES v1 series.

Tasks to Do:

- [x] Clean up deprecations in `examples-pse`.

    - https://github.com/IDAES/examples-pse/pull/129

- [x] Remove redirects for moved files. PR #937
- [x] Remove old costing modules and all dependencies (in progress, only remainder is power plant costing)
- [x] Identify all uses of deprecation warnings in IDAES code, categorise them and remove where possible.
- [x] Address derprecation warnings arising from dependencies (esp. Pyomo).
- [ ] Identify cases where testing of core IDAES code depends on contributed code and fix (e.g. where testing something in `idaes.models` depends on something in `idaes.models_extra`.
- [ ] Identify all TODO statements and decide whether they should be addressed.

**Comment by eslickj** [comment]
To help with this PR #822

**Comment by andrewlee94** [comment]
All the important aspects of this PR have been addressed, so I will call it completed.
