### ISSUE TITLE
Improvements for IDAES interface to PETSc

### ISSUE THREAD

**Issue by dallan-keylogic** [IDAES/idaes-pse#757]
After some use of the PETSc integrator to initialize a Pyomo model discretized in time, I've run into a few situations where additional tools within IDAES could be helpful.

- [X]  Because PETSc doesn't return values of derivatives, `DerivativeVar`s are not initialized. It would be handy to have a function to automatically initialize them using, e.g., a backwards difference. --- Added in #774.

- [ ] Often we would like a Pyomo model to have a fine mesh, while only a coarse mesh is needed to run PETSc (because it integrates between time points anyway). Furthermore, if we use PETSc with a fine mesh, there is a huge amount of overhead in calling PETSc at every time point, PETSc determining an appropriate step size, then the results getting loaded back into the Pyomo model after PETSc is done time stepping. There are currently tools in IDAES to interpolate PETSc trajectories, but it would be nice to be able to automatically initialize a fine mesh using PETSc trajectories from a coarser mesh.

- [x] It would be nice to have a tool that automatically concatenated PETSc trajectories between different time points. Right now it saves a single file for the gap between every two time points.

**Comment by eslickj** [comment]
@Robbybp, I think this would be useful.  We have the thing to do the PETSc trajectory interpolation.  We mainly need to map the scalar variables from the problem PETSc solves back to time indexed ones with I guess would be in another copy of the model with finer discretization.

**Comment by blnicho** [comment]
> I've implemented a tool to interpolate a Pyomo DAE model onto a model with a more fine discretization grid. (Works for PD(A)Es too!) I use this to do discretization stability testing of my models. Would this be useful? What I've done is operating on Pyomo models, so it's completely agnostic of any Petsc trajectory.

@Robbybp is your tool available somewhere?

**Comment by eslickj** [comment]
@blnicho, thanks that would probably be helpful.  I'm going to get to this in the next could days.

**Comment by Robbybp** [comment]
The code I'm talking about ("tool" might be a little generous) is here:
https://github.com/IDAES/publications/tree/main/parker_dycops2022/parker_dycops2022/common/serialize
See approximately lines 300-330 of this file for an example of use:
https://github.com/IDAES/publications/blob/main/parker_dycops2022/parker_dycops2022/run_stability_analysis.py

**Comment by Robbybp** [comment]
I guess I don't actually transfer the data back to a model with a more fine discretization grid, but from the data structure that holds the data on the finer grid, this should be fairly easy with `m.find_component(name)[t].set_value(val)`.

**Comment by eslickj** [comment]
I think what I'm going to do is allow the user to specify a subset of times.  Integrate between those times.  That will allow the sort-of conditional changes at certain times if you have that.  Then I'll interpolate the full set of time points from the trajectory, fill in the model then calculate the time derivatives.

It shouldn't be too hard.  Currently I'm using the variable names and the .col file to match up model variable with the trajectory output.  That means I just need to change the time index to get the right variable from the trajectory.  Using string names and the col file isn't probably the most efficient, but it's easy.  It will be a first pass anyway.  We can make it more efficient behind the scenes later.  The interpolation is done already.
