### ISSUE TITLE
Failures when running `idaes get-examples`

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/idaes-pse#767]
(Originally reported by @Andresj89)

Running `idaes get-examples` results in an error:

```
idaes get-examples -d /tmp/foo
Internal Error: Could not find an examples release
matching IDAES version 2.0.0
You can manually pick  version with '-V/--version'
or install from a local directory with '--local'.
Use '-l/--list-releases' to see all versions.
--------------------------------------------------
You can report this error by visiting the Github
software page at:
    https://github.com/idaes/idaes-pse/issues
and clicking on 'New issue', or by sending email
to 'idaes-support@idaes.org'. Please include the
command or actions you took, and the resulting
message, in the report.
--------------------------------------------------
```

- My guess is that this is due to switching to 2.0.0dev0 (starting with #759)
- I've tried to address this by updating the version and `idaes-compatibility.json` in `examples-pse` (https://github.com/IDAES/examples-pse/commit/79dfed7ade2a352bf9d847bbd155ed40bf6d4559), but it did not seem to have an effect

**Comment by lbianchi-lbl** [comment]
The workaround is to specify the version directly using the `--version` flag, together with the `--unstable` flag to include prerelease versions in the available versions:

```console
idaes get-examples --version 2.0.0a3 --unstable
```

**Comment by ksbeattie** [comment]
I think the workaround described above is good enough for this strange corner case.

**Comment by ateknur** [comment]
====================commands===============
pip install idaes-pse --pre
idaes get-extensions
idaes get-examples --version 2.0.0a3 --unstable

=====================log====================
Done
---------------------------------------------------
IDAES Extensions Build Versions
===================================================
Solvers:  v3.1.0 20221103-0906 ubuntu2004-x86_64
Library:  v3.1.0 20221103-0937 ubuntu2004-x86_64
===================================================
Downloading...
Installing...
error: package directory 'src/idaes_examples' does not exist
------------------------------------------------------------------------------------------


I was facing same below mentioned issue, so I tried this workaround but getting error: package directory 'src/idaes_examples' does not exist.

=========================================
idaes get-examples -d /tmp/foo
Internal Error: Could not find an examples release
matching IDAES version 2.0.0
You can manually pick  version with '-V/--version'
or install from a local directory with '--local'.
Use '-l/--list-releases' to see all versions.
--------------------------------------------------
You can report this error by visiting the Github
software page at:
    https://github.com/idaes/idaes-pse/issues
and clicking on 'New issue', or by sending email
to 'idaes-support@idaes.org'. Please include the
command or actions you took, and the resulting
message, in the report.
--------------------------------------------------

**Comment by lbianchi-lbl** [comment]
> ====================commands===============
> pip install idaes-pse --pre
> idaes get-extensions
> idaes get-examples --version 2.0.0a3 --unstable

Hi @ateknur, thanks for reporting this. I think the use of `--pre` (which results in the latest available version being installed) and specifying an exact version with `idaes get-examples --version` might have resulted in incompatibilities.

Can you try to run the following commands in the same environment? **NOTE** you might have to delete the `examples` directory if one already exists in the current working directory.

```sh
pip uninstall idaes-pse --yes
pip install idaes-pse==2.0.0b2
idaes get-extensions --verbose
idaes get-examples --unstable --version 2.0.0b2
```

If this still doesn't work, please go ahead and open a new issue with these commands and the output you get.
