### ISSUE TITLE
Run `black` on all code

### ISSUE THREAD

**Issue by andrewlee94** [IDAES/idaes-pse#768]
As part of IDAES v2.0 we should add running `black` on the code as a requirement with an associated test.

We are starting to reformat the code on a folder-by-folder basis as we reorganize the repo.

**Comment by NdagiStanley** [comment]
Are you accepting contributions on this?
I'd happily contribute

**Comment by dallan-keylogic** [comment]
Isn't this complete now?

**Comment by ksbeattie** [comment]
Yes, I believe this was done in #894.

@dallan-keylogic, thanks for following up on this.  @NdagiStanley thanks for the offer to help (even though we didn't take you up on it) and thanks to @lbianchi-lbl for actually doing the hard part
