### ISSUE TITLE
Failing tests on Git 

### ISSUE THREAD

**Issue by elbashandy** [IDAES/idaes-pse#784]
The pytest failures report this issue:

=================================== FAILURES ===================================
___________________________ test_tag_display_convert ___________________________

model = <pyomo.core.base.PyomoModel.ConcreteModel object at 0x7f53231db740>

    @pytest.mark.unit
    def test_tag_display_convert(model):
        m = model
        tw = ModelTag(expr=m.w, format_string="{:.3f}", doc="Tag for w", display_units=pyo.units.g)
        tx = ModelTag(expr=m.x, format_string="{:.3f}", doc="Tag for x", display_units=pyo.units.g)
        ty = ModelTag(
            expr=m.y, format_string="{:.1f}", doc="Tag for y", display_units=pyo.units.hr
        )
        tf = ModelTag(
            expr=m.f,
            format_string="{:.1f}",
            doc="Tag for f",
            display_units=pyo.units.g / pyo.units.hr,
        )
    
>       assert str(tf) == "3000000.0 g/hr"
E       AssertionError: assert '3000000.0 g/h' == '3000000.0 g/hr'
E         - 3000000.0 g/hr
E         ?              -
E         + 3000000.0 g/h

**Comment by bpaul4** [comment]
I see that these first appeared on #775 , but I believe these may be related to Git itself and not a recent commit. While pushing updates to an open PR, these errors appeared after re-running tests for new commits without updating from IDAES:main and any "breaking changes" in the code itself would not have been pulled to the PR.

**Comment by andrewlee94** [comment]
These are related to a new release of `pint` that occurred this morning. We are aware of the issue and are working on a fix.
