### ISSUE TITLE
Missing module for example methanol_synthesis.py

### ISSUE THREAD

**Issue by hbeden** [IDAES/idaes-pse#8]
Missing methanol_reaction ,compressor  and expander as shown below:
#from methanol_reaction import MethanolReactionParameterBlock
#from compressor import IdealGasIsentropicCompressor
#from expander import Expander

**Comment by ksbeattie** [comment]
@hbeden, this should be fixed in the new release, 1.1.0, which should be ready next week.

**Comment by ksbeattie** [comment]
@hbeden, it appears that this file was not intended to be included in the tutorial, so it's being removed.
