### ISSUE TITLE
BFB Oxygen-Iron OC Flowsheet Fails To Solve

### ISSUE THREAD

**Issue by bpaul4** [IDAES/idaes-pse#811]
The flowsheet demonstrating the BFB unit model with the oxygen-iron reduction OC property packages fails to solve successfully. The issue could be due to unapplied or missing scaling, which would require several small straightforward updates. I am using the list below to keep track of items/commits, and will push them to a PR branch once ready:

(Update: all tasks "complete" in forked branch, currently under review in open PR linked below)

- [x] Apply the existing unit model scaling by calculating scaling factors inside the flowsheet
- [x] Convert the property packages from kJ and bar to standard units of J and Pa
- [x] Expand state block methods, including adding entropy calculations
- [x] Scale the gas/solid property packages, including default scaling factors and constraint scaling
- [x] Scale the reaction package, including creating a `self.default_scaling_factor` object and adding constraint scaling
- [x] Scaling tests for the oxygen-iron reduction properties
- [x] BFB tests using the oxygen-iron reduction properties

A visible flowsheet failing to run merits updating these properties (if we wish to keep the notebook), and barring any unexpected debugging this should not be too difficult to implement.

**Comment by andrewlee94** [comment]
This sounds lie there is a gap in our testing if this not resulting in test failures.

**Comment by bpaul4** [comment]
@andrewlee94 It seems we only test the BFB unit model for the methane iron reduction properties, not the oxygen iron reduction properties. If you'd like, I can rename `test_BFB.py` to `test_BFB_methane_oc.py` and create a new file `test_BFB_oxygen_oc.py`.

**Comment by andrewlee94** [comment]
@bpaul4 That is probably a good idea - we should have a test that runs the BFB with both property packages so that we can catch issues like this.
