### ISSUE TITLE
Update Getting Started Page

### ISSUE THREAD

**Issue by FiannaOBrien** [IDAES/idaes-pse#818]
- [X] Split OSs into individual pages
- [ ] Test install on each OS
- [X] Remove links & text related to to empty "optional dependencies" page
- [ ] Test user experience workflow
- [ ] Split specialty installs into How-To Guide pages

**Comment by FiannaOBrien** [comment]
I need some information on the binaries page. I can't find a clear reference to this page within the getting started docs and trying to hide the optional dependencies content has removed the binaries page from the TOC tree, causing a meltdown. The binaries page is content-rich, so I don't want to lose it, I just need to know more about what it is, why it is, and where it should be housed to be most useful.

**Comment by eslickj** [comment]
I have the install testing sort of covered with docker here https://github.com/IDAES/idaes-ext/actions.  We can setup GitHub actions to exactly reproduce the docs and use a similar setup maybe.  Unfortunately I now have ARM64 linux and macOS builds, to testing those (I guess) requires a Mac VM and a local docker install, but mostly I think we could do the same thing.  As far as I know they don't have ARM64 runners hosted by GitHub yet.

I can get you more information on the binaries page.  Just let me know what you need.  Once I have new binaries ready, I'll need to update it anyway.

**Comment by ksbeattie** [comment]
@FiannaOBrien, are the above checkboxes done now with the merging of PR #885?
