### ISSUE TITLE
Uncertainty Propagation Failing on macOS ARM64

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-pse#842]
The uncertainty propagation app doesn't seem to be working on macOS on ARM64 for me.  I think there is a good chance that my build of k_aug and/or dotsens, but they do run.  I'm not really sure how to debug this though.

After a lot of work, I think I've figured out the basic issue, so I'm deleting old comments to avoid confusion.  The problems the solvers are getting seem the same, and the solvers seem to work, but for whatever reason, there are differences in the way the solvers on the two platforms treat to problems.

**Comment by adowling2** [comment]
I am not sure either. I do not have access to ARM64 hardware, so this is difficult for me to debug.

**Comment by adowling2** [comment]
Can you do a side-by-side comparison of the test output (log) for Linux x64 and ARM64?

**Comment by eslickj** [comment]
@adowling2 thanks.  Yeah let me see if I can isolate the first test and get max output on the two systems for comparison.

**Comment by eslickj** [comment]
As shown below it is in fact K_aug failing, but the problem may not be k_aug.  Somehow the number of variables and constraints are different between the two.

This is the working one:

```
I[K_AUG]...     [K_AUG_ASL]File read successfully.
I[K_AUG]...     [K_AUG_ASL]Number of Right hand sides: 0
I[K_AUG]...     [K_AUG_ASL]Number of variables       : 2
I[K_AUG]...     [K_AUG_ASL]Number of constraints     : 0
I[K_AUG]...     [K_AUG_ASL]Number of valid n_dof     : 2
I[K_AUG]...     [ADJUST_MU]     Warning strict complementarity (lb) is not within tol for var:0
I[K_AUG]...     [ADJUST_MU]     Warning strict complementarity (lb) is not within tol for var:1
I[K_AUG]...     [ADJUST_MU]     Warning no relevant info from the problem can predict logmu
yes I hear you 1
W[k_aug]...     [k_aug_asl]printing kkt matrix.
I[K_AUG]...     [FIND_INEQUALITIES]summary: eq: 0, leq: 0, geq: 0
```

This is the non-working one
```
I[K_AUG]...	[K_AUG_ASL]File read successfully.
I[K_AUG]...	[K_AUG_ASL]Number of Right hand sides: 0
I[K_AUG]...	[K_AUG_ASL]Number of variables       : 4
I[K_AUG]...	[K_AUG_ASL]Number of constraints     : 4
I[K_AUG]...	[K_AUG_ASL]Number of valid n_dof     : 0
I[K_AUG]...	[ADJUST_MU]	Warning strict complementarity (lb) is not within tol for var:0
I[K_AUG]...	[ADJUST_MU]	Warning strict complementarity (lb) is not within tol for var:1
I[K_AUG]...	[ADJUST_MU]	Warning no relevant info from the problem can predict logmu
I[K_AUG]...	[FIND_INEQUALITIES]summary: eq: 4, leq: 0, geq: 0 
I[K_AUG]...	[K_AUG_ASL]Nonzeroes in the sparse Jacobian 6
I[K_AUG]...	[GET_HESS_ASL]Objective found```

**Comment by eslickj** [comment]
The one from windows, the second ipopt solve says all variables are fixed.  On macOS there are 4 variables and 4 constraints in the second solve.  Now it looks like there is some problem setting up the problem and not a problem with the binaries.  I'm not sure how that could happen.

Here's environment info for macOS:
(idaes) john@Johns-Mac-mini uncertainty_propagation % idaes environment-info

IDAES
    Version: 2.0.0.dev0
    Git Hash: 0d66e68d98e497035e01a48afa058e9c26325392
    Binary Directory: /Users/john/.idaes/bin
    Data Directory: /Users/john/.idaes
    Global Config: /Users/john/.idaes/idaes.conf

Pyomo
    Version: 6.4.0

Python
    Version: 3.10.4 (main, Mar 31 2022, 03:37:37) [Clang 12.0.0 ]
    Executable: /Users/john/miniconda3/envs/idaes/bin/python

OS
    Platform: Darwin
    Release: 21.4.0
    Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:47:26 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T8101

Dependencies
    backports.shutil_get_terminal_size: 1.0.0
    bunch: 1.0.1
    click: 8.1.2
    colorama: 0.4.4
    distro: 1.7.0
    flask: 2.1.1
    flask-cors: 3.0.10
    ipython: 7.32.0
    jupyter: 1.0.0
    lxml: 4.8.0
    matplotlib: 3.5.1
    nbconvert: 6.5.0
    nbformat: 5.3.0
    networkx: 2.8
    numpy: 1.22.3
    omlt: 0.3.1
    openpyxl: 3.0.9
    pandas: 1.4.2
    pint: 0.19.2
    psutil: 5.9.0
    pytest: 7.1.2
    python-slugify: 6.1.1
    pyyaml: 6.0
    rbfopt: 4.2.4
    requests: 2.27.1
    scipy: 1.8.0
    sympy: 1.10.1
    tinydb: 4.7.0
    xlrd: 2.0.1

Extras
    seaborn: Not Installed

Solvers
    bonmin: 1.8.8.0
    cbc: 2.10.4.0
    couenne: 0.5.8.0
    dot_sens: 1.0.0.0
    ipopt: 3.13.2.0
    ipopt_l1: 3.13.3.0
    ipopt_sens: 3.13.2.0
    k_aug: 0.1.0.0

And Windows:
(idaes-pse) C:\Users\EslickJ\git\idaes-pse\idaes\apps\uncertainty_propagation>idaes environment-info

IDAES
    Version: 2.0.0.dev0
    Git Hash: 0d66e68d98e497035e01a48afa058e9c26325392
    Binary Directory: C:\Users\EslickJ\AppData\Local\idaes\bin
    Data Directory: C:\Users\EslickJ\AppData\Local\idaes
    Global Config: C:\Users\EslickJ\AppData\Local\idaes\idaes.conf

Pyomo
    Version: 6.4.0

Python
    Version: 3.9.4 (default, Apr  9 2021, 11:43:21) [MSC v.1916 64 bit (AMD64)]
    Executable: C:\Users\EslickJ\miniconda3\envs\idaes-pse\python.exe

OS
    Platform: Windows
    Release: 10
    Version: 10.0.19041

Dependencies
    backports.shutil_get_terminal_size: 1.0.0
    bunch: 1.0.1
    click: 8.0.3
    colorama: 0.4.4
    distro: 1.7.0
    flask: 2.0.0
    flask-cors: 3.0.10
    ipython: 7.23.1
    jupyter: 1.0.0
    lxml: 4.6.3
    matplotlib: 3.4.2
    nbconvert: 6.0.7
    nbformat: 5.1.3
    networkx: 2.5.1
    numpy: 1.20.3
    omlt: 0.3.1
    openpyxl: 3.0.9
    pandas: 1.2.4
    pint: 0.17
    psutil: 5.8.0
    pytest: 6.2.4
    python-slugify: 5.0.2
    pyyaml: 5.4.1
    rbfopt: 4.2.2
    requests: 2.25.1
    scipy: 1.6.3
    sympy: 1.8
    tinydb: 4.4.0
    xlrd: 2.0.1

Extras
    seaborn: Not Installed

Solvers
    bonmin: 1.8.8.0
    cbc: 2.10.4.0
    couenne: 0.5.8.0
    dot_sens: 1.0.0.0
    ipopt: 3.13.2.0
    ipopt_l1: 3.13.3.0
    ipopt_sens: 3.13.2.0
    k_aug: 0.1.0.0

**Comment by eslickj** [comment]
So the problem seems the same.  Ipopt seems to work fine on both platforms.  Somehow, though, Ipopt and k_aug while they seem to work, see this problem differently.

On Windows, from Ipopt I get:

```
This is Ipopt version 3.13.2, running with linear solver ma27.

All variables are fixed and constraint violation 0.000000e+00
   is below tolerance 1.000000e-08. Declaring success.
```

On macOS I get:

```
This is Ipopt version 3.13.2, running with linear solver ma27.

Too few degrees of freedom (n_x = 2, n_c = 4).
  Trying fixed_variable_treatment = RELAX_BOUNDS

Number of nonzeros in equality constraint Jacobian...:        6
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:        2

Total number of variables............................:        4
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        2
                     variables with only upper bounds:        0
Total number of equality constraints.................:        4
Total number of inequality constraints...............:        0
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  1.9048060e+01 1.88e-07 9.95e-01  -1.0 0.00e+00    -  0.00e+00 0.00e+00   0
   1  1.9048060e+01 0.00e+00 9.43e-09  -1.7 1.88e-07    -  1.00e+00 1.00e+00f  1

Number of Iterations....: 1

                                   (scaled)                 (unscaled)
Objective...............:   1.9048060484600317e+01    1.9048060484600317e+01
Dual infeasibility......:   0.0000000000000000e+00    0.0000000000000000e+00
Constraint violation....:   0.0000000000000000e+00    0.0000000000000000e+00
Complementarity.........:   0.0000000000000000e+00    0.0000000000000000e+00
Overall NLP error.......:   0.0000000000000000e+00    0.0000000000000000e+00


Number of objective function evaluations             = 2
Number of objective gradient evaluations             = 2
Number of equality constraint evaluations            = 2
Number of inequality constraint evaluations          = 0
Number of equality constraint Jacobian evaluations   = 2
Number of inequality constraint Jacobian evaluations = 0
Number of Lagrangian Hessian evaluations             = 1
Total CPU secs in IPOPT (w/o function evaluations)   =      0.000
Total CPU secs in NLP function evaluations           =      0.000

EXIT: Optimal Solution Found.
```

So while Ipopt reports different, it seems to work okay for both.

**Comment by eslickj** [comment]
The relevant thing seems to be k_aug.  For simplicity I'll just show the relevant lines:

On Windows:

```
I[K_AUG]...     [K_AUG_ASL]File read successfully.
I[K_AUG]...     [K_AUG_ASL]Number of Right hand sides: 0
I[K_AUG]...     [K_AUG_ASL]Number of variables       : 2
I[K_AUG]...     [K_AUG_ASL]Number of constraints     : 0
I[K_AUG]...     [K_AUG_ASL]Number of valid n_dof     : 2
```

On macOS:

```
I[K_AUG]...	[K_AUG_ASL]File read successfully.
I[K_AUG]...	[K_AUG_ASL]Number of Right hand sides: 0
I[K_AUG]...	[K_AUG_ASL]Number of variables       : 4
I[K_AUG]...	[K_AUG_ASL]Number of constraints     : 4
I[K_AUG]...	[K_AUG_ASL]Number of valid n_dof     : 0
```

So on macOS, this results in k_aug failing.  Something is causing the solvers to behave differently between the two systems.

**Comment by adowling2** [comment]
@eslickj Just to be super clear, when you said "macOS" in your previous post, did you mean "macOS ARM64"? I have "macOS x86-64" systems ;)

**Comment by eslickj** [comment]
@adowling2, yes ARM64.

**Comment by eslickj** [comment]
Problem solved!  The coin build of Metis was crashing for some reason (on macOS ARM64).  I added more solver tests to catch it, and I'm switching the mumps and Metis libraries to the ones I build for PETSc.  Seems to work.
