### ISSUE TITLE
Found More Delicate Tests

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-pse#844]
I have some more delicate tests that fail on ARM64 macOS.  I'm not sure who's responsible for these so we can assign appropriately.  I guess the NGFC may be fixed in PR #836.  I didn't put the details in, but I think with these a solve is just failing somewhere.

```
FAILED models/flowsheets/tests/test_demo_flowsheet.py::test_initialize_flowsheet - idaes.core.util.exceptions.InitializationError: fs.M01.inlet_2_state failed to initializ...
FAILED models/flowsheets/tests/test_demo_flowsheet.py::test_solve_flowsheet - assert 3.0479570982064495e-10 == 2.0 ± 2.0e-04
FAILED models_extra/column_models/tests/test_tray_column.py::TestBTXIdeal::test_solve - AssertionError: assert False
FAILED models_extra/column_models/tests/test_tray_column.py::TestBTXIdeal::test_solution - assert 16.856 ± 1.7e-01 == 20.000000000032745
FAILED models_extra/power_generation/flowsheets/test/test_NGFC.py::test_initialize - idaes.core.util.exceptions.InitializationError: fs.air_compressor_s2 failed to initial...
```

**Comment by bpaul4** [comment]
@eslickj could you test pulling from my NGFC branch and see if that resolves the issue with `test_NGFC.py`? In addition to new scaling, the initialization/solve scheme is more robust for re-solving unit blocks.

Regarding the other four tests, I noticed they all use the `idaes.models.properties.activity_coeff_models.BTX_activity_coeff_VLE` property package and we did recently update some of our VLE calculation modules. It would helpful to know which state variable set (btx_ftpz or btx_fctp) failed to solve for the column model tests. I'm not sure why only the toluene inlet is failing for the demo flowsheet, I've only seen something similar when using enthalpy as a state variable and accidentally pushing past the temperature state bounds.
