### ISSUE TITLE
Improve documentation for ALAMO interface

### ISSUE THREAD

**Issue by adowling2** [IDAES/idaes-pse#85]
@mozammelmazumder @OOAmusat 

Let's use this issue to record issues we found when installing ALAMO and using the interface in IDAES:
- [x] Mention in IDAES documentation that ALAMO is an optional dependency, link to where it can be obtained
- [x] Tell ALAMO developers about missing steps in the installation instructions:
   - [x] Installer did not automatically set the path with Windows 10
   - [x] Need to put the ALAMO license in the folder it is installed. Recommend highlighting this in the instructions.

**Comment by GuillermoGarciaF** [comment]
Hello, thank you for the great package, it is really nice, good work!

Are there any updates on this topic? I am having a lot of issues figuring out if a need to install ALAMO software and license to use the idaes.surrogate.alamopy wrapper. 
Currently, it fails and throws the following error #24 

Thank you!

**Comment by andrewlee94** [comment]
Hi @GuillermoGarciaF, we are still working on updating the documentation for the new ALAMO interface, and it will not be ready until after the holiday break unfortunately.

You do need to install ALAMO separately along with a license - the IDAES code is just a wrapper that prepares the .alm file for you and reads the resulting trace file back in to create surrogate object.

**Comment by andrewlee94** [comment]
This issue was addressed in #943
