### ISSUE TITLE
Pynumero spawns multiple instances of script file from which it's called

### ISSUE THREAD

**Issue by dallan-keylogic** [IDAES/idaes-pse#852]
Want to leave a record of [this Pyomo issue](https://github.com/Pyomo/pyomo/issues/2380) in the IDAES repo, in case any IDAES user encounters it.

**Comment by lbianchi-lbl** [comment]
For cross-project reference, this is related to watertap-org/watertap#387, with a simple workaround described [here](https://watertap.readthedocs.io/en/latest/how_to_guides/how_to_run_models_in_a_py_script.html).

**Comment by ksbeattie** [comment]
While someone might be interested in finding out what/where/why this script is getting imported (and run without the `__main__` check), that's beyond our scope right now.
