### ISSUE TITLE
Change link to Degeneracy Hunter example

### ISSUE THREAD

**Issue by dangunter** [IDAES/idaes-pse#880]
Current link is into a GitHub PR. Should be:  https://idaes.github.io/examples-pse/latest/Examples/Tools/degeneracy_hunter_doc.html

**Comment by ksbeattie** [comment]
Which link is the one that needs to be fixed?

**Comment by ksbeattie** [comment]
The link to be fixed is here: https://idaes-pse.readthedocs.io/en/latest/explanations/modeling_extensions/diagnostics/index.html
