### ISSUE TITLE
PySMO Surrogate Tests Failing on Linux Due To Latest Numpy Release

### ISSUE THREAD

**Issue by bpaul4** [IDAES/idaes-pse#897]
I tracked down the source of a few reoccurring test failures (see the latest nightly run [here](https://github.com/IDAES/idaes-pse/actions/runs/2566917920)) and `numpy` updating to 1.23.0 is likely the main cause. As @OOAmusat is the main PySMO developer, I believe it's best if you check and address the `AssertionError` issues. The result changes seem minor to me.

**Comment by lbianchi-lbl** [comment]
@bpaul4, thanks a lot for spotting this and creating this issue. To try to make it more visible for developers while a fix is being worked on, I've pinned it so that it shows up at the top of the issues list.

**Comment by OOAmusat** [comment]
@ksbeattie @bpaul4 @lbianchi-lbl @dangunter 

i have not been able to reproduce this issue with a fresh install of IDAES on my local Ubuntu 18.04 machine in both Python 3.8 and 3.9. The tests run just fine for me.

 Dan and Ludovico suggested I do a pip freeze of my local working environment and compare with the CI; the resuts are attached here:
[frozen.txt](https://github.com/IDAES/idaes-pse/files/9024003/frozen.txt)
[ci-pip.txt](https://github.com/IDAES/idaes-pse/files/9024002/ci-pip.txt)


The only differences between the two are 
 ``bleach``
 ``cffi``,
``charset-normalizer``
``google-auth``
``jsonschema``
``nbclient``
``prompt-toolkit``
``requests``

None of these should be causing problems or is used explicitly in PySMO, so I'm not sure where to go from here.

**Comment by lbianchi-lbl** [comment]
@OOAmusat Thanks for running the checks. I agree on most of those not looking very suspicious, but (a very uneducated guess) wouldn't `cffi` potentially be able to affect the interaction between OS numeric libraries and numpy/Python/Pyomo through the C Foreign Function Interface?

**Comment by OOAmusat** [comment]
@lbianchi-lbl  The thing is that my local installation has the newer version of cffi (1.15.1) vs the 1.15.0 used by the CI, so if anything I owuld expect my local version to be the failing one.

Anyway, I downgraded to the 1.15.0 used by the CI and still have no test failures, so it's not that.

`(test_fixes_p39) ooamusat@ooamusat-virtual-machine:~/Desktop/fix_test_errors/idaes-pse/idaes/core/surrogate/tests$ pip install cffi==1.15.0
Collecting cffi==1.15.0
  Downloading cffi-1.15.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (444 kB)
     |████████████████████████████████| 444 kB 7.6 MB/s 
Requirement already satisfied: pycparser in /home/ooamusat/miniconda3/envs/test_fixes_p39/lib/python3.9/site-packages (from cffi==1.15.0) (2.21)
Installing collected packages: cffi
  Attempting uninstall: cffi
    Found existing installation: cffi 1.15.1
    Uninstalling cffi-1.15.1:
      Successfully uninstalled cffi-1.15.1
Successfully installed cffi-1.15.0
(test_fixes_p39) ooamusat@ooamusat-virtual-machine:~/Desktop/fix_test_errors/idaes-pse/idaes/core/surrogate/tests$ pytest test_pysmo_surrogate.py 
========================================================================= test session starts =========================================================================
platform linux -- Python 3.9.12, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/ooamusat/Desktop/fix_test_errors/idaes-pse, configfile: pytest.ini
plugins: cov-3.0.0
collected 105 items                                                                                                                                                   

test_pysmo_surrogate.py .........................................................................................................                               [100%]

======================================================================== slowest 100 durations ========================================================================`

**Comment by bpaul4** [comment]
I compared the Ubuntu Python 3.8 Nightly tests just [before](https://github.com/IDAES/idaes-pse/actions/runs/2539989339) and [after](https://github.com/IDAES/idaes-pse/actions/runs/2546859620) the errors appeared, checking the pip list outputs, and found these differences:

grpcio changed from 1.46.3 to 1.47.0
ipywidgets changed from 7.7.0 to 7.7.1
jupyter-console changed from 6.4.3 to 6.4.4
jupyterlab-widgets changed from 1.1.0 to 1.1.1
numpy changed from 1.22.4 to 1.23.0
widgetsnbextension changed from 3.6.0 to 3.6.1

The cffi version stayed same at 1.15.0

**Comment by OOAmusat** [comment]
Yeah, I still can't reproduce it. Also, some of the tests failing make no sense. The error on the first test is:

```
E           assert 0.00100829246...0427 ± 1.0e-09 == 0.0010082907974720001
E             comparison failed
E             Obtained: 0.0010082907974720001
E             Expected: 0.0010082924613410427 ± 1.0e-09
/home/runner/work/idaes-pse/idaes-pse/idaes/core/surrogate/tests/test_pysmo_surrogate.py:1798: AssertionError
```

indicating that the values are different for a tolerance of 1e-9. However, the test failing has the tolerance set explicitly to 1e-6:
```
for i in range(inputs.shape[0]):
assert pytest.approx(out["z1"][i], rel=1e-6) == (
                (
```
