### ISSUE TITLE
Request for documentation/examples for new ALAMOpy interface.

### ISSUE THREAD

**Issue by bspivey** [IDAES/idaes-pse#906]
I followed the AlamoPy example at the following link, and I received the error that alamopy has no attribute alamo.

https://idaes-pse.readthedocs.io/en/stable/explanations/modeling_extensions/surrogate/alamopy/index.html

When I investigated the submodules in alamopy, alamo does not appear either:
Found submodule almain (is a package: False)
Found submodule almconfidence (is a package: False)
Found submodule almexec (is a package: False)
Found submodule almlayer (is a package: False)
Found submodule almopts (is a package: False)
Found submodule almplot (is a package: False)
Found submodule almread (is a package: False)
Found submodule almutils (is a package: False)
Found submodule almwrite (is a package: False)
Found submodule example (is a package: False)
Found submodule optsTest (is a package: False)
Found submodule utilsTest (is a package: False)

Do you have an updated example that works with the current version of alamopy which does not have a function called "alamo"?

**Comment by andrewlee94** [comment]
@bspivey Unfortunately we are still working on examples for the new ALAMOpy interface, and I do not believe we have any ready to be shared. In the interim, we have some test examples you can look at which do include demonstrate the full workflow but do not have much explanation of the process: https://github.com/IDAES/idaes-pse/blob/main/idaes/core/surrogate/tests/test_alamopy.py

**Comment by ksbeattie** [comment]
This is related to: https://github.com/IDAES/examples-pse/pull/113
