### ISSUE TITLE
Ensure pressure changer documentation covers PR #925

### ISSUE THREAD

**Issue by adam-a-a** [IDAES/idaes-pse#927]
Based on the changes made in PR #925, we should ensure that the existing documentation adequately explains how certain config options might affect creation of the `pressure_changer` unit.

**Comment by ksbeattie** [comment]
@adam-a-a is this something for the Aug release (as in within the next week)?

**Comment by ksbeattie** [comment]
@adam-a-a I'm guessing that a "no".

**Comment by adam-a-a** [comment]
@ksbeattie - sorry for missing your comment! I'll double check the existing documentation and see how in depth it already goes. If it was fairly vague about the issue in the first place, I'd push this off. If not, I could try to squeeze it in for the Aug release.

**Comment by ksbeattie** [comment]
Thanks, I've push it to Nov.

**Comment by ksbeattie** [comment]
@adam-a-a, can you take another look at this?

**Comment by lbibl** [comment]
I am trying to conclude this issue. The current doc for the `pressure_change`, https://idaes-pse.readthedocs.io/en/stable/reference_guides/model_libraries/generic/unit_models/pressure_changer.html,  does not have obvious text in conflict to the changes made in PR #925 .  The only slight relation is the `work_mechanical` var listed in the Variables  table, where it is noted to reference `control_volume.work`.       If we want to note the change, I can add footnote under the table saying `control_volume.work` can still be constructed even if `energy_balance` is none.   However, the current  doc is just fine in my view.  I'd like to consult @andrewlee94 and others if you would like to put such a note or leave as is.  I can then close this issue with or without a tiny PR.

**Comment by andrewlee94** [comment]
@lbibl `work_mechanical` is the issue here - the fact that the model does certain things if `control_volume.work` does not exist needs to be documented somehow. It does not need to be much (e.g. a note block), but it does need to explain what happens in these case any why it might be useful.
