### ISSUE TITLE
Improve and Standardize Documentation

### ISSUE THREAD

**Issue by andrewlee94** [IDAES/idaes-pse#94]
This is a master issue for tracking issues with the IDAES documentation.

The IDAES documentation has grown somewhat organically up to this point, and there are a number of gaps in the current docs along with a lack of consistent style and formatting.

**Missing Content**

- [ ] Improve documentation on how and where to get support - notably emphasize the difference between the users and idaes developers mailing lists and when to use each. This is where we can try to encourage the growth of the user community.
- [ ] A number of modules in `ideas.core.util` do not have doc pages. Notable examples: config, exceptions, expr_doc, functions, math, misc, plot, testing
- [ ] Clarify usage of Docker, especially for those less familiar with the tool Notably, we should briefly explain when and why you should use one before explaining how. We should also make sure we clean up any remaining stray references to avoid user confusion.
- [ ] Improve flow of advanced user guide to help guide new developers.
- [ ] Improve documentation of code review section to fully explain expectations and requirements (both for potential reviewers and for contributors to understand what will be expected of them).
- [x] Document the visualization UI (as it now/soon-will work, current docs are very old)

**Style and Formatting Issues:**

- [ ] Add IDAES platform component terminology/acronyms and diagrams from paper in introductory page #95 
- [ ] Develop and document formatting standards for Sphinx docs (`.rst` files), e.g. how to mark class names, arguments, and variable/option names. These standards should then be applied across the existing IDAES docs.
- [ ] Develop, document and apply standards for formatting of doc strings in the code, and ensure these work properly with the Sphinx autodocs features
- [ ] Develop, document and apply standards for content when documenting each type of model (i.e. unit models, property packages).

**Comment by dangunter** [comment]
re: docstring formatting. The two obvious options are Google and Numpy formats. I think the majority of the code is Google. We can just point to the appropriate documentation for the given format, and also a documentation page about how to include restructured text in your docstrings. The official Python docs on are here: https://www.python.org/dev/peps/pep-0256/

**Comment by andrewlee94** [comment]
I think this is somewhat out of date now, with the move to Diataxis.
