### ISSUE TITLE
Deprecate caprese method categorize_dae_variables?

### ISSUE THREAD

**Issue by dallan-keylogic** [IDAES/idaes-pse#945]
Looking through `caprese.categorize` I see that there are two methods that do the same thing: `categorize_dae_variables_and_constraints` and `categorize_dae_variables`.  The former seems to be more general the latter, and the latter has problems like having empty lists as default arguments (rather than using `None` and creating a new empty list in the function). 

@Robbybp , can you tell us if `categorize_dae_variables` is obsolete and can be deprecated and/or removed, or whether we still need it for something?

**Comment by Robbybp** [comment]
As far as I'm aware, `categorize_dae_variables` is obsolete and can be deprecated. I forget the exact reason I left it in, but I think it was for a vague performance consideration - walking constraint bodies to detect differential equations could get expensive.
