### ISSUE TITLE
Prevent test suite from modifying data/config.yaml file

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/idaes-pse#953]
See: https://github.com/IDAES/idaes-pse/pull/948#discussion_r967367224

**Comment by ksbeattie** [comment]
Possible fixes:
- get the test to write this file into a tmp dir
- get the test to "clean up after itself" and undo the changes it made to the file
- not have this file in the repo, add it to .gitignore, and have the file generated by the test (then thrown away)

**Comment by dangunter** [comment]
Short fix would be to remove the test(s) that cause the data file to be modified.

**Comment by ksbeattie** [comment]
This will be taken care of by the forthcoming retirement of the DMF.

**Comment by lbianchi-lbl** [comment]
Resolved (hopefully) by #1484.
