### ISSUE TITLE
Fix broken link in IDAES `readme.md`

### ISSUE THREAD

**Issue by andrewlee94** [IDAES/idaes-pse#963]
Some of the links in the `README.md` file (that makes up the welcome page on Github) are out-of-date and/or broken.

E.g. https://idaes-pse.readthedocs.io/en/stable/getting_started/

Seeing as this serves as one of the entry points to getting IDAES, we should make sure these are up-to-date and maintained.

**Comment by dangunter** [comment]
Fixed
