### ISSUE TITLE
Deprecate default in documentation

### ISSUE THREAD

**Issue by dallan-keylogic** [IDAES/idaes-pse#972]
Although `default` has been excised from the repo's code, it's still showing up in automatically generated unit model documentation:

![image](https://user-images.githubusercontent.com/88728506/192035559-f3a268c8-9b70-4f31-a7cf-52676bc74a57.png)

**Comment by andrewlee94** [comment]
@dallan-keylogic Which version of the docs are you looking at? For one, `default` will still appear in the the stable docs until the next release.

**Comment by dallan-keylogic** [comment]
I'm looking at the docs being generated in my PID controller branch. Granted, I haven't merged main today, so it might already be obsolete.

**Comment by andrewlee94** [comment]
It is still showing up in the "latest" version on ReadTheDocs as well.

**Comment by andrewlee94** [comment]
I think the issue is line 50 here: https://github.com/IDAES/idaes-pse/blob/main/idaes/core/base/process_block.py
